export type Programme = "all" | "dubbo_ewaste" | "repair_cafe" | "library_of_things";
export type LearningLesson = { id: string; title: string; idea: string; steps: string[]; practice: string };
export type LearningCourse = {
  id: string; programme: Programme; title: string; summary: string;
  duration: number; level: "Getting started" | "Building skills" | "Advanced";
  source: string; sourceLabel: string;
  lessons: LearningLesson[];
  check: { question: string; options: [string, string, string]; answer: number; explanation: string };
};
type LessonInput = [string, string, string, string];
function course(id: string, programme: Programme, title: string, summary: string, duration: number,
  level: LearningCourse["level"], source: string, lessons: [LessonInput,LessonInput,LessonInput],
  question: string, options: [string,string,string], answer: number, explanation: string): LearningCourse {
  return { id, programme, title, summary, duration, level, source,
    sourceLabel: source.split("/").pop()?.replace(/\.md$/, "").replace(/-/g, " ") ?? "Source notes",
    lessons: lessons.map(([title,idea,steps,practice], i) => ({
      id: "lesson-" + (i+1), title, idea, steps: steps.split("|"), practice,
    })),
    check: { question, options, answer, explanation } };
}
export const courses: LearningCourse[] = [
  course("repair-electrical-safety","all","Electrical safety and stop-work decisions","Classify electric-shock, stored-energy and workshop hazards before handling a device.",50,"Getting started","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Draw the energy boundary","An unplugged appliance is not automatically safe: capacitors and batteries may still hold energy.","Distinguish extra-low-voltage circuits from mains circuitry.|Identify mains inlets, large capacitors and exposed conductors without opening the appliance.|Identify a competent supervisor and a stop-work point.","On photographs of three devices, mark each hazardous region and identify an escalation path."],
    ["Build a hazard-first intake","Intake inspection detects unsafe items before volunteers are tempted to start troubleshooting.","Screen for damaged plugs, water exposure, heat marks and unsafe modification.|Record owner permission and electrical condition without energising the device.|Quarantine uncertain mains devices and do not remove protective covers.","Write a go/quarantine/refer decision for a damaged power board and explain who may assess it."],
    ["Match task to competence","A general soldering course does not confer authority to perform prescribed electrical work.","Separate external low-voltage inspection from mains wiring work.|Use NSW electrical-work rules and site procedures for scope decisions.|Record training, supervision, testing and sign-off rather than self-certifying safety.","Draft a Repair Café rule for escalating appliances requiring mains electrical work."],
  ],"A donated mains appliance has a cracked power inlet. What should a new volunteer do?",["Quarantine it and refer to an appropriately competent person","Replace the inlet after watching an online repair demonstration","Try energising it to learn whether the inlet is really damaged"],0,"A damaged mains connection needs competent assessment; do not energise it to diagnose casually."),
  course("repair-lithium-batteries","all","Lithium-ion battery safety and triage","Identify swelling, damage, charging risks, isolation and safe downstream battery handling.",55,"Getting started","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Spot a battery emergency","Swelling, heat, puncture, odour or hissing can precede a serious incident.","Recognise warning signs on laptops, tablets, power banks and e-bikes.|Keep damaged packs out of normal storage and charging areas.|Use the site's emergency, isolation and escalation plan.","Make an intake poster showing three battery warning signs and their first safe response."],
    ["Prevent shorts and heat","Loose contacts, conductive clutter and unsuitable charging increase risk.","Use approved containers, insulated terminals and segregated storage as site policy requires.|Never puncture, flatten, bend, short or heat cells.|Do not use a soldering iron directly on bare lithium battery cells.","Plan the safe routing of a swollen tablet battery without touching the cell."],
    ["Document battery fate","Responsible repair and recycling need a documented hand-off, not a bin label.","Identify pack chemistry and condition when safely readable.|Record quarantine reason, handler and authorised downstream route.|Confirm local recycler acceptance criteria before moving packs.","Write a mock battery quarantine and downstream transfer record."],
  ],"A laptop battery is swollen but the laptop still boots. Which decision is safest?",["Run a short benchmark so the customer can see it is usable","Stop using or charging it and follow the damaged-pack procedure","Press the case flat and store it with other batteries for now"],1,"Damaged lithium packs should not be charged or treated as normal stock."),
  course("repair-circuit-fundamentals","all","Circuit fundamentals: volts to components","Apply voltage, current, resistance and basic semiconductor concepts to safe low-voltage circuits.",70,"Getting started","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Explain energy flow","Voltage is electrical potential difference; current is charge flow; resistance limits current.","Calculate current with I=V/R and power with P=VI.|Identify ground and current paths without treating ground as always safe.|Differentiate AC/DC and never use a practice circuit on mains.","Calculate the current through a 1 kΩ resistor on a 3 V battery, stating assumptions."],
    ["Read component behaviour","Resistors, capacitors, diodes, LEDs and transistors have different jobs.","Interpret resistor markings and LED polarity.|Explain why an LED needs a current-limiting resistor.|Recognise that capacitors can retain energy even when disconnected.","Sketch an LED and resistor series circuit and predict LED behaviour with the diode reversed."],
    ["Breadboard a safe circuit","Experiments should be reversible, low-current and measurable.","Use an approved current-limited, low-voltage battery or bench source.|Build an LED/resistor/switch circuit and record expected voltage drops.|Introduce a disconnected wire and explain how it changes current.","Build or simulate the circuit and submit your measurements and a fault explanation."],
  ],"Why does a simple battery-and-LED circuit normally need a resistor?",["To regulate the battery voltage to exactly zero after use","To prevent the switch from allowing reverse current into the cell","To limit current through the LED to a safe operating value"],2,"The resistor limits current; an LED connected without one can draw destructive current."),
  course("repair-multimeter-diagnostics","all","Multimeter measurements and safe interpretation","Choose correct meter functions, read meaningful measurements and avoid destructive mistakes.",60,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Check the meter before the circuit","Wrong sockets or settings can short supplies or damage a meter.","Check probes, CAT ratings, lead position and internal fuse status.|Distinguish V/Ω jack from current-input jack.|Restrict first exercises to known low-voltage DC circuits.","Set up the meter to read a 1.5 V battery and explain why a current jack would be wrong."],
    ["Measure without creating faults","Voltage is measured across nodes; resistance and continuity require safe de-energisation.","Record polarity, expected range and actual DC readings.|Remove power before a resistance or diode-mode test.|Treat buzzer continuity and no-load voltage as clues, not universal proof.","Draw where both probes sit for a two-point voltage measurement across an LED."],
    ["Diagnose an open path","Combine an expected circuit state with a discriminating measurement.","Predict voltage readings around a known battery/resistor/switch network.|Use continuity only after disconnecting the source.|Distinguish an open switch from a faulty LED using recorded evidence.","Write a fault table for three simulated causes of a dark LED."],
  ],"Which measurement is acceptable with a disconnected, verified-safe circuit?",["Continuity across a switch after all sources are removed","Resistance across a charging tablet while the USB cable is attached","Continuity on a battery pack while its charger stays connected"],0,"Resistance and continuity testing must not be performed on energised circuits."),
  course("repair-fault-finding","all","Systematic electronics fault-finding","Turn vague symptoms into testable hypotheses, controlled checks and documented outcomes.",65,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Clarify symptoms and history","A repeatable symptom is more valuable than a random component swap.","Collect owner history, water exposure and prior repair attempts.|Separate observed symptoms from assumptions.|Photograph condition and record reproducibility.","Write an intake note for a laptop described only as 'won't turn on'."],
    ["Design a discriminating test","Good troubleshooting chooses the lowest-risk check that separates plausible causes.","Make a fault tree for power, display and storage symptoms.|Check external conditions before board-level actions.|Decide what evidence would falsify your first hypothesis.","Create a three-branch diagnostic plan for no display with a working power LED."],
    ["Close the evidence loop","A replaced component is not a successful repair until the original fault stays resolved.","Record tests, changes and measurements in chronological order.|Retest the original symptom and run appropriate stability checks.|Identify unknowns and when to stop.","Write a final repair note including one failed hypothesis and evidence of verification."],
  ],"A laptop shows a power LED but a black internal panel. What's the next best approach?",["Replace the motherboard immediately because the fault is internal","Make a display-path fault tree and choose low-risk separating tests","Assume Windows is corrupted and erase its drive before any tests"],1,"Fault trees reduce guesswork and destructive interventions."),
  course("repair-esd-disassembly","all","ESD-safe disassembly and delicate connectors","Open low-voltage devices methodically and protect flex cables, screws and connectors.",60,"Getting started","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Prepare an organised work area","Electrostatic discharge and mixed screws can turn a repairable device into scrap.","Use an ESD-safe bench and appropriate handling methods.|Record device identity and owner permission before opening.|Create a screw map and take staged photos.","Sketch a laptop disassembly plan and mark the parts most susceptible to damage."],
    ["Treat connectors as mechanisms","ZIF, FPC, board-to-board and coax connectors fail when forced.","Recognise flip-lock versus slide-lock flex mechanisms.|Follow device service guidance for release direction.|Never pry a battery connector with metal tools near cells.","On a scrap board, label the connector type and how its latch opens."],
    ["Reassemble and inspect","A repaired device must be safe, functional and mechanically sound after assembly.","Check cable seating and screw locations before power-up.|Inspect pinched cables, missing insulation and damaged seals.|Perform documented non-destructive functional checks.","Complete a mock reassembly checklist for a retired laptop."],
  ],"A ribbon cable won't release from its socket. What's the right first move?",["Pull with extra force because the connector may be glued","Apply heat directly to the plastic connector to loosen it","Identify the latch type using the service guide before acting"],2,"Connector latches differ; forcing a flex cable damages it or the socket."),
  course("repair-usbc-power","dubbo_ewaste","DC charging paths, USB-C and power delivery","Diagnose documented low-voltage charging systems and understand USB-C negotiation.",75,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Map the input path","Power failure may involve the charger, cable, port, fuse, battery or controller.","Read output polarity and ratings on an external approved adapter.|Distinguish USB-A power from USB-C PD negotiation.|Explain why a compatible-looking plug can still be unsuitable.","Build a no-power decision tree starting with charger, cable and port checks."],
    ["Recognise USB-C evidence","USB-C can carry power, data and alternate modes; passive cables are not all equal.","Identify port orientation and mechanical failures without probing fine contacts.|Use a trusted USB-C power tester on intact equipment only within its rating.|Understand source/sink roles and negotiated voltage profiles.","Compare a USB-C charge request and a barrel adapter using their published specifications."],
    ["Stop at hazardous board work","Current-limited work on low-voltage boards still needs competence and ESD planning.","Differentiate charging-connector repair from PMIC IC diagnosis.|Do not open mains adapters or energise a damaged power supply.|Escalate suspected board shorts rather than injecting unverified voltages.","Write a safe action plan for a bent laptop charging port."],
  ],"Why can two USB-C chargers behave differently with the same laptop?",["The PD profiles and cable capabilities may not meet requirements","USB-C plugs always deliver the same voltage regardless of devices","Both chargers must have defective power outputs if one fails"],0,"USB-C PD uses advertised capabilities and negotiation; connector shape is not enough."),
  course("repair-schematics-pcbs","dubbo_ewaste","Reading schematics, boardviews and PCBs","Understand symbols, nets, reference designators and simple board-level fault paths.",85,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Translate symbols to hardware","A schematic is a connectivity model; a boardview is a location map.","Identify R, C, D, Q, U, J and F designators.|Explain common ground, net names and power rails.|Distinguish schematic logic from physical board placement.","Annotate a supplied LED circuit with components, voltage rails and ground."],
    ["Follow a safe signal path","A diagnostic path connects expected function to measurable evidence.","Trace battery to protection to regulator to load in a simple toy circuit.|Locate a fuse and connector on an unpowered scrap board.|Use datasheets for pin names rather than inventing voltages.","Trace a low-voltage power rail on an open reference schematic and label test points."],
    ["Use references critically","A boardview made for the wrong revision can mislead diagnosis.","Match make, model and exact board revision.|Document evidence source and uncertain pinout.|Avoid powering a board merely to satisfy a reference measurement.","Write a source-confidence note for two conflicting boardviews."],
  ],"A boardview labels a connector differently from the schematic for your device. What next?",["Probe likely pins using an assumed board revision and compare values","Confirm the exact board revision and validate nets before measurement","Replace the connector first because part names rarely matter"],1,"Board revisions and pinouts must be checked before testing or rework."),
  course("repair-through-hole-soldering","repair_cafe","Through-hole soldering and joint inspection","Make reliable joints on unpowered practice boards with suitable ventilation and heat control.",80,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Prepare for safe soldering","A soldering iron creates burn, fume and lead-handling risks even on safe circuits.","Use dedicated ventilation, eye protection and a heat-safe surface.|Learn tip cleaning/tinning and flux selection.|Keep batteries, plastics and high-energy parts away from rework.","Draw your workbench layout and identify burn, fume and contamination controls."],
    ["Form a sound through-hole joint","Heat the pad and lead together so solder wets both surfaces.","Practise adding a modest amount of solder to clean practice pads.|Recognise insufficient wetting, bridges and overheated pads.|Let joints cool without movement.","Solder five resistors on an unpowered practice kit and photograph the front and back."],
    ["Inspect and test workmanship","Visual quality and continuity are necessary but not sufficient checks.","Inspect wetting, shape, pad damage and joint spacing with magnification.|Use continuity only with the circuit unpowered.|Clean flux according to board and chemistry recommendations.","Compare three practice joints and justify accept/rework decisions."],
  ],"A dull joint wets only the component lead but not the copper pad. What is the concern?",["It is an ideal joint because the solder forms a narrow bead","Poor wetting may cause an intermittent or high-resistance connection","The solder will flow properly when the circuit is powered on"],1,"A sound joint must wet both pad and component lead without bridges."),
  course("repair-desolder-replace","repair_cafe","Desoldering and replacing damaged parts","Remove through-hole components and connectors without lifting pads or damaging nearby parts.",75,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Choose a removal method","Wick, pumps and hot tools have different effects on fragile PCB copper.","Select solder wick or a vacuum pump for an appropriate scrap through-hole joint.|Use flux and correct tip geometry without excessive force.|Protect plastics and adjacent parts from heat.","Decide how you'd remove an old unpowered switch without lifting its solder pads."],
    ["Remove components cleanly","Force during removal often causes more damage than the faulty component.","Practise on a sacrificial low-voltage board.|Clear the hole and allow joints to cool; avoid repeated long heating.|Inspect pad adhesion before replacement.","Remove a scrap two-pin component and record whether the pads survived."],
    ["Verify the replacement","The replacement must match rating, pinout and mechanical function.","Compare manufacturer marking and orientation.|Solder and visually inspect both sides of the board.|Test continuity and functionality on a safely powered practice circuit.","Document one replaced switch with before/after close-up photos."],
  ],"A through-hole pin is stuck and the pad begins lifting. What's the sensible response?",["Stop pulling, reassess heat transfer and select a gentler technique","Continue levering until the component detaches and then tidy the pad","Increase force while the solder is cool to avoid further heating"],0,"Excess force can tear pads and internal copper connections."),
  course("repair-smd-microsoldering","dubbo_ewaste","SMD rework and microsoldering foundations","Learn fine-pitch work on expendable boards before attempting valuable motherboard repairs.",100,"Advanced","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Recognise SMD scale","Small resistors, capacitors, QFN and fine-pitch connectors demand different skills.","Distinguish 0603/0402 passives from fine-pitch packages.|Prepare lighting, magnification, flux and a stable fixture.|Know when commercial rework tools and supervision are required.","Identify three SMD footprints on a practice PCB photo and choose tools."],
    ["Control heat and nearby components","Thermal damage can lift pads, warp boards and damage sensitive components.","Practise placing a larger SMD resistor on a sacrificial practice board.|Minimise heat exposure and protect nearby components.|Never apply hot air to a battery pack or unknown high-energy board.","Inspect and photograph a single SMD practice joint, noting wetting and alignment."],
    ["Evaluate a board-level repair","An apparent short or missing rail does not prove an IC is defective.","Record symptoms and safe board-level baseline checks.|Avoid transplanting PMIC or SPD parts without confirmed compatible part and firmware.|Require microscope inspection and supervised acceptance testing for advanced repairs.","Write a hypothetical decision note on when microsoldering should be referred out."],
  ],"A board is missing one voltage rail. Is the power-management IC automatically faulty?",["Yes, any missing rail is proof the power IC must be replaced","Yes, but only when the device also has an overheating problem","No, the surrounding circuitry and protection path require diagnosis"],2,"Missing rails have many potential causes; chip swapping without diagnosis risks more damage."),
  course("repair-laptop-refurb","dubbo_ewaste","Laptop repair, testing and refurbishment","Inspect, diagnose, upgrade and verify donated laptops without exposing previous owners' data.",85,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Intake before booting","Ownership, batteries and data come before a quick functional test.","Check legal transfer and serial number.|Inspect swelling, liquid damage, missing screws and unsafe adapters.|Classify data-bearing media as restricted pending approved sanitisation.","Write a device intake card for a donated HP laptop with no drive paperwork."],
    ["Test components systematically","A methodical hardware baseline beats speculative replacement.","Test RAM, storage health, fan behaviour, display, ports and charging.|Check service manuals and part compatibility before swapping screens or DIMMs.|Separate hardware failures from firmware and software faults.","Create a before/after bench-test checklist for a refurb laptop."],
    ["Grade the outcome","A refurb is only valuable when limitations and faults are honestly recorded.","Record battery wear, thermal stability, accessories and cosmetic defects.|Run appropriate stress and memory checks.|Prepare a truthful resale/donation grade and returns information.","Produce a mock refurbishment certificate with unresolved issues clearly labelled."],
  ],"A donated laptop passes boot testing but its data ownership is unclear. What now?",["Reset the operating system and list it as ready for donation","Quarantine the data-bearing drive until authorised handling is established","Give it to a volunteer for personal use if the login screen is clear"],1,"Device function does not authorise access to, deletion of or transfer of data."),
  course("repair-pat-verification","repair_cafe","Portable appliance testing and referral","Understand electrical inspection/testing scopes without confusing a short course with legal authorisation.",70,"Advanced","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Separate inspection and testing","Visual checks, electrical testing and repair authorisation have distinct boundaries.","Read applicable NSW electrical safety and WHS guidance.|Identify hazards that warrant immediate tag-out.|Understand when a competent test-and-tag specialist is needed.","Sort six imaginary donated appliances into accept, quarantine or refer categories."],
    ["Interpret outcomes cautiously","A PAT result is not proof every possible fault is absent.","Understand earth continuity, insulation and leakage concepts at theory level.|Learn why test method depends on appliance class and condition.|Do not attempt live mains measurements or open appliances as unsupervised practice.","Describe what an inspector should record after a failed test, without performing it."],
    ["Release and documentation","Repairs and public return need documented sign-off matched to risk and competence.","Write a Repair Café referral checklist.|Separate operational permission from completion of an LMS lesson.|Set a release/no-release decision requiring authorised testing where relevant.","Draft a handover note for a toaster with a damaged lead."],
  ],"Can a volunteer sign off all mains repairs after passing this online lesson?",["Yes, once their assessment score is above eighty percent","Yes, but only if another volunteer watches the repair","No, task-specific competence and applicable legal requirements still govern"],2,"LMS completion is educational and never substitutes for legal competence or necessary licences."),
  course("repair-itad-sanitisation","dubbo_ewaste","Secure data sanitisation and ITAD traceability","Choose storage-safe outcomes, record custody and verify sanitisation under NIST SP 800-88 Rev.2.",90,"Advanced","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Establish authority and inventory","Ownership and drive identity are prerequisites for safe sanitisation.","Record device, media serial, owner consent, staff handler and custody timestamps.|Identify HDD, SATA SSD, NVMe and embedded storage.|Escalate unmanaged accounts, encrypted drives and missing ownership evidence.","Design a chain-of-custody record for three mixed donated laptops."],
    ["Choose the right sanitisation path","Erase commands, encryption keys and verification differ across storage technology.","Distinguish Clear, Purge and Destroy objectives.|Select a documented, device-supported method under policy.|Do not assume overwriting a modern SSD addresses all physical blocks.","Write a sanitisation decision tree for HDD, SATA SSD and NVMe media."],
    ["Verify and close the record","A tool saying 'success' is one evidence item, not an entire certificate.","Preserve erasure report identity and verify the media and method against the asset.|Record failed attempts, quarantine and downstream controls.|Include an accountable review and authorised release decision.","Draft a mock sanitisation certificate and identify two missing evidence fields."],
  ],"An SSD overwrite reports success but the method is not verified for its controller. What should you do?",["Mark it fully sanitised because the process reported completion","Treat it as unverified and investigate an approved controller-supported method","Discard the logs and run an operating-system reset before resale"],1,"A trustworthy sanitisation outcome requires a suitable method and verification."),
  course("repair-triage-economics","all","Repair triage, salvage and circular economics","Balance safety, labour, demand, parts, sustainability and customer consent.",70,"Building skills","docs/ELECTRONICS-REPAIR-15-SKILL-LEARNING-PATH-2026-10-11.md",[
    ["Classify the device honestly","Reuse-first still requires a safe, economical and realistic route.","Estimate parts cost, skill requirements and age-related failures.|Record owner requirements and data-bearing status.|Classify as repair, reuse-as-is, parts harvesting or approved recycling.","Triage three fictional laptops with different damage and resale values."],
    ["Calculate the true repair cost","A free device can cost too much in parts, staff time or warranty returns.","Estimate labour hours, consumables, storage and disposal.|Consider life expectancy and availability of replacement alternatives.|Document uncertainty and avoid false environmental precision.","Compare a $90 battery repair with a replacement refurbished laptop on cost per useful year."],
    ["Record parts and outcomes","Parts must remain traceable from donor to recipient and through testing.","Record serial/model compatibility and condition.|Test harvested components and disclose limitations.|Log final repair outcome and routes for unusable batteries/media.","Create a parts harvest manifest with five reusable items and downstream disposition."],
  ],"A repair costs less up front but fails again every month. How should its value be assessed?",["Compare only the initial repair quote because reuse always beats replacement","Recycle it immediately without considering repair evidence or customer needs","Compare reliability, remaining service life and full support costs"],2,"Total useful life, safety and repeated failures matter more than the first invoice."),

  course("dubbo-ewaste-uncontacted-leads","all","Finding ethical e-waste sourcing leads in Dubbo","27 new prospect routes not found in the 10 October outreach batch; ask about ownership before accepting devices.",35,"Building skills","docs/DUBBO-NEW-EWASTE-OUTREACH-LEADS-2026-10-11.md",[
    ["Distinguish repair shops from organisational fleets","Repairers may handle customer-owned equipment while employers may own office assets.","Read the new research for Custom Computer Creations, Inland Technology, Westhaven and MAAS.|For each candidate, identify who owns the devices.|Use verified contact pages and ask for the correct role, not a staff member’s personal email.","Choose two different prospects; write one evidence-backed question for each."],
    ["Check ownership and safe handoffs","A replaced device is not automatically free, transferable or safe to accept.","Record releasing organisation, permission, model/serial and data-bearing status.|Ask about leases, warranty returns and current recycling/ITAD contracts.|Only propose a five-device pilot once sanitisation, battery safety and downstream routing are scoped.","Draw a simple owner → custody → data → destination process with one stop condition."],
    ["Keep the project part-time and independent","Avoid mass emailing, uncontrolled stockpiles and conflicts involving your employer.","Compare proposed contacts against the outreach register.|Contact two organisations, not twenty-seven in one day.|Plan a 15-minute follow-up only after a positive response; never use employer client details.","Set a two-week outreach limit, desired learning outcome and review date."]
  ],"What must you establish before taking possession of an old laptop?",["That it is no longer wanted by the current user","Who has legal authority to release it and what data/security obligations apply","That the business sells computers"],1,"The lawful owner and their authorised representative determine transfer; sanitisation, custody, safety and existing contracts also matter."),

  course("dubbo-business-field-guide","all","Inside Dubbo’s technology and repair businesses","Explore 15 locations, public role maps, workplace evidence and useful project partnerships from 67 sources.",45,"Building skills","docs/DUBBO-TECH-BUSINESS-FIELD-GUIDE-2026-10-10.md",[
    ["Models, people and workplace evidence","A retail repairer, MSP, print dealer and POS installer offer different kinds of learning and partnership.","Read the report dossiers for Tech Savvy, Gravity, Orana and Desspos.|Compare published roles with unknown reporting lines.|Treat employer claims and old employee reviews according to their date and location.","Choose two businesses. Record one documented practice, one evidenced role and three workplace questions."],
    ["Follow the device and its authority","Replacement work does not establish ownership of the outgoing device.","Read Orana, Colton, Winc and Viatek lifecycle sections.|Ask what is already contracted and who can release equipment.|Define permitted categories, data responsibilities, custody, costs and final destination before a pilot.","Draft a five-device handoff proposal with an authority check and a stop condition."],
    ["Choose a project experiment","Resolve a small uncertainty before committing time, money or collection capacity.","Use the report’s separate DubboEwaste, Repair Café, Library of Things and AssetFlow experiments.|Prepare two short discovery agendas; outreach has not been sent.|Use the 30-day plan to record answers, review evidence and decide whether to stop, adjust or repeat.","Write a one-page plan with two research leads, one decision owner to verify and one measurable outcome."]
  ],"A business replaces client laptops. What must be verified before proposing reuse?",["Only the number of laptops","Ownership, release authority, data responsibilities and existing arrangements","Whether the shop has good customer reviews"],1,"A service relationship is not proof of ownership or permission to transfer devices. Read the full source report for each business’s evidence and gaps."),

  course("circular-thinking","all","Circular economy essentials","See the difference between reusing, repairing, sharing and recycling.",25,"Getting started","docs/DUBBO-CIRCULAR-ECONOMY-IN-PRACTICE-2026-10-08.md",[
    ["The life of an object","A useful object can have more than one life before it becomes waste.","Think about the resources used to make it.|Ask whether it can be used again as-is.|Consider repair or sharing before recycling.","Choose one object near you. Name two ways it could remain in use."],
    ["The local picture","A national solution is not necessarily available in Dubbo.","Check local availability and acceptance rules.|Separate evidence from assumptions.|Record useful unanswered questions.","Find one Dubbo service and note what it actually accepts."],
    ["Make the better next choice","The most useful action is a decision that fits the item and the person's situation.","Reuse if safe and practical.|Repair when cost and safety make sense.|Recycle through an appropriate pathway when reuse is no longer suitable.","Write the next action for a broken but otherwise useful item."]
  ],"Which choice normally preserves the most value in an item?",["Recycle it immediately","Keep it safely in use","Put it into general waste"],1,"Keeping an item useful commonly avoids more replacement activity."),
  course("volunteer-welcome","all","Welcome and volunteer basics","Learn what to expect, how to ask for help and how to contribute within your role.",20,"Getting started","docs/FAMILY-CAPACITY-ITAD-REPAIR-CAFE.md",[
    ["Know your scope","A volunteer should know which jobs they can do and where to stop.","Check the session lead and your assigned role.|Ask about site rules and escalation.|Never work beyond your own training.","Write down who you would ask about a task that feels unsafe."],
    ["Good handovers","A clear handover protects people, equipment and time.","Record what was received and who owns it.|Explain what you tried and what you observed.|Avoid claiming a repair is complete before a check.","Practise a two-sentence handover to the next volunteer."],
    ["Respect people's time","Warmth and realistic expectations make community services trustworthy.","Introduce yourself and listen first.|Explain limitations without blame.|Make sure the visitor understands the next step.","Describe how you would welcome someone who is nervous about asking for help."]
  ],"What should you do when a task is outside your skills?",["Try anyway to avoid a delay","Stop and ask the appropriate supervisor","Hand it back without explanation"],1,"Competence and clear escalation matter more than appearing capable."),
  course("workshop-safety","all","Workshop safety foundations","Recognise common risks and know when to stop before someone gets hurt.",35,"Getting started","docs/RESEARCH-06-BATTERY-ELECTRICAL-WORKSHOP-SAFETY.md",[
    ["Spot the hazards","A tidy bench is a starting point, not a full risk assessment.","Look for damaged cords, exposed power and trip hazards.|Keep sharp and hot tools controlled.|Check emergency contacts and first-aid arrangements.","Walk around your work area and identify three potential hazards."],
    ["Battery and power boundaries","Lithium batteries and mains electricity require clear authority and competence.","Isolate suspect devices where safe to do so.|Never puncture or crush swollen cells.|Do not attempt unauthorised mains-electrical repairs.","Practise explaining why a swollen battery needs escalation, not experimentation."],
    ["Stop-work decisions","Volunteers must be free to stop a job without pressure.","Pause when something is hot, damaged, leaking or uncertain.|Tell the lead and keep others clear.|Record the hazard and agreed next step.","Describe your stop-work response to a device smelling of burning."]
  ],"A laptop battery is swollen. What is the appropriate first response?",["Puncture it to release pressure","Stop work and follow the isolation/escalation procedure","Continue charging to diagnose it"],1,"Damaged lithium cells can ignite; protect people and escalate."),
  course("privacy-consent","all","Privacy, consent and trust","Handle people's possessions and information respectfully.",30,"Getting started","docs/RESEARCH-05-DATA-IDENTITY-PRIVACY-SOP.md",[
    ["Ask before accessing","Permission to look at a device is not blanket permission to explore personal data.","Explain the intended action.|Avoid personal photos, files and accounts.|Ask before using or sharing images of people or belongings.","Write a simple consent question before inspecting a device."],
    ["Record less","Collect only information necessary for the service.","Use asset IDs instead of unnecessary personal details.|Protect paper forms and digital records.|Avoid copying passwords or access tokens into notes.","Review an intake form and remove one unnecessary question."],
    ["Respond to a mistake","Quickly containing a privacy mistake is better than hiding it.","Stop further disclosure.|Tell your supervisor promptly.|Follow the incident and notification procedure.","Explain the first two actions after sending a record to the wrong person."]
  ],"Which record is most appropriate?",["A full copy of a customer's photo folder","An asset ID and agreed service notes","A saved password for convenience"],1,"Data minimisation reduces exposure and supports trust."),
  course("kind-communication","all","Welcoming, accessible conversations","Make sessions approachable for newcomers, children and people with different needs.",25,"Getting started","docs/RESEARCH-14-COMMUNITY-ACCESSIBILITY-IMPACT.md",[
    ["Listen before explaining","Ask what the person hopes to achieve instead of assuming.","Use a welcoming introduction.|Let the visitor describe the problem.|Check their preferred way of learning.","Practise one open question and one reflective summary."],
    ["Teach with consent","Demonstration is more useful when the visitor can see and participate.","Explain one step at a time.|Ask whether they want to have a go.|Avoid jargon and unexplained acronyms.","Explain an SSD upgrade without technical jargon."],
    ["Close well","Not fixing an item can still be a useful outcome.","Explain what was found and what is uncertain.|Offer realistic referral or next steps.|Ask if anything remains unclear.","Give a respectful handover for an item you cannot repair."]
  ],"What is a good first question?",["Why did you break this?","What were you hoping to use this for?","Do you know what a motherboard is?"],1,"Start with the person's goal, not a technical assumption."),
  course("evidence-observation","all","Good evidence and field notes","Separate observations, assumptions and claims so the next person can check your work.",30,"Building skills","docs/RESEARCH-16-CLOSURE-EVIDENCE-REGISTER.md",[
    ["Facts versus hypotheses","A research note should say what was checked and what remains unknown.","Record the source and date.|Label hypotheses and estimates clearly.|Distinguish local findings from statewide comparisons.","Rewrite an uncertain claim as a testable hypothesis."],
    ["Observe consistently","Repeatable observations are more valuable than impressive anecdotes.","Use the same fields each time.|Capture time, conditions and limitations.|Protect any sensitive names or identifiers.","Design a three-field observation card for a community pilot."],
    ["Close the loop","An unanswered question becomes more useful when it has an owner and a method.","Write the exact question.|Name a practical evidence method.|Record the decision and what would change it.","Choose a gap that needs a local interview rather than web search."]
  ],"A figure comes from a statewide report. Can it be presented as a measured Dubbo result?",["Yes, if plausible","No, its scope must be stated","Yes, if the report is recent"],1,"Evidence must retain the scope and limitations of its source."),
  course("repair-first","all","Repair before replacement","Learn to make an informed repair-or-replace decision.",35,"Building skills","docs/REPAIR-FIRST-DUBBO-IMPLEMENTATION-PLAN.md",[
    ["Check before discarding","A quick diagnosis can prevent an unnecessary replacement.","Clarify the fault and the person's goals.|Estimate safety and repair feasibility.|Identify a local repair or parts option.","Choose one common broken item and list its likely low-cost fixes."],
    ["Cost, time and confidence","A cheap repair is not automatically best, and an expensive repair is not automatically poor.","Consider parts and labour.|Consider reliability, warranty and time.|Be honest about uncertainty.","Compare a repair quote with a realistic replacement."],
    ["Refer appropriately","A useful referral may be better than overpromising.","Look for a qualified local service where needed.|Explain what you have and have not checked.|Ask permission before passing on details.","Prepare a short referral note for a specialist job."]
  ],"Which is a good repair recommendation?",["Always repair regardless of cost","Explain options, safety, cost and uncertainty","Always replace electronics older than three years"],1,"A transparent choice is better than a rigid rule."),
  course("ewaste-intake","dubbo_ewaste","Device receiving and chain of custody","Bring devices into a traceable workflow without losing ownership or condition evidence.",45,"Getting started","docs/INTAKE-AND-DATA-PAPERWORK-PACK.md",[
    ["Before accepting","Confirm authority, permitted categories and safe handling.","Ask about ownership and transfer authority.|Check for prohibited or hazardous items.|Set clear expectations about data and downstream handling.","Draft your intake questions for a laptop donated by a business."],
    ["Identify and label","A unique label connects a physical item to its digital record.","Assign the correct job and lot.|Capture maker, model, serial when authorised and condition.|Attach a durable asset ID before moving it.","Practise a label-to-record check on one device."],
    ["Handover to triage","The next worker needs a truthful snapshot.","Log defects and accessories.|Flag data-bearing media and hazards.|Record time, location and handover state.","Prepare a receiving handover for a laptop with no charger."]
  ],"What should happen before an accepted laptop moves to triage?",["Give it a unique tracked identity","Erase its labels","Advertise it for sale"],0,"Receiving links custody, condition and subsequent actions."),
  course("device-triage","dubbo_ewaste","Device triage and grading","Decide whether a device should be reused, repaired, harvested or recycled.",50,"Building skills","agyDOCS/Triage-Skills-Guide.md",[
    ["Start with a visual check","Look for signs that make testing unsafe or uneconomic.","Check casing, hinges, ports and display.|Identify liquid damage and swelling.|Keep unknown battery risks isolated.","Inspect a laptop and write three observations without diagnosing yet."],
    ["Run repeatable checks","A consistent sequence prevents missed faults.","Test with safe power methods.|Record screen, keyboard, storage and core function results.|Do not treat an untested feature as passed.","Build a repeatable seven-step check sequence."],
    ["Choose a disposition","A route should be explainable and revisitable.","Compare likely repair effort and value.|Account for data-bearing media.|Record the decision and supporting test results.","Route three sample laptops: usable, fixable, and unsafe."]
  ],"An untested keyboard should be recorded as…",["Passed","Not tested","Failed irreparably"],1,"Unknown is different from passed or failed."),
  course("storage-erasure","dubbo_ewaste","Data sanitisation and verification","Understand sanitisation decisions and why evidence matters.",55,"Advanced","docs/ASSETFLOW-ERASURE-DIAGNOSTICS-INTEGRATIONS.md",[
    ["Identify every medium","A laptop can contain removable storage and hidden additional media.","Check reported drives against the physical device.|Record interface and relevant restrictions.|Keep data-bearing assets controlled before reuse.","Draft a storage inventory for a laptop plus a USB drive."],
    ["Choose the right method","Clear and Purge choices depend on medium, capability and risk.","Follow the approved NIST-aligned policy.|Check HPA, DCO, OPAL and freeze state where applicable.|Escalate unsupported or locked media.","Explain why a generic overwrite is not always sufficient for an SSD."],
    ["Verify the result","A claimed wipe is not equivalent to verified sanitisation.","Record method, tool, operator and result.|Verify according to procedure.|Quarantine failures and link evidence to the asset.","Review an example certificate and name three missing fields."]
  ],"A sanitisation task reports failure. What next?",["Issue a pass certificate anyway","Quarantine and investigate under the approved policy","Sell the drive without further checks"],1,"Failures need escalation and traceable resolution."),
  course("diagnostic-bench","dubbo_ewaste","Laptop diagnostics fundamentals","Use observation and controlled tests to narrow a fault.",50,"Building skills","docs/PRACTICAL-TRAINING-SHEETS.md",[
    ["Describe the symptom","Start from what actually happens, not your first theory.","Record power, display and boot behaviour.|Try a safe and repeatable setup.|Separate intermittent from repeatable faults.","Write a fault description for a laptop that runs but its screen goes dark."],
    ["Test one variable","Changing one thing at a time makes results meaningful.","Check power delivery safely.|Use known-good parts where appropriate.|Document changed conditions and outcomes.","Plan a display test that distinguishes panel from external-output behaviour."],
    ["Record the diagnosis","Confidence belongs beside any conclusion.","Write observed results and what remains untested.|Make next steps proportionate to value and safety.|Escalate electrical or board faults outside competence.","Complete a simple diagnostic log for an unresolved fault."]
  ],"A laptop screen goes dark but the laptop stays powered. Should you conclude it fully shuts down?",["Yes","No, test display and power behaviour separately","Yes, if it is old"],1,"The symptom does not establish a complete power loss."),
  course("battery-safety","dubbo_ewaste","Lithium battery handling","Recognise unsafe packs and protect volunteers and downstream handlers.",40,"Getting started","docs/RESEARCH-06-BATTERY-ELECTRICAL-WORKSHOP-SAFETY.md",[
    ["Red flags","Swelling, heat, damage and leakage demand a different handling route.","Visually assess before charging.|Do not deform or probe compromised cells.|Know the isolation location and emergency plan.","List four signs that a battery needs escalation."],
    ["Controlled handling","Prevention includes storage, transport and separation.","Keep terminals and conductive materials controlled.|Use approved containment and procedures.|Never send damaged batteries into mixed scrap.","Inspect a mock battery-handling station for risks."],
    ["Downstream responsibility","A battery remains a risk after it leaves your bench.","Record condition and route.|Use suitable accepted downstream providers.|Retain evidence of correct transfer.","Write a short handover description for a damaged pack."]
  ],"Should a visibly swollen battery go into the normal testing queue?",["Yes, if powered off","No, follow the hazard procedure","Yes, after a brief charge"],1,"Suspect lithium batteries need separate safe handling."),
  course("refurb-upgrades","dubbo_ewaste","Refurbishment and parts strategy","Decide which repairs improve usability without consuming the whole workshop.",45,"Building skills","docs/RESEARCH-07-REPAIR-ECONOMICS-PARTS-STRATEGY.md",[
    ["Decide if worthwhile","Not every repair has positive value or useful impact.","Check likely sale/use outcome.|Account for labour, parts and uncertainty.|Avoid long-running projects without a purpose.","Estimate a simple SSD upgrade's total cost including labour."],
    ["Parts compatibility","Right parts, correct documentation and controlled sourcing matter.","Check model and connector before ordering.|Record donor-parts provenance.|Inspect and test replacements.","Prepare a compatibility checklist for a laptop RAM upgrade."],
    ["Finish the job","A repaired device must be retested.","Re-run diagnostics after repair.|Confirm storage sanitisation and software permissions.|Record parts used, failures and final grade.","Write a final test checklist for a refurbished notebook."]
  ],"A replacement part is installed. Is the job finished immediately?",["Yes","Only after appropriate re-testing and recording","If the laptop powers on once"],1,"Repairs must be verified before disposition."),
  course("reuse-resale","dubbo_ewaste","Resale, warranties and honest listings","Prepare devices for responsible resale or donation.",45,"Building skills","docs/LISTING-WARRANTY-CHECKLIST.md",[
    ["Describe the actual device","Trust depends on accurate specs, tests and flaws.","Record exact model and configuration.|List known defects and untested functions.|Keep private identifiers out of public adverts.","Draft a concise listing for a laptop with a cosmetic defect."],
    ["Price responsibly","Margin is not only the difference between sale price and parts.","Add labour, freight, fees and returns allowance.|Check comparable sold prices, not just asks.|Avoid unsupported impact or quality claims.","Calculate a hypothetical true resale margin."],
    ["Support a buyer","Consumer obligations and reasonable after-sale support matter.","Give accurate included items and limitations.|Use applicable Australian consumer law guidance.|Keep a traceable sale and return record.","Write a short, clear handover note for a refurbished device."]
  ],"How should an untested webcam be described in a listing?",["Works perfectly","Not tested","Brand new"],1,"Listings should distinguish tested functions from assumptions."),
  course("downstream-recycling","dubbo_ewaste","Recycling and downstream proof","Track what cannot be reused and verify where it goes.",40,"Building skills","docs/RESEARCH-11-DOWNSTREAM-ENVIRONMENTAL-CHAIN-OF-CUSTODY.md",[
    ["Sort correctly","Different materials and hazards demand different pathways.","Separate batteries and controlled waste.|Preserve data controls for all data-bearing media.|Check acceptance rules before dispatch.","Sort sample items into reuse, controlled processing and general waste."],
    ["Verify the provider","A waste handover is not proof of final recycling.","Record approved provider and acceptance evidence.|Check scope and any required credentials.|Keep transport and receiving documentation.","List the evidence you would request from a processor."],
    ["Report carefully","Impact figures require a defensible method.","Measure weights or counts consistently.|Avoid treating estimated diversion as exact.|Report uncertainty and methodology.","Write a cautious impact statement for ten processed laptops."]
  ],"Which is strongest evidence of responsible downstream processing?",["A casual verbal promise","Traceable transfer and verified processing records","An attractive recycling logo"],1,"Chain-of-custody and verifiable records are essential."),
  course("assetflow-basics","dubbo_ewaste","AssetFlow: your first shift","Navigate intake, assets, jobs and evidence without corrupting the record.",35,"Getting started","docs/ASSETFLOW-PLATFORM-BACKLOG.md",[
    ["Find your workspace","Only use features permitted to your role.","Start at your dashboard.|Find jobs, lots and assets.|Use the linked record rather than disconnected notes.","Locate a practice asset in the Search / Scan workflow."],
    ["Make a traceable update","The asset timeline should explain each change.","Check the asset ID before editing.|Record observations instead of speculation.|Avoid duplicate submissions.","Describe how you would prevent creating the same asset twice."],
    ["Close or escalate","Incomplete tasks should have a visible next owner.","Confirm the workflow state.|Link supporting tests or evidence.|Escalate exceptions rather than hiding them.","Create a handover checklist for the next shift."]
  ],"What should you check before updating a record?",["The exact asset identity","How many people are watching","Whether the form looks familiar"],0,"Record accuracy starts with the right asset."),
  course("repair-cafe-intro","repair_cafe","Repair Café: first session","Understand the proposed pop-up model and the volunteer's role.",30,"Getting started","docs/REPAIR-FIRST-DUBBO-PILOT.md",[
    ["How the café works","This is a community learning and shared-repair model, not a drop-off shop.","Welcome the owner and their item.|Explain that safe repair cannot be guaranteed.|Invite the owner to participate.","Practise explaining the concept in two sentences."],
    ["Your volunteer role","Hospitality and organisation matter as much as technical fixing.","Choose welcome, intake, fixer, learner or setup roles.|Know who makes safety decisions.|Accept only work within competence.","Pick two ways you could help without any repair expertise."],
    ["A good outcome","Diagnosed, referred and learned can be successes, even without a fix.","Capture a clear outcome.|Explain any referral and next steps.|Thank the owner for sharing the experience.","Write a positive handover for a non-repairable item."]
  ],"Does every item have to be repaired for the session to be worthwhile?",["Yes","No, learning and diagnosis can be useful","Only if the owner pays"],1,"The event is about learning, connection and practical next steps."),
  course("repair-cafe-intake","repair_cafe","Repair Café intake and triage","Welcome an item, identify hazards and match it to a safe station.",40,"Building skills","docs/RESEARCH-01-FRONT-DOOR-TRIAGE.md",[
    ["Ask the right questions","A short intake conversation sets safe expectations.","Ask what is broken and what changed.|Clarify ownership and consent.|Check electrical, battery and sharp-edge risks.","Role-play a two-minute intake for a broken lamp."],
    ["Route to the right person","Competence and workspace determine what can be attempted.","Match the job to a suitable volunteer.|Decline or refer high-risk items.|Keep any queue realistic and visible.","Decide whether a damaged mains-powered appliance is appropriate to accept."],
    ["Document the outcome","The owner should leave with a clear understanding.","Record attempted actions and limits.|Note whether fixed, diagnosed or referred.|Record safety concerns confidentially.","Complete a sample outcomes slip for an unsuccessful repair."]
  ],"What matters most when assigning a repair?",["How quickly someone volunteers","Matching risk, skills and permissions","How old the item is"],1,"Safe scope and competence take priority over enthusiasm."),
  course("repair-cafe-toolkit","repair_cafe","Hand tools and simple repairs","Use common tools carefully and learn to test a basic diagnosis.",45,"Building skills","docs/PRACTICAL-TRAINING-SHEETS.md",[
    ["Choose the correct tool","Using the wrong tool can damage the item or hurt someone.","Identify fastener type before turning.|Keep sharps controlled and parts organised.|Never force a seized or powered component.","Prepare a safe work area for opening a battery-free mechanical item."],
    ["Check before changing","Diagnose the fault without replacing parts at random.","Observe the symptom.|Test an accessible, safe cause.|Record what changed and what did not.","Describe a method for investigating a loose chair fitting."],
    ["Explain your limits","Confidence grows when volunteers report uncertainty plainly.","Check fit and function after a repair.|Keep safety-critical work for competent specialists.|Explain what wasn't tested.","Tell a visitor why a repair must stop even though you have tools available."]
  ],"Can a volunteer repair mains wiring just because they own a multimeter?",["Yes","No, authorisation and competence are required","Only on older devices"],1,"Owning tools is not evidence of suitable qualifications or safety procedures."),
  course("repair-cafe-running","repair_cafe","Running a welcoming event","Plan the venue, volunteer flow, check-in and a manageable first pilot.",40,"Building skills","docs/DUBBO-REPAIR-CAFE-VENUE-RESEARCH-2026-10-08.md",[
    ["Prepare the venue","Room layout must work for safety and for people.","Check venue permission and insurance.|Plan accessible welcome, queue and tool zones.|Identify evacuation, power and first-aid needs.","Sketch a small event with distinct welcome and repair areas."],
    ["Manage the session","A small pilot gives better learning than an uncontrolled queue.","Cap item intake to available skills.|Assign roles and breaks.|Explain wait times and what cannot be accepted.","Plan a three-hour pop-up event schedule."],
    ["Measure and improve","Learn from outcomes without collecting unnecessary personal information.","Count items by outcome.|Ask what visitors found useful.|Record safety incidents and improvements.","Write three questions for a volunteer debrief."]
  ],"What is the safest first-event plan?",["Unlimited walk-ins and all electrical repairs","A capped pilot matched to venue and volunteers","No intake records"],1,"Start within capacity and expand based on evidence."),
  course("repair-cafe-accessibility","repair_cafe","Inclusive teaching and community connection","Make repair activities welcoming for different ages, backgrounds and abilities.",30,"Getting started","docs/RESEARCH-14-COMMUNITY-ACCESSIBILITY-IMPACT.md",[
    ["Make participation possible","Visitors should not need technical vocabulary to belong.","Ask about comfort and access needs without assumptions.|Offer seating and visibility.|Explain how to opt out of tasks.","Choose one way to help a visitor who cannot stand for long."],
    ["Teach side by side","Learning together is often more important than finishing fast.","Demonstrate clearly and offer turns.|Adjust the pace to the visitor.|Invite questions without embarrassment.","Demonstrate how to tighten an accessible fastener verbally."],
    ["Keep a respectful atmosphere","No one should be pressured into repairs, photographs or public sharing.","Ask before photos.|Avoid blame about buying or breaking things.|Thank people for participation.","Rephrase a judgemental comment into a welcoming response."]
  ],"Should you photograph a visitor's repair for publicity without asking?",["Yes, it's a public event","No, get appropriate consent","Only if the repair succeeds"],1,"Consent and dignity are not optional."),
  course("things-foundations","library_of_things","Library of Things: getting started","Understand sharing services, ownership and why a small lending pilot works best.",30,"Getting started","docs/DUBBO-CIRCULAR-ECONOMY-IN-PRACTICE-2026-10-08.md",[
    ["Why borrow?","Some useful items are rarely used and costly to own.","Consider infrequent-use equipment.|Check whether borrowing is practical for the user.|Avoid buying inventory before demand is known.","Name three things people might borrow instead of buy."],
    ["Start with real demand","A service should be built around actual needs.","Ask what exact objects people want.|Estimate frequency, access and storage needs.|Keep the pilot inventory small and traceable.","Write three survey questions for a lending pilot."],
    ["Steward responsibilities","A friendly loan is still a responsibility.","Confirm member identity under approved rules.|Explain safe use and loan terms.|Track where the item is and when it returns.","Describe a good handover of a borrowed hand-tool kit."]
  ],"How should a new Library of Things decide what to stock first?",["Buy many popular-sounding items","Validate local demand and start small","Accept everything immediately"],1,"Measured demand and capacity should guide the collection."),
  course("things-catalogue","library_of_things","Cataloguing and kit completeness","Make shared items easy to find, check out and return.",40,"Building skills","docs/RESEARCH-09-INVENTORY-SYSTEM-OF-RECORD.md",[
    ["Describe every item","A useful catalogue entry connects a name to an actual object.","Assign a unique item ID.|Record condition, accessories and safe-use instructions.|Use clear photos when appropriate.","Describe a projector kit with its cables and remote."],
    ["Check out carefully","Borrowing should have visible accountability.","Match the user, item and approved loan period.|Explain inclusions and conditions.|Log handover time and item condition.","Draft a friendly handover checklist for camping gear."],
    ["Check return completeness","A return is not finished until the kit is ready for its next borrower.","Count components against the checklist.|Record faults or missing pieces.|Move items needing attention out of circulation.","Practise checking a hypothetical ten-piece tool kit."]
  ],"What should happen when a returned kit is missing a part?",["Mark it complete anyway","Record the missing part and hold or update availability","Discard the entire item"],1,"Accurate completeness records protect future borrowers."),
  course("things-maintenance","library_of_things","Maintenance, inspections and quarantine","Keep borrowed equipment ready for safe, repeated use.",45,"Building skills","docs/RESEARCH-06-BATTERY-ELECTRICAL-WORKSHOP-SAFETY.md",[
    ["Pre-loan checks","Inspection should match the risk and type of item.","Compare against a standard condition checklist.|Look for damage, missing instructions and recalls.|Do not lend unsafe or unverified equipment.","Draft a visual inspection card for a basic hand-tool kit."],
    ["Returns and cleaning","Every return is an opportunity to improve reliability.","Check cleanliness and completeness.|Record damage without blaming borrowers prematurely.|Dry and store items appropriately.","Plan a return workflow for a camping tent."],
    ["Quarantine and escalation","An uncertain item is not an available item.","Tag and isolate damaged items.|Set an owner for a qualified assessment.|Document the decision before re-lending.","Write a quarantine note for a tool with a cracked handle."]
  ],"A borrowed tool comes back with a cracked handle. What should happen?",["Put it straight back on the shelf","Remove it from circulation pending assessment","Lend it with a verbal warning only"],1,"Damaged shared equipment needs a controlled inspection."),
  course("things-service","library_of_things","Fair lending and community service","Set clear, equitable rules for reservations, fees and late returns.",35,"Building skills","docs/RESEARCH-14-COMMUNITY-ACCESSIBILITY-IMPACT.md",[
    ["Simple rules","Borrowers should understand terms before accepting an item.","Explain availability, returns and responsibility.|Make pricing and deposits transparent.|Offer accessible communication formats.","Rewrite a complicated borrowing rule in plain language."],
    ["Support fair access","Rules should not unintentionally exclude the people the service aims to help.","Consider transport, hours and cost barriers.|Design workable reminders and extensions.|Handle disputes calmly and consistently.","Plan an alternative pickup arrangement for a borrower without a car."],
    ["Use feedback","Lending data can reveal both demand and frustration.","Record actual loans, waiting lists and losses.|Seek feedback without over-collecting data.|Adjust inventory and rules based on patterns.","Choose one metric you would use to decide whether to buy another kit."]
  ],"What's a good basis for changing loan periods?",["One volunteer's preference","Actual usage, feedback and capacity","Whichever rule sounds strictest"],1,"Fair service design improves through measured experience."),
  course("things-launch","library_of_things","Launching a small lending pilot","Plan a safe, sustainable first collection and evaluate it.",40,"Advanced","docs/PHASE-0-OPERATING-BLUEPRINT.md",[
    ["Define the pilot","Small scope reduces avoidable storage and maintenance burden.","Choose a few item categories.|Confirm hosting, insurance and accountabilities.|Write clear success and stop conditions.","Define a ten-item pilot with a review date."],
    ["Track real costs","Loans are not free to operate even when borrowing is free.","Budget staff/volunteer time, parts and storage.|Track item utilisation and maintenance.|Record losses without hiding them.","Estimate the true monthly cost of a low-use item."],
    ["Decide what next","A pilot is meant to inform a decision, not automatically expand.","Compare usage to initial hypotheses.|Note barriers and unexpected costs.|Retire underused categories and improve popular ones.","Write a short go/change/stop recommendation for a test collection."]
  ],"What is a good reason to expand the item catalogue?",["The idea feels exciting","Consistent demand with manageable maintenance","An empty shelf looks unattractive"],1,"Growth should follow evidence and practical capacity."),
  course("multimeter-low-voltage","dubbo_ewaste","Multimeter basics: safe low-voltage practice","Learn what voltage and continuity can tell you without opening mains equipment.",45,"Building skills","docs/MULTIMETER-REPAIR-TRAINING-VIDEOS.md",[
    ["Know your meter","The dial and sockets must be set correctly for the measurement.","Read the meter's safety ratings and manual.|Use COM for the black lead and the voltage/resistance socket for the red lead.|Identify DC voltage and continuity functions without connecting to anything.","Point to the correct DC voltage setting and explain what it measures."],
    ["Measure documented low-voltage DC","Only work on known, documented low-voltage supplies with appropriate supervision.","Read the adapter label and polarity first.|Avoid shorting barrel plug pins or ID contacts.|Treat a no-load voltage as only one observation, not proof the supply works under load.","Describe a safe measurement plan for a known low-voltage battery, without making contact yet."],
    ["Continuity needs power off","Resistance and continuity checks must not be used on live circuits.","Disconnect all power and remove the battery where appropriate.|Verify a safe de-energised state.|Never open or probe a mains charger or ATX PSU interior.","Explain what you would do if the lead is accidentally left in a current-measurement socket."]
  ],"When is a continuity test appropriate?",["While a device is powered on","Only with power disconnected and the circuit confirmed safe","When testing an open laptop charger"],1,"Continuity and resistance tests on energised circuits risk equipment damage and injury."),
  course("device-identity-locks","dubbo_ewaste","Ownership and device lock decisions","Recognise legitimate identity gates without bypassing owner or enterprise controls.",35,"Advanced","docs/RESEARCH-05-DATA-IDENTITY-PRIVACY-SOP.md",[
    ["Identify a lock","A cloud lock or BIOS password is an authority question, not a repair challenge.","Recognise Activation Lock, Android FRP, Autopilot and managed enrolment.|Record the lock state without disclosing private content.|Ask the owner or administrator to resolve it.","Describe a locked laptop's state clearly in the intake record."],
    ["Ask the right organisation","Only the legitimate device owner or administrator can safely release managed devices.","Confirm legal transfer of ownership.|Request vendor-supported removal by the authorised account holder.|Do not use bypass kits, questionable tools or shared passwords.","Prepare a polite release request for a business IT administrator."],
    ["Quarantine unresolved assets","An unresolved lock changes the device's disposition and value.","Keep it out of resale or public donation listings.|Record exact next owner and deadline.|Escalate for return or approved recycling if unresolved.","Write a next-action note for a device still enrolled in a previous employer's tenant."]
  ],"A laptop remains enrolled in an organisation's device-management service. What is the responsible next step?",["Attempt a bypass tool","Ask its authorised administrator to remove the association","Sell it as a fully working laptop"],1,"Identity/management locks require legitimate owner or administrator action."),
];
export const programmes: {id: Programme; label: string; icon: string}[] = [
  {id:"all",label:"Shared foundations",icon:"🌱"},
  {id:"dubbo_ewaste",label:"DubboEwaste",icon:"💻"},
  {id:"repair_cafe",label:"Repair Café",icon:"🛠️"},
  {id:"library_of_things",label:"Library of Things",icon:"📚"},
];
export function getCourse(id: string) { return courses.find(c => c.id === id); }
export function courseProgress(course: LearningCourse, lessons: {course_slug:string;lesson_slug:string}[]) {
  const complete = course.lessons.filter(l => lessons.some(x => x.course_slug === course.id && x.lesson_slug === l.id)).length;
  return { complete, total: course.lessons.length, percent: Math.round(100*complete/course.lessons.length) };
}
