export type Programme = "all" | "dubbo_ewaste" | "repair_cafe" | "library_of_things";
export type LearningLesson = { id: string; title: string; idea: string; steps: string[]; practice: string };
export type LearningCourse = {
  id: string; programme: Programme; title: string; summary: string;
  duration: number; level: "Getting started" | "Building skills" | "Advanced";
  source: string; sourceLabel: string;
  lessons: LearningLesson[];
  check: { question: string; options: [string, string, string]; answer: number; explanation: string };
};
type LessonInput = [string, string, string, string];
function course(id: string, programme: Programme, title: string, summary: string, duration: number,
  level: LearningCourse["level"], source: string, lessons: [LessonInput,LessonInput,LessonInput],
  question: string, options: [string,string,string], answer: number, explanation: string): LearningCourse {
  return { id, programme, title, summary, duration, level, source,
    sourceLabel: source.split("/").pop()?.replace(/\.md$/, "").replace(/-/g, " ") ?? "Source notes",
    lessons: lessons.map(([title,idea,steps,practice], i) => ({
      id: "lesson-" + (i+1), title, idea, steps: steps.split("|"), practice,
    })),
    check: { question, options, answer, explanation } };
}
export const courses: LearningCourse[] = [
  course("circular-thinking","all","Circular economy essentials","See the difference between reusing, repairing, sharing and recycling.",25,"Getting started","docs/DUBBO-CIRCULAR-ECONOMY-IN-PRACTICE-2026-10-08.md",[
    ["The life of an object","A useful object can have more than one life before it becomes waste.","Think about the resources used to make it.|Ask whether it can be used again as-is.|Consider repair or sharing before recycling.","Choose one object near you. Name two ways it could remain in use."],
    ["The local picture","A national solution is not necessarily available in Dubbo.","Check local availability and acceptance rules.|Separate evidence from assumptions.|Record useful unanswered questions.","Find one Dubbo service and note what it actually accepts."],
    ["Make the better next choice","The most useful action is a decision that fits the item and the person's situation.","Reuse if safe and practical.|Repair when cost and safety make sense.|Recycle through an appropriate pathway when reuse is no longer suitable.","Write the next action for a broken but otherwise useful item."]
  ],"Which choice normally preserves the most value in an item?",["Recycle it immediately","Keep it safely in use","Put it into general waste"],1,"Keeping an item useful commonly avoids more replacement activity."),
  course("volunteer-welcome","all","Welcome and volunteer basics","Learn what to expect, how to ask for help and how to contribute within your role.",20,"Getting started","docs/FAMILY-CAPACITY-ITAD-REPAIR-CAFE.md",[
    ["Know your scope","A volunteer should know which jobs they can do and where to stop.","Check the session lead and your assigned role.|Ask about site rules and escalation.|Never work beyond your own training.","Write down who you would ask about a task that feels unsafe."],
    ["Good handovers","A clear handover protects people, equipment and time.","Record what was received and who owns it.|Explain what you tried and what you observed.|Avoid claiming a repair is complete before a check.","Practise a two-sentence handover to the next volunteer."],
    ["Respect people's time","Warmth and realistic expectations make community services trustworthy.","Introduce yourself and listen first.|Explain limitations without blame.|Make sure the visitor understands the next step.","Describe how you would welcome someone who is nervous about asking for help."]
  ],"What should you do when a task is outside your skills?",["Try anyway to avoid a delay","Stop and ask the appropriate supervisor","Hand it back without explanation"],1,"Competence and clear escalation matter more than appearing capable."),
  course("workshop-safety","all","Workshop safety foundations","Recognise common risks and know when to stop before someone gets hurt.",35,"Getting started","docs/RESEARCH-06-BATTERY-ELECTRICAL-WORKSHOP-SAFETY.md",[
    ["Spot the hazards","A tidy bench is a starting point, not a full risk assessment.","Look for damaged cords, exposed power and trip hazards.|Keep sharp and hot tools controlled.|Check emergency contacts and first-aid arrangements.","Walk around your work area and identify three potential hazards."],
    ["Battery and power boundaries","Lithium batteries and mains electricity require clear authority and competence.","Isolate suspect devices where safe to do so.|Never puncture or crush swollen cells.|Do not attempt unauthorised mains-electrical repairs.","Practise explaining why a swollen battery needs escalation, not experimentation."],
    ["Stop-work decisions","Volunteers must be free to stop a job without pressure.","Pause when something is hot, damaged, leaking or uncertain.|Tell the lead and keep others clear.|Record the hazard and agreed next step.","Describe your stop-work response to a device smelling of burning."]
  ],"A laptop battery is swollen. What is the appropriate first response?",["Puncture it to release pressure","Stop work and follow the isolation/escalation procedure","Continue charging to diagnose it"],1,"Damaged lithium cells can ignite; protect people and escalate."),
  course("privacy-consent","all","Privacy, consent and trust","Handle people's possessions and information respectfully.",30,"Getting started","docs/RESEARCH-05-DATA-IDENTITY-PRIVACY-SOP.md",[
    ["Ask before accessing","Permission to look at a device is not blanket permission to explore personal data.","Explain the intended action.|Avoid personal photos, files and accounts.|Ask before using or sharing images of people or belongings.","Write a simple consent question before inspecting a device."],
    ["Record less","Collect only information necessary for the service.","Use asset IDs instead of unnecessary personal details.|Protect paper forms and digital records.|Avoid copying passwords or access tokens into notes.","Review an intake form and remove one unnecessary question."],
    ["Respond to a mistake","Quickly containing a privacy mistake is better than hiding it.","Stop further disclosure.|Tell your supervisor promptly.|Follow the incident and notification procedure.","Explain the first two actions after sending a record to the wrong person."]
  ],"Which record is most appropriate?",["A full copy of a customer's photo folder","An asset ID and agreed service notes","A saved password for convenience"],1,"Data minimisation reduces exposure and supports trust."),
  course("kind-communication","all","Welcoming, accessible conversations","Make sessions approachable for newcomers, children and people with different needs.",25,"Getting started","docs/RESEARCH-14-COMMUNITY-ACCESSIBILITY-IMPACT.md",[
    ["Listen before explaining","Ask what the person hopes to achieve instead of assuming.","Use a welcoming introduction.|Let the visitor describe the problem.|Check their preferred way of learning.","Practise one open question and one reflective summary."],
    ["Teach with consent","Demonstration is more useful when the visitor can see and participate.","Explain one step at a time.|Ask whether they want to have a go.|Avoid jargon and unexplained acronyms.","Explain an SSD upgrade without technical jargon."],
    ["Close well","Not fixing an item can still be a useful outcome.","Explain what was found and what is uncertain.|Offer realistic referral or next steps.|Ask if anything remains unclear.","Give a respectful handover for an item you cannot repair."]
  ],"What is a good first question?",["Why did you break this?","What were you hoping to use this for?","Do you know what a motherboard is?"],1,"Start with the person's goal, not a technical assumption."),
  course("evidence-observation","all","Good evidence and field notes","Separate observations, assumptions and claims so the next person can check your work.",30,"Building skills","docs/RESEARCH-16-CLOSURE-EVIDENCE-REGISTER.md",[
    ["Facts versus hypotheses","A research note should say what was checked and what remains unknown.","Record the source and date.|Label hypotheses and estimates clearly.|Distinguish local findings from statewide comparisons.","Rewrite an uncertain claim as a testable hypothesis."],
    ["Observe consistently","Repeatable observations are more valuable than impressive anecdotes.","Use the same fields each time.|Capture time, conditions and limitations.|Protect any sensitive names or identifiers.","Design a three-field observation card for a community pilot."],
    ["Close the loop","An unanswered question becomes more useful when it has an owner and a method.","Write the exact question.|Name a practical evidence method.|Record the decision and what would change it.","Choose a gap that needs a local interview rather than web search."]
  ],"A figure comes from a statewide report. Can it be presented as a measured Dubbo result?",["Yes, if plausible","No, its scope must be stated","Yes, if the report is recent"],1,"Evidence must retain the scope and limitations of its source."),
  course("repair-first","all","Repair before replacement","Learn to make an informed repair-or-replace decision.",35,"Building skills","docs/REPAIR-FIRST-DUBBO-IMPLEMENTATION-PLAN.md",[
    ["Check before discarding","A quick diagnosis can prevent an unnecessary replacement.","Clarify the fault and the person's goals.|Estimate safety and repair feasibility.|Identify a local repair or parts option.","Choose one common broken item and list its likely low-cost fixes."],
    ["Cost, time and confidence","A cheap repair is not automatically best, and an expensive repair is not automatically poor.","Consider parts and labour.|Consider reliability, warranty and time.|Be honest about uncertainty.","Compare a repair quote with a realistic replacement."],
    ["Refer appropriately","A useful referral may be better than overpromising.","Look for a qualified local service where needed.|Explain what you have and have not checked.|Ask permission before passing on details.","Prepare a short referral note for a specialist job."]
  ],"Which is a good repair recommendation?",["Always repair regardless of cost","Explain options, safety, cost and uncertainty","Always replace electronics older than three years"],1,"A transparent choice is better than a rigid rule."),
  course("ewaste-intake","dubbo_ewaste","Device receiving and chain of custody","Bring devices into a traceable workflow without losing ownership or condition evidence.",45,"Getting started","docs/INTAKE-AND-DATA-PAPERWORK-PACK.md",[
    ["Before accepting","Confirm authority, permitted categories and safe handling.","Ask about ownership and transfer authority.|Check for prohibited or hazardous items.|Set clear expectations about data and downstream handling.","Draft your intake questions for a laptop donated by a business."],
    ["Identify and label","A unique label connects a physical item to its digital record.","Assign the correct job and lot.|Capture maker, model, serial when authorised and condition.|Attach a durable asset ID before moving it.","Practise a label-to-record check on one device."],
    ["Handover to triage","The next worker needs a truthful snapshot.","Log defects and accessories.|Flag data-bearing media and hazards.|Record time, location and handover state.","Prepare a receiving handover for a laptop with no charger."]
  ],"What should happen before an accepted laptop moves to triage?",["Give it a unique tracked identity","Erase its labels","Advertise it for sale"],0,"Receiving links custody, condition and subsequent actions."),
  course("device-triage","dubbo_ewaste","Device triage and grading","Decide whether a device should be reused, repaired, harvested or recycled.",50,"Building skills","agyDOCS/Triage-Skills-Guide.md",[
    ["Start with a visual check","Look for signs that make testing unsafe or uneconomic.","Check casing, hinges, ports and display.|Identify liquid damage and swelling.|Keep unknown battery risks isolated.","Inspect a laptop and write three observations without diagnosing yet."],
    ["Run repeatable checks","A consistent sequence prevents missed faults.","Test with safe power methods.|Record screen, keyboard, storage and core function results.|Do not treat an untested feature as passed.","Build a repeatable seven-step check sequence."],
    ["Choose a disposition","A route should be explainable and revisitable.","Compare likely repair effort and value.|Account for data-bearing media.|Record the decision and supporting test results.","Route three sample laptops: usable, fixable, and unsafe."]
  ],"An untested keyboard should be recorded as…",["Passed","Not tested","Failed irreparably"],1,"Unknown is different from passed or failed."),
  course("storage-erasure","dubbo_ewaste","Data sanitisation and verification","Understand sanitisation decisions and why evidence matters.",55,"Advanced","docs/ASSETFLOW-ERASURE-DIAGNOSTICS-INTEGRATIONS.md",[
    ["Identify every medium","A laptop can contain removable storage and hidden additional media.","Check reported drives against the physical device.|Record interface and relevant restrictions.|Keep data-bearing assets controlled before reuse.","Draft a storage inventory for a laptop plus a USB drive."],
    ["Choose the right method","Clear and Purge choices depend on medium, capability and risk.","Follow the approved NIST-aligned policy.|Check HPA, DCO, OPAL and freeze state where applicable.|Escalate unsupported or locked media.","Explain why a generic overwrite is not always sufficient for an SSD."],
    ["Verify the result","A claimed wipe is not equivalent to verified sanitisation.","Record method, tool, operator and result.|Verify according to procedure.|Quarantine failures and link evidence to the asset.","Review an example certificate and name three missing fields."]
  ],"A sanitisation task reports failure. What next?",["Issue a pass certificate anyway","Quarantine and investigate under the approved policy","Sell the drive without further checks"],1,"Failures need escalation and traceable resolution."),
  course("diagnostic-bench","dubbo_ewaste","Laptop diagnostics fundamentals","Use observation and controlled tests to narrow a fault.",50,"Building skills","docs/PRACTICAL-TRAINING-SHEETS.md",[
    ["Describe the symptom","Start from what actually happens, not your first theory.","Record power, display and boot behaviour.|Try a safe and repeatable setup.|Separate intermittent from repeatable faults.","Write a fault description for a laptop that runs but its screen goes dark."],
    ["Test one variable","Changing one thing at a time makes results meaningful.","Check power delivery safely.|Use known-good parts where appropriate.|Document changed conditions and outcomes.","Plan a display test that distinguishes panel from external-output behaviour."],
    ["Record the diagnosis","Confidence belongs beside any conclusion.","Write observed results and what remains untested.|Make next steps proportionate to value and safety.|Escalate electrical or board faults outside competence.","Complete a simple diagnostic log for an unresolved fault."]
  ],"A laptop screen goes dark but the laptop stays powered. Should you conclude it fully shuts down?",["Yes","No, test display and power behaviour separately","Yes, if it is old"],1,"The symptom does not establish a complete power loss."),
  course("battery-safety","dubbo_ewaste","Lithium battery handling","Recognise unsafe packs and protect volunteers and downstream handlers.",40,"Getting started","docs/RESEARCH-06-BATTERY-ELECTRICAL-WORKSHOP-SAFETY.md",[
    ["Red flags","Swelling, heat, damage and leakage demand a different handling route.","Visually assess before charging.|Do not deform or probe compromised cells.|Know the isolation location and emergency plan.","List four signs that a battery needs escalation."],
    ["Controlled handling","Prevention includes storage, transport and separation.","Keep terminals and conductive materials controlled.|Use approved containment and procedures.|Never send damaged batteries into mixed scrap.","Inspect a mock battery-handling station for risks."],
    ["Downstream responsibility","A battery remains a risk after it leaves your bench.","Record condition and route.|Use suitable accepted downstream providers.|Retain evidence of correct transfer.","Write a short handover description for a damaged pack."]
  ],"Should a visibly swollen battery go into the normal testing queue?",["Yes, if powered off","No, follow the hazard procedure","Yes, after a brief charge"],1,"Suspect lithium batteries need separate safe handling."),
  course("refurb-upgrades","dubbo_ewaste","Refurbishment and parts strategy","Decide which repairs improve usability without consuming the whole workshop.",45,"Building skills","docs/RESEARCH-07-REPAIR-ECONOMICS-PARTS-STRATEGY.md",[
    ["Decide if worthwhile","Not every repair has positive value or useful impact.","Check likely sale/use outcome.|Account for labour, parts and uncertainty.|Avoid long-running projects without a purpose.","Estimate a simple SSD upgrade's total cost including labour."],
    ["Parts compatibility","Right parts, correct documentation and controlled sourcing matter.","Check model and connector before ordering.|Record donor-parts provenance.|Inspect and test replacements.","Prepare a compatibility checklist for a laptop RAM upgrade."],
    ["Finish the job","A repaired device must be retested.","Re-run diagnostics after repair.|Confirm storage sanitisation and software permissions.|Record parts used, failures and final grade.","Write a final test checklist for a refurbished notebook."]
  ],"A replacement part is installed. Is the job finished immediately?",["Yes","Only after appropriate re-testing and recording","If the laptop powers on once"],1,"Repairs must be verified before disposition."),
  course("reuse-resale","dubbo_ewaste","Resale, warranties and honest listings","Prepare devices for responsible resale or donation.",45,"Building skills","docs/LISTING-WARRANTY-CHECKLIST.md",[
    ["Describe the actual device","Trust depends on accurate specs, tests and flaws.","Record exact model and configuration.|List known defects and untested functions.|Keep private identifiers out of public adverts.","Draft a concise listing for a laptop with a cosmetic defect."],
    ["Price responsibly","Margin is not only the difference between sale price and parts.","Add labour, freight, fees and returns allowance.|Check comparable sold prices, not just asks.|Avoid unsupported impact or quality claims.","Calculate a hypothetical true resale margin."],
    ["Support a buyer","Consumer obligations and reasonable after-sale support matter.","Give accurate included items and limitations.|Use applicable Australian consumer law guidance.|Keep a traceable sale and return record.","Write a short, clear handover note for a refurbished device."]
  ],"How should an untested webcam be described in a listing?",["Works perfectly","Not tested","Brand new"],1,"Listings should distinguish tested functions from assumptions."),
  course("downstream-recycling","dubbo_ewaste","Recycling and downstream proof","Track what cannot be reused and verify where it goes.",40,"Building skills","docs/RESEARCH-11-DOWNSTREAM-ENVIRONMENTAL-CHAIN-OF-CUSTODY.md",[
    ["Sort correctly","Different materials and hazards demand different pathways.","Separate batteries and controlled waste.|Preserve data controls for all data-bearing media.|Check acceptance rules before dispatch.","Sort sample items into reuse, controlled processing and general waste."],
    ["Verify the provider","A waste handover is not proof of final recycling.","Record approved provider and acceptance evidence.|Check scope and any required credentials.|Keep transport and receiving documentation.","List the evidence you would request from a processor."],
    ["Report carefully","Impact figures require a defensible method.","Measure weights or counts consistently.|Avoid treating estimated diversion as exact.|Report uncertainty and methodology.","Write a cautious impact statement for ten processed laptops."]
  ],"Which is strongest evidence of responsible downstream processing?",["A casual verbal promise","Traceable transfer and verified processing records","An attractive recycling logo"],1,"Chain-of-custody and verifiable records are essential."),
  course("assetflow-basics","dubbo_ewaste","AssetFlow: your first shift","Navigate intake, assets, jobs and evidence without corrupting the record.",35,"Getting started","docs/ASSETFLOW-PLATFORM-BACKLOG.md",[
    ["Find your workspace","Only use features permitted to your role.","Start at your dashboard.|Find jobs, lots and assets.|Use the linked record rather than disconnected notes.","Locate a practice asset in the Search / Scan workflow."],
    ["Make a traceable update","The asset timeline should explain each change.","Check the asset ID before editing.|Record observations instead of speculation.|Avoid duplicate submissions.","Describe how you would prevent creating the same asset twice."],
    ["Close or escalate","Incomplete tasks should have a visible next owner.","Confirm the workflow state.|Link supporting tests or evidence.|Escalate exceptions rather than hiding them.","Create a handover checklist for the next shift."]
  ],"What should you check before updating a record?",["The exact asset identity","How many people are watching","Whether the form looks familiar"],0,"Record accuracy starts with the right asset."),
  course("repair-cafe-intro","repair_cafe","Repair Café: first session","Understand the proposed pop-up model and the volunteer's role.",30,"Getting started","docs/REPAIR-FIRST-DUBBO-PILOT.md",[
    ["How the café works","This is a community learning and shared-repair model, not a drop-off shop.","Welcome the owner and their item.|Explain that safe repair cannot be guaranteed.|Invite the owner to participate.","Practise explaining the concept in two sentences."],
    ["Your volunteer role","Hospitality and organisation matter as much as technical fixing.","Choose welcome, intake, fixer, learner or setup roles.|Know who makes safety decisions.|Accept only work within competence.","Pick two ways you could help without any repair expertise."],
    ["A good outcome","Diagnosed, referred and learned can be successes, even without a fix.","Capture a clear outcome.|Explain any referral and next steps.|Thank the owner for sharing the experience.","Write a positive handover for a non-repairable item."]
  ],"Does every item have to be repaired for the session to be worthwhile?",["Yes","No, learning and diagnosis can be useful","Only if the owner pays"],1,"The event is about learning, connection and practical next steps."),
  course("repair-cafe-intake","repair_cafe","Repair Café intake and triage","Welcome an item, identify hazards and match it to a safe station.",40,"Building skills","docs/RESEARCH-01-FRONT-DOOR-TRIAGE.md",[
    ["Ask the right questions","A short intake conversation sets safe expectations.","Ask what is broken and what changed.|Clarify ownership and consent.|Check electrical, battery and sharp-edge risks.","Role-play a two-minute intake for a broken lamp."],
    ["Route to the right person","Competence and workspace determine what can be attempted.","Match the job to a suitable volunteer.|Decline or refer high-risk items.|Keep any queue realistic and visible.","Decide whether a damaged mains-powered appliance is appropriate to accept."],
    ["Document the outcome","The owner should leave with a clear understanding.","Record attempted actions and limits.|Note whether fixed, diagnosed or referred.|Record safety concerns confidentially.","Complete a sample outcomes slip for an unsuccessful repair."]
  ],"What matters most when assigning a repair?",["How quickly someone volunteers","Matching risk, skills and permissions","How old the item is"],1,"Safe scope and competence take priority over enthusiasm."),
  course("repair-cafe-toolkit","repair_cafe","Hand tools and simple repairs","Use common tools carefully and learn to test a basic diagnosis.",45,"Building skills","docs/PRACTICAL-TRAINING-SHEETS.md",[
    ["Choose the correct tool","Using the wrong tool can damage the item or hurt someone.","Identify fastener type before turning.|Keep sharps controlled and parts organised.|Never force a seized or powered component.","Prepare a safe work area for opening a battery-free mechanical item."],
    ["Check before changing","Diagnose the fault without replacing parts at random.","Observe the symptom.|Test an accessible, safe cause.|Record what changed and what did not.","Describe a method for investigating a loose chair fitting."],
    ["Explain your limits","Confidence grows when volunteers report uncertainty plainly.","Check fit and function after a repair.|Keep safety-critical work for competent specialists.|Explain what wasn't tested.","Tell a visitor why a repair must stop even though you have tools available."]
  ],"Can a volunteer repair mains wiring just because they own a multimeter?",["Yes","No, authorisation and competence are required","Only on older devices"],1,"Owning tools is not evidence of suitable qualifications or safety procedures."),
  course("repair-cafe-running","repair_cafe","Running a welcoming event","Plan the venue, volunteer flow, check-in and a manageable first pilot.",40,"Building skills","docs/DUBBO-REPAIR-CAFE-VENUE-RESEARCH-2026-10-08.md",[
    ["Prepare the venue","Room layout must work for safety and for people.","Check venue permission and insurance.|Plan accessible welcome, queue and tool zones.|Identify evacuation, power and first-aid needs.","Sketch a small event with distinct welcome and repair areas."],
    ["Manage the session","A small pilot gives better learning than an uncontrolled queue.","Cap item intake to available skills.|Assign roles and breaks.|Explain wait times and what cannot be accepted.","Plan a three-hour pop-up event schedule."],
    ["Measure and improve","Learn from outcomes without collecting unnecessary personal information.","Count items by outcome.|Ask what visitors found useful.|Record safety incidents and improvements.","Write three questions for a volunteer debrief."]
  ],"What is the safest first-event plan?",["Unlimited walk-ins and all electrical repairs","A capped pilot matched to venue and volunteers","No intake records"],1,"Start within capacity and expand based on evidence."),
  course("repair-cafe-accessibility","repair_cafe","Inclusive teaching and community connection","Make repair activities welcoming for different ages, backgrounds and abilities.",30,"Getting started","docs/RESEARCH-14-COMMUNITY-ACCESSIBILITY-IMPACT.md",[
    ["Make participation possible","Visitors should not need technical vocabulary to belong.","Ask about comfort and access needs without assumptions.|Offer seating and visibility.|Explain how to opt out of tasks.","Choose one way to help a visitor who cannot stand for long."],
    ["Teach side by side","Learning together is often more important than finishing fast.","Demonstrate clearly and offer turns.|Adjust the pace to the visitor.|Invite questions without embarrassment.","Demonstrate how to tighten an accessible fastener verbally."],
    ["Keep a respectful atmosphere","No one should be pressured into repairs, photographs or public sharing.","Ask before photos.|Avoid blame about buying or breaking things.|Thank people for participation.","Rephrase a judgemental comment into a welcoming response."]
  ],"Should you photograph a visitor's repair for publicity without asking?",["Yes, it's a public event","No, get appropriate consent","Only if the repair succeeds"],1,"Consent and dignity are not optional."),
  course("things-foundations","library_of_things","Library of Things: getting started","Understand sharing services, ownership and why a small lending pilot works best.",30,"Getting started","docs/DUBBO-CIRCULAR-ECONOMY-IN-PRACTICE-2026-10-08.md",[
    ["Why borrow?","Some useful items are rarely used and costly to own.","Consider infrequent-use equipment.|Check whether borrowing is practical for the user.|Avoid buying inventory before demand is known.","Name three things people might borrow instead of buy."],
    ["Start with real demand","A service should be built around actual needs.","Ask what exact objects people want.|Estimate frequency, access and storage needs.|Keep the pilot inventory small and traceable.","Write three survey questions for a lending pilot."],
    ["Steward responsibilities","A friendly loan is still a responsibility.","Confirm member identity under approved rules.|Explain safe use and loan terms.|Track where the item is and when it returns.","Describe a good handover of a borrowed hand-tool kit."]
  ],"How should a new Library of Things decide what to stock first?",["Buy many popular-sounding items","Validate local demand and start small","Accept everything immediately"],1,"Measured demand and capacity should guide the collection."),
  course("things-catalogue","library_of_things","Cataloguing and kit completeness","Make shared items easy to find, check out and return.",40,"Building skills","docs/RESEARCH-09-INVENTORY-SYSTEM-OF-RECORD.md",[
    ["Describe every item","A useful catalogue entry connects a name to an actual object.","Assign a unique item ID.|Record condition, accessories and safe-use instructions.|Use clear photos when appropriate.","Describe a projector kit with its cables and remote."],
    ["Check out carefully","Borrowing should have visible accountability.","Match the user, item and approved loan period.|Explain inclusions and conditions.|Log handover time and item condition.","Draft a friendly handover checklist for camping gear."],
    ["Check return completeness","A return is not finished until the kit is ready for its next borrower.","Count components against the checklist.|Record faults or missing pieces.|Move items needing attention out of circulation.","Practise checking a hypothetical ten-piece tool kit."]
  ],"What should happen when a returned kit is missing a part?",["Mark it complete anyway","Record the missing part and hold or update availability","Discard the entire item"],1,"Accurate completeness records protect future borrowers."),
  course("things-maintenance","library_of_things","Maintenance, inspections and quarantine","Keep borrowed equipment ready for safe, repeated use.",45,"Building skills","docs/RESEARCH-06-BATTERY-ELECTRICAL-WORKSHOP-SAFETY.md",[
    ["Pre-loan checks","Inspection should match the risk and type of item.","Compare against a standard condition checklist.|Look for damage, missing instructions and recalls.|Do not lend unsafe or unverified equipment.","Draft a visual inspection card for a basic hand-tool kit."],
    ["Returns and cleaning","Every return is an opportunity to improve reliability.","Check cleanliness and completeness.|Record damage without blaming borrowers prematurely.|Dry and store items appropriately.","Plan a return workflow for a camping tent."],
    ["Quarantine and escalation","An uncertain item is not an available item.","Tag and isolate damaged items.|Set an owner for a qualified assessment.|Document the decision before re-lending.","Write a quarantine note for a tool with a cracked handle."]
  ],"A borrowed tool comes back with a cracked handle. What should happen?",["Put it straight back on the shelf","Remove it from circulation pending assessment","Lend it with a verbal warning only"],1,"Damaged shared equipment needs a controlled inspection."),
  course("things-service","library_of_things","Fair lending and community service","Set clear, equitable rules for reservations, fees and late returns.",35,"Building skills","docs/RESEARCH-14-COMMUNITY-ACCESSIBILITY-IMPACT.md",[
    ["Simple rules","Borrowers should understand terms before accepting an item.","Explain availability, returns and responsibility.|Make pricing and deposits transparent.|Offer accessible communication formats.","Rewrite a complicated borrowing rule in plain language."],
    ["Support fair access","Rules should not unintentionally exclude the people the service aims to help.","Consider transport, hours and cost barriers.|Design workable reminders and extensions.|Handle disputes calmly and consistently.","Plan an alternative pickup arrangement for a borrower without a car."],
    ["Use feedback","Lending data can reveal both demand and frustration.","Record actual loans, waiting lists and losses.|Seek feedback without over-collecting data.|Adjust inventory and rules based on patterns.","Choose one metric you would use to decide whether to buy another kit."]
  ],"What's a good basis for changing loan periods?",["One volunteer's preference","Actual usage, feedback and capacity","Whichever rule sounds strictest"],1,"Fair service design improves through measured experience."),
  course("things-launch","library_of_things","Launching a small lending pilot","Plan a safe, sustainable first collection and evaluate it.",40,"Advanced","docs/PHASE-0-OPERATING-BLUEPRINT.md",[
    ["Define the pilot","Small scope reduces avoidable storage and maintenance burden.","Choose a few item categories.|Confirm hosting, insurance and accountabilities.|Write clear success and stop conditions.","Define a ten-item pilot with a review date."],
    ["Track real costs","Loans are not free to operate even when borrowing is free.","Budget staff/volunteer time, parts and storage.|Track item utilisation and maintenance.|Record losses without hiding them.","Estimate the true monthly cost of a low-use item."],
    ["Decide what next","A pilot is meant to inform a decision, not automatically expand.","Compare usage to initial hypotheses.|Note barriers and unexpected costs.|Retire underused categories and improve popular ones.","Write a short go/change/stop recommendation for a test collection."]
  ],"What is a good reason to expand the item catalogue?",["The idea feels exciting","Consistent demand with manageable maintenance","An empty shelf looks unattractive"],1,"Growth should follow evidence and practical capacity.")
];
export const programmes: {id: Programme; label: string; icon: string}[] = [
  {id:"all",label:"Shared foundations",icon:"🌱"},
  {id:"dubbo_ewaste",label:"DubboEwaste",icon:"💻"},
  {id:"repair_cafe",label:"Repair Café",icon:"🛠️"},
  {id:"library_of_things",label:"Library of Things",icon:"📚"},
];
export function getCourse(id: string) { return courses.find(c => c.id === id); }
export function courseProgress(course: LearningCourse, lessons: {course_slug:string;lesson_slug:string}[]) {
  const complete = course.lessons.filter(l => lessons.some(x => x.course_slug === course.id && x.lesson_slug === l.id)).length;
  return { complete, total: course.lessons.length, percent: Math.round(100*complete/course.lessons.length) };
}
