import { getCourse, type Programme } from "@/lib/learning/catalog";

export type MediaItem = {
 id: string; course: string; type: "video"|"podcast"|"guide";
 title: string; provider: string; url: string;
 summary: string; focus: string; provenance: "primary"|"practitioner"|"vendor"|"community";
 accessibility: string;
};
export const mediaItems: MediaItem[] = [
 {id:"repair-safety-video",course:"repair-electrical-safety",type:"video",title:"Know the limits of what you are measuring",provider:"Afrotechmods",url:"https://www.youtube.com/watch?v=bF3OyQ3HwfU",summary:"Learn how meter mistakes happen and where novice low-voltage practice should stop.",focus:"Which demonstrations would be inappropriate on a live mains appliance?",provenance:"practitioner",accessibility:"Verified English YouTube instructional video; equipment recommendations are dated. Low-voltage observation only."},
 {id:"repair-battery-ipad",course:"repair-lithium-batteries",type:"video",title:"iPad battery replacement: hazard observation",provider:"iFixit",url:"https://www.youtube.com/watch?v=nPgJ-8DTDhA",summary:"See why adhesive, fragile cells and display cables create repair risks.",focus:"What warning signs mean you must not proceed with battery opening?",provenance:"practitioner",accessibility:"Verified English YouTube demonstration. Older iPad model; watch only until appropriately trained and supervised."},
 {id:"repair-ohm-afrotechmods",course:"repair-circuit-fundamentals",type:"video",title:"Resistance, Ohm's law and an LED circuit",provider:"Afrotechmods",url:"https://www.youtube.com/watch?v=NfcgA1axPLo",summary:"A worked low-voltage resistor-and-LED example.",focus:"Calculate LED resistor current; what voltage drop did you assume?",provenance:"practitioner",accessibility:"Verified English beginner instruction; includes a practical current-limiting LED circuit."},
 {id:"repair-meter-afrotechmods",course:"repair-multimeter-diagnostics",type:"video",title:"How to use a digital multimeter",provider:"Afrotechmods",url:"https://www.youtube.com/watch?v=bF3OyQ3HwfU",summary:"Learn lead placement, voltage, current, resistance and continuity.",focus:"Why must a current-input jack never be used like a voltage jack?",provenance:"practitioner",accessibility:"Verified English video. Meter buying examples are old; follow your own meter's current manual."},
 {id:"repair-troubleshoot-messer",course:"repair-fault-finding",type:"video",title:"Hardware troubleshooting: systematic symptoms",provider:"Professor Messer",url:"https://www.youtube.com/watch?v=HgeURynWn_w",summary:"A+ hardware fault examples including power, POST, heat and blank screens.",focus:"What single observation best separates the two most likely faults?",provenance:"practitioner",accessibility:"Verified English instructional video from the 220-1201 A+ series."},
 {id:"repair-ipad-disassembly",course:"repair-esd-disassembly",type:"video",title:"iPad opening and flex-cable risk demonstration",provider:"iFixit",url:"https://www.youtube.com/watch?v=nPgJ-8DTDhA",summary:"Watch fragile disassembly and identify battery/displays/connector hazards.",focus:"Where would you stop before manipulating an unverified latch?",provenance:"practitioner",accessibility:"Verified English model-specific demonstration. Not a beginner DIY battery replacement endorsement."},
 {id:"repair-usbc-channel",course:"repair-usbc-power",type:"video",title:"Repair troubleshooting cases: connectors, charging and power",provider:"TronicsFix",url:"https://www.youtube.com/watch?v=2WHa4EcDtUI",summary:"Observe diagnosis across unusual broken electronics; this is a repair case-study, not a USB-C PD class.",focus:"Which checks would be safe for a beginner versus advanced board work?",provenance:"practitioner",accessibility:"Verified English YouTube repair case video; not specific USB-C PD training. Refer to technical specifications for PD."},
 {id:"repair-board-rossmann",course:"repair-schematics-pcbs",type:"guide",title:"Louis Rossmann board-repair training slides and channel",provider:"Louis Rossmann / Rossmann Repair",url:"https://docs.google.com/presentation/d/1PkeO_lC5WTPScSV3ZzEEjVuDWeQtL2eHK6jEcf7axA0/htmlpresent",summary:"Structured advanced reference for reading circuits and explaining real board-level reasoning.",focus:"What is a power rail, and how do you avoid an unjustified IC replacement?",provenance:"practitioner",accessibility:"Trainer's publicly shared slides link to his official YouTube channel. Advanced case material; no unsafe hands-on assignment."},
 {id:"repair-solder-beginner-video",course:"repair-through-hole-soldering",type:"video",title:"Beginners guide to soldering",provider:"Mr SolderFix",url:"https://www.youtube.com/watch?v=dETS6YHrNRI",summary:"Detailed iron, flux, tinning and through-hole practice demonstration.",focus:"Describe pad and lead wetting and how you would inspect a joint.",provenance:"practitioner",accessibility:"Verified English YouTube soldering tutorial; practise only on unpowered scrap boards."},
 {id:"repair-solder-remove-video",course:"repair-desolder-replace",type:"video",title:"How to solder and desolder SMD crystals",provider:"Mr SolderFix",url:"https://www.youtube.com/watch?v=QsWQrP69ZuI",summary:"Compare component removal approaches and collateral heat risks.",focus:"Which part of this video is beyond beginner through-hole work?",provenance:"practitioner",accessibility:"Verified English specialist video. SMD rework is more advanced than this course's beginner practice."},
 {id:"repair-smd-solderfix",course:"repair-smd-microsoldering",type:"video",title:"Control solder flow on difficult PCB joints",provider:"Mr SolderFix",url:"https://www.youtube.com/watch?v=Sj5fZgsL8J0",summary:"A close-up method for controlled solder placement and avoiding unintended bridges.",focus:"How would you inspect pads and adjacent circuitry before declaring success?",provenance:"practitioner",accessibility:"Verified English soldering video; do not generalise heat settings to unfamiliar boards."},
 {id:"repair-laptop-messer",course:"repair-laptop-refurb",type:"video",title:"Laptop and computer hardware troubleshooting",provider:"Professor Messer",url:"https://www.youtube.com/watch?v=HgeURynWn_w",summary:"A structured troubleshooting approach to boot, overheating, drive and screen symptoms.",focus:"Create a test sequence before attempting a RAM or display replacement.",provenance:"practitioner",accessibility:"Verified English CompTIA A+ instructional video."},
 {id:"repair-pat-nsw-guide",course:"repair-pat-verification",type:"guide",title:"SafeWork NSW official guidance portal",provider:"SafeWork NSW",url:"https://www.safework.nsw.gov.au/",summary:"Start with local WHS rules on electrical equipment inspection, testing and competent people.",focus:"Why is an online theory course not sufficient to authorise mains work?",provenance:"primary",accessibility:"Official written reference. Search SafeWork NSW for the current applicable inspection/testing guidance."},
 {id:"repair-itad-blancco",course:"repair-itad-sanitisation",type:"video",title:"Blancco commercial data-erasure overview",provider:"Blancco Technology Group",url:"https://www.youtube.com/watch?v=mdgd4VIbLgk",summary:"A vendor explanation of ITAD data erasure, auditing and certificates; treat all claims as vendor assertions.",focus:"Which parts of an erasure certificate require independent evidence?",provenance:"vendor",accessibility:"Verified English company video; not independent assurance that a given method meets NIST SP 800-88 Rev.2."},
 {id:"repair-triage-tronicsfix",course:"repair-triage-economics",type:"video",title:"Can this unusual broken technology be repaired?",provider:"TronicsFix",url:"https://www.youtube.com/watch?v=2WHa4EcDtUI",summary:"Observe repair/replace decisions, repairability and testing considerations.",focus:"Estimate tools, labour and parts costs that the edit may not reveal.",provenance:"practitioner",accessibility:"Verified English repair case study. Edited entertainment is not a complete bench procedure."},
 {id:"repair-breadboard-guide",course:"repair-circuit-fundamentals",type:"guide",title:"DC circuits textbook with practice exercises",provider:"All About Circuits",url:"https://www.allaboutcircuits.com/textbook/direct-current/",summary:"A substantial readable reference with circuit arithmetic and common errors.",focus:"Explain each resistor voltage drop in your circuit.",provenance:"practitioner",accessibility:"Text tutorial provides an alternative to video."},
 {id:"repair-itad-standard",course:"repair-itad-sanitisation",type:"guide",title:"NIST SP 800-88 Revision 2 source",provider:"NIST",url:"https://csrc.nist.gov/pubs/sp/800/88/r2/final",summary:"Official storage sanitisation standard for sanitisation programmes and evidence.",focus:"When is a claimed successful SSD overwrite insufficient?",provenance:"primary",accessibility:"Primary written standard, not a YouTube video."},
 {id:"repair-data-cyber",course:"repair-laptop-refurb",type:"guide",title:"Dispose of your device securely",provider:"Australian Cyber Security Centre",url:"https://www.cyber.gov.au/protect-yourself/securing-your-devices/how-secure-your-device/how-dispose-your-device-securely",summary:"Personal-data and device-retirement safety advice.",focus:"What is different between a consumer reset and audited ITAD?",provenance:"primary",accessibility:"Australian Government written consumer guidance."},
 {id:"repair-solderwire",course:"repair-through-hole-soldering",type:"video",title:"Soldering PCB wiring and technique",provider:"Mr SolderFix",url:"https://www.youtube.com/watch?v=Npl10nkywsM",summary:"More wiring and pad-wetting demonstrations, including very fine technique.",focus:"Which techniques are appropriate for a beginner's larger scrap through-hole pads?",provenance:"practitioner",accessibility:"Verified English video; fine-pitch work is observation only."},
 {id:"multimeter-intro",course:"multimeter-low-voltage",type:"video",title:"How to use a multimeter",provider:"Defpom's Electronics Repair",url:"https://www.youtube.com/watch?v=jUAXPTBRxmw",summary:"Basics of choosing a measurement and reading the display.",focus:"Identify COM, V/Ω and DC voltage before touching a circuit.",provenance:"practitioner",accessibility:"English-course listing identified in curated research; caption availability not independently verified."},
 {id:"meter-fundamentals",course:"multimeter-low-voltage",type:"video",title:"Multimeter fundamentals",provider:"LED Projects",url:"https://www.youtube.com/watch?v=OD-VMmPyCo4",summary:"A beginner demonstration of voltage, resistance and continuity.",focus:"What must be disconnected before measuring resistance?",provenance:"practitioner",accessibility:"English on-screen captions observed in the original research; audio/captions require checking at the source."},
 {id:"laptop-power-diagnosis",course:"diagnostic-bench",type:"video",title:"Diagnosing a laptop power fault",provider:"Electronics Repair Basics",url:"https://www.youtube.com/watch?v=BTSzGiOY8Mo",summary:"See the difference between symptoms, adapter checks and hypotheses.",focus:"Note which tests are safe for a beginner and which require a qualified technician.",provenance:"practitioner",accessibility:"English transcript excerpt was documented; not a safety endorsement of every demonstrated step."},
 {id:"lenovo-power-case",course:"diagnostic-bench",type:"video",title:"Lenovo not charging: observed troubleshooting",provider:"Electronics Repair School",url:"https://www.youtube.com/watch?v=j73U2ZnvrBM",summary:"A practical case study for observational learning only.",focus:"Identify the symptom and the test that changed the hypothesis.",provenance:"practitioner",accessibility:"Third-party listing identified English; do not copy live-board work without competence."},
 {id:"laptop-ssd-erasure",course:"storage-erasure",type:"video",title:"Why SSD sanitisation differs",provider:"Blancco",url:"https://www.youtube.com/watch?v=9RdeQPw_G48",summary:"Vendor explanation of SSD sanitisation concepts and tool options.",focus:"Find one assertion that needs independent validation against NIST.",provenance:"vendor",accessibility:"Direct video link; captions and current playback not independently confirmed."},
 {id:"drive-eraser-overview",course:"storage-erasure",type:"video",title:"Enterprise erasure workflow overview",provider:"Blancco",url:"https://www.youtube.com/watch?v=qNt84_b3UXw",summary:"A tool walkthrough; treat vendor certification statements as claims.",focus:"List evidence fields that a certificate should actually contain.",provenance:"vendor",accessibility:"Direct video link; caption availability unverified."},
 {id:"responsible-ewaste",course:"downstream-recycling",type:"video",title:"Recycling e-waste responsibly",provider:"Panasonic and TechCollect",url:"https://www.youtube.com/watch?v=V-3EhSnzFfI",summary:"Product stewardship introduction; older material for scheme context.",focus:"Differentiate collection from independently documented final processing.",provenance:"primary",accessibility:"Direct YouTube link; current availability and captioning not verified."},
 {id:"australian-itad",course:"ewaste-intake",type:"podcast",title:"E-waste revolution with Austin Turpin",provider:"Life on Planet A",url:"https://podcasts.apple.com/au/podcast/82-e-waste-revolution-with-austin-turpin/id1508865350?i=1000705662337",summary:"Australian operator perspective on focused electronics reuse and processing.",focus:"Name two claims that need testing in Dubbo rather than assuming they transfer.",provenance:"practitioner",accessibility:"External Apple Podcasts page; transcript availability varies."},
 {id:"device-circularity",course:"circular-thinking",type:"podcast",title:"Refurbished technology and circular growth",provider:"All Things Circular · Foxway",url:"https://podcasts.apple.com/at/podcast/ep-59-refurbished-technology-itad-circular-growth-ai/id1790559566?i=1000770978719",summary:"Device lifecycles from collection through reuse and resale.",focus:"Which stage preserves useful value, and where is data protection essential?",provenance:"practitioner",accessibility:"External podcast page; check player and transcripts with your device."},
 {id:"the-last-mile",course:"device-triage",type:"podcast",title:"The last mile: disposal and data destruction",provider:"Operational ITAM",url:"https://podcasts.apple.com/us/podcast/the-last-mile-disposal-data-destruction-and/id6794776975?i=1000779297944",summary:"Disposal and data-audit considerations from an industry perspective.",focus:"Explain why a functional device may still be unreleasable.",provenance:"practitioner",accessibility:"External Apple Podcasts page; transcript not confirmed."},
 {id:"ifixit-multimeter",course:"multimeter-low-voltage",type:"guide",title:"Illustrated guide to using a multimeter",provider:"iFixit",url:"https://www.ifixit.com/Guide/How+To+Use+A+Multimeter/25632",summary:"Readable guide to the basic controls and measurement types.",focus:"Explain why continuity testing requires an unpowered circuit.",provenance:"community",accessibility:"Text and imagery provide an alternative to video."},
 {id:"secure-disposal-acsc",course:"privacy-consent",type:"guide",title:"Dispose of your device securely",provider:"Australian Cyber Security Centre",url:"https://www.cyber.gov.au/protect-yourself/securing-your-devices/how-secure-your-device/how-dispose-your-device-securely",summary:"Official consumer advice about accounts, removable media and disposal.",focus:"What is different between a consumer reset and an audited commercial sanitisation?",provenance:"primary",accessibility:"Text-based government resource."}
];
export function mediaForCourse(course:string){return mediaItems.filter(i=>i.course===course && Boolean(getCourse(i.course)));}
export function mediaProgramme(item:MediaItem):Programme{return getCourse(item.course)?.programme??"all";}
export function safeExternalMediaUrl(url:string){try{const parsed=new URL(url);return parsed.protocol==="https:"&&["youtube.com","www.youtube.com","podcasts.apple.com","www.ifixit.com","www.cyber.gov.au","csrc.nist.gov","www.safework.nsw.gov.au","www.allaboutcircuits.com","docs.google.com"].includes(parsed.hostname);}catch{return false;}}
