import { getCourse, type Programme } from "@/lib/learning/catalog";

export type MediaItem = {
 id: string; course: string; type: "video"|"podcast"|"guide";
 title: string; provider: string; url: string;
 summary: string; focus: string; provenance: "primary"|"practitioner"|"vendor"|"community";
 accessibility: string;
};
export const mediaItems: MediaItem[] = [
 {id:"multimeter-intro",course:"multimeter-low-voltage",type:"video",title:"How to use a multimeter",provider:"Defpom's Electronics Repair",url:"https://www.youtube.com/watch?v=jUAXPTBRxmw",summary:"Basics of choosing a measurement and reading the display.",focus:"Identify COM, V/Ω and DC voltage before touching a circuit.",provenance:"practitioner",accessibility:"English-course listing identified in curated research; caption availability not independently verified."},
 {id:"meter-fundamentals",course:"multimeter-low-voltage",type:"video",title:"Multimeter fundamentals",provider:"LED Projects",url:"https://www.youtube.com/watch?v=OD-VMmPyCo4",summary:"A beginner demonstration of voltage, resistance and continuity.",focus:"What must be disconnected before measuring resistance?",provenance:"practitioner",accessibility:"English on-screen captions observed in the original research; audio/captions require checking at the source."},
 {id:"laptop-power-diagnosis",course:"diagnostic-bench",type:"video",title:"Diagnosing a laptop power fault",provider:"Electronics Repair Basics",url:"https://www.youtube.com/watch?v=BTSzGiOY8Mo",summary:"See the difference between symptoms, adapter checks and hypotheses.",focus:"Note which tests are safe for a beginner and which require a qualified technician.",provenance:"practitioner",accessibility:"English transcript excerpt was documented; not a safety endorsement of every demonstrated step."},
 {id:"lenovo-power-case",course:"diagnostic-bench",type:"video",title:"Lenovo not charging: observed troubleshooting",provider:"Electronics Repair School",url:"https://www.youtube.com/watch?v=j73U2ZnvrBM",summary:"A practical case study for observational learning only.",focus:"Identify the symptom and the test that changed the hypothesis.",provenance:"practitioner",accessibility:"Third-party listing identified English; do not copy live-board work without competence."},
 {id:"laptop-ssd-erasure",course:"storage-erasure",type:"video",title:"Why SSD sanitisation differs",provider:"Blancco",url:"https://www.youtube.com/watch?v=9RdeQPw_G48",summary:"Vendor explanation of SSD sanitisation concepts and tool options.",focus:"Find one assertion that needs independent validation against NIST.",provenance:"vendor",accessibility:"Direct video link; captions and current playback not independently confirmed."},
 {id:"drive-eraser-overview",course:"storage-erasure",type:"video",title:"Enterprise erasure workflow overview",provider:"Blancco",url:"https://www.youtube.com/watch?v=qNt84_b3UXw",summary:"A tool walkthrough; treat vendor certification statements as claims.",focus:"List evidence fields that a certificate should actually contain.",provenance:"vendor",accessibility:"Direct video link; caption availability unverified."},
 {id:"responsible-ewaste",course:"downstream-recycling",type:"video",title:"Recycling e-waste responsibly",provider:"Panasonic and TechCollect",url:"https://www.youtube.com/watch?v=V-3EhSnzFfI",summary:"Product stewardship introduction; older material for scheme context.",focus:"Differentiate collection from independently documented final processing.",provenance:"primary",accessibility:"Direct YouTube link; current availability and captioning not verified."},
 {id:"australian-itad",course:"ewaste-intake",type:"podcast",title:"E-waste revolution with Austin Turpin",provider:"Life on Planet A",url:"https://podcasts.apple.com/au/podcast/82-e-waste-revolution-with-austin-turpin/id1508865350?i=1000705662337",summary:"Australian operator perspective on focused electronics reuse and processing.",focus:"Name two claims that need testing in Dubbo rather than assuming they transfer.",provenance:"practitioner",accessibility:"External Apple Podcasts page; transcript availability varies."},
 {id:"device-circularity",course:"circular-thinking",type:"podcast",title:"Refurbished technology and circular growth",provider:"All Things Circular · Foxway",url:"https://podcasts.apple.com/at/podcast/ep-59-refurbished-technology-itad-circular-growth-ai/id1790559566?i=1000770978719",summary:"Device lifecycles from collection through reuse and resale.",focus:"Which stage preserves useful value, and where is data protection essential?",provenance:"practitioner",accessibility:"External podcast page; check player and transcripts with your device."},
 {id:"the-last-mile",course:"device-triage",type:"podcast",title:"The last mile: disposal and data destruction",provider:"Operational ITAM",url:"https://podcasts.apple.com/us/podcast/the-last-mile-disposal-data-destruction-and/id6794776975?i=1000779297944",summary:"Disposal and data-audit considerations from an industry perspective.",focus:"Explain why a functional device may still be unreleasable.",provenance:"practitioner",accessibility:"External Apple Podcasts page; transcript not confirmed."},
 {id:"ifixit-multimeter",course:"multimeter-low-voltage",type:"guide",title:"Illustrated guide to using a multimeter",provider:"iFixit",url:"https://www.ifixit.com/Guide/How+To+Use+A+Multimeter/25632",summary:"Readable guide to the basic controls and measurement types.",focus:"Explain why continuity testing requires an unpowered circuit.",provenance:"community",accessibility:"Text and imagery provide an alternative to video."},
 {id:"secure-disposal-acsc",course:"privacy-consent",type:"guide",title:"Dispose of your device securely",provider:"Australian Cyber Security Centre",url:"https://www.cyber.gov.au/protect-yourself/securing-your-devices/how-secure-your-device/how-dispose-your-device-securely",summary:"Official consumer advice about accounts, removable media and disposal.",focus:"What is different between a consumer reset and an audited commercial sanitisation?",provenance:"primary",accessibility:"Text-based government resource."}
];
export function mediaForCourse(course:string){return mediaItems.filter(i=>i.course===course && Boolean(getCourse(i.course)));}
export function mediaProgramme(item:MediaItem):Programme{return getCourse(item.course)?.programme??"all";}
export function safeExternalMediaUrl(url:string){try{const parsed=new URL(url);return parsed.protocol==="https:"&&["youtube.com","www.youtube.com","podcasts.apple.com","www.ifixit.com","www.cyber.gov.au"].includes(parsed.hostname);}catch{return false;}}
