import { ResponsiveTable } from "@/components/ResponsiveTable";
import { createClient } from "@/lib/supabase/server";
import { recordSale } from "../processing/actions";
import { addMarketObservation, createAutoPricedListing, createPricingRule, openReturn, resolveReturn } from "../commercial/actions";

export default async function ResalePage({searchParams}:{searchParams:Promise<{error?:string}>}) {
  const params=await searchParams;
  const supabase=await createClient();
  const [{data:assets},{data:listings},{data:sales},{data:returns},{data:rules},{data:observations}] = await Promise.all([
    supabase.from("assets").select("id,asset_code,category,manufacturer,model,data_state,ownership_verified,status").in("data_state",["VERIFIED_CLEARED","NON_DATA_BEARING"]).eq("ownership_verified",true).order("created_at",{ascending:false}),
    supabase.from("resale_listings").select("*,assets(asset_code,manufacturer,model)").order("created_at",{ascending:false}),
    supabase.from("sales").select("*,assets(asset_code)").order("sold_at",{ascending:false}).limit(100),
    supabase.from("returns_rma").select("*,assets(asset_code)").order("created_at",{ascending:false}),
    supabase.from("pricing_rules").select("*").eq("enabled",true).order("created_at",{ascending:false}),
    supabase.from("market_observations").select("*").order("observed_at",{ascending:false}).limit(100),
  ]);

  return <div className="stack"><div><div className="badge">Resale</div><h1>Pricing, qualification, sales & returns</h1><p className="muted">Ownership, cleared/non-data-bearing state and grading are hard gates. Leave asking price blank to use the most specific configured pricing rule, then matching market observations as fallback.</p></div>
    {params.error?<div className="error">{params.error}</div>:null}
    <div className="grid">
      <form action={createAutoPricedListing} className="card form"><h2>Qualify / create listing</h2><label>Asset<select name="asset_id" required defaultValue=""><option value="" disabled>Select asset</option>{(assets??[]).map((a:any)=><option key={a.id} value={a.id}>{a.asset_code} · {[a.manufacturer,a.model].filter(Boolean).join(" ")||"asset"}</option>)}</select></label><div className="two"><label>SKU<input name="sku" required/></label><label>Channel<input name="channel" placeholder="eBay / direct / other"/></label></div><label>Title<input name="title" required/></label><label>Description<textarea name="description"/></label><label>Asking price<input name="asking_price" type="number" min="0" step="0.01" placeholder="Blank = rule/market recommendation"/></label><button className="button">Run gate & create listing</button></form>
      <form action={createPricingRule} className="card form"><h2>Pricing rule</h2><label>Name<input name="name" required/></label><div className="two"><label>Category<input name="category" placeholder="Blank = any"/></label><label>Grade<input name="grade" placeholder="Blank = any"/></label></div><div className="two"><label>Base price<input name="base_price" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Minimum price<input name="min_price" type="number" min="0" step="0.01" defaultValue="0"/></label></div><button className="button secondary">Save pricing rule</button></form>
      <form action={addMarketObservation} className="card form"><h2>Market observation</h2><label>Category<input name="category" required/></label><div className="two"><label>Manufacturer<input name="manufacturer"/></label><label>Model<input name="model"/></label></div><div className="two"><label>Grade<input name="grade"/></label><label>Observed price<input name="observed_price" type="number" min="0" step="0.01" required/></label></div><label>Source<input name="source" required placeholder="Sold listing / quote / direct sale"/></label><label>Notes<textarea name="notes"/></label><button className="button secondary">Record observation</button></form>
    </div>
    <section className="card"><h2>Pricing inputs</h2><p className="muted">{rules?.length??0} active rule{rules?.length===1?"":"s"} · {observations?.length??0} recent observation{observations?.length===1?"":"s"}.</p></section>
    <section className="card"><h2>Listings</h2><div className="table-wrap"><ResponsiveTable><thead><tr><th>SKU</th><th>Asset</th><th>Channel</th><th>Price</th><th>Status</th><th>Record sale</th></tr></thead><tbody>{(listings??[]).map((l:any)=><tr key={l.id}><td><strong>{l.sku}</strong></td><td>{l.assets?.asset_code||"—"}</td><td>{l.channel||"—"}</td><td>{"$"+Number(l.asking_price??0).toFixed(2)}</td><td>{l.status}</td><td>{l.status==="SOLD"?"Sold":<form action={recordSale} className="mini-form"><input type="hidden" name="listing_id" value={l.id}/><input name="sold_price" type="number" min="0" step="0.01" required placeholder="Sold $"/><input name="fees" type="number" min="0" step="0.01" placeholder="Fees"/><input name="freight" type="number" min="0" step="0.01" placeholder="Freight"/><input name="channel_order_id" placeholder="Order ref"/><input name="tracking" placeholder="Tracking"/><button className="button secondary">Sold</button></form>}</td></tr>)}</tbody></ResponsiveTable></div></section>

    <section className="card"><h2>Sales / open return</h2><div className="table-wrap"><ResponsiveTable><thead><tr><th>Asset</th><th>Sold</th><th>Fees</th><th>Freight</th><th>Return / RMA</th></tr></thead><tbody>{(sales??[]).map((s:any)=><tr key={s.id}><td>{s.assets?.asset_code||"—"}</td><td>{"$"+Number(s.sold_price??0).toFixed(2)}</td><td>{"$"+Number(s.fees??0).toFixed(2)}</td><td>{"$"+Number(s.freight??0).toFixed(2)}</td><td><form action={openReturn} className="mini-form"><input type="hidden" name="sale_id" value={s.id}/><input type="hidden" name="asset_id" value={s.asset_id}/><input name="reason" required placeholder="Reason for return"/><button className="button secondary">Open RMA</button></form></td></tr>)}</tbody></ResponsiveTable></div></section>

    <section className="card"><h2>Returns / RMA</h2>{!(returns??[]).length?<p className="muted">No returns recorded.</p>:<div className="table-wrap"><ResponsiveTable><thead><tr><th>Asset</th><th>Reason</th><th>Status</th><th>Resolution</th></tr></thead><tbody>{(returns??[]).map((r:any)=><tr key={r.id}><td>{r.assets?.asset_code||"—"}</td><td>{r.reason}</td><td>{r.status}</td><td>{["REFUNDED","REPAIRED","REPLACED","CLOSED","REJECTED"].includes(r.status)?r.resolution||"—":<form action={resolveReturn} className="mini-form"><input type="hidden" name="return_id" value={r.id}/><select name="status" defaultValue="CLOSED"><option>REFUNDED</option><option>REPAIRED</option><option>REPLACED</option><option>CLOSED</option><option>REJECTED</option></select><input name="resolution" required placeholder="Resolution"/><input name="refund_amount" type="number" min="0" step="0.01" placeholder="Refund $"/><input name="internal_cost" type="number" min="0" step="0.01" placeholder="Internal cost $"/><button className="button secondary">Resolve</button></form>}</td></tr>)}</tbody></ResponsiveTable></div>}</section>
  </div>;
}
