import { createClient } from "@/lib/supabase/server";
import { createDefectTemplate, createDeploymentProfile, createWorkflowRule, createWorkstation, planDeploymentRun } from "./actions";
import { recordDiagnosticRun } from "../operations/actions";

export default async function ProcessingPage({searchParams}:{searchParams:Promise<{error?:string}>}) {
  const params=await searchParams;
  const supabase=await createClient();
  const [{data:rules},{data:stations},{data:locations},{data:defectTemplates},{data:capabilities},{data:profiles},{data:deploymentRuns},{count:wipe},{count:diagnostics},{count:repair}] = await Promise.all([
    supabase.from("workflow_rules").select("*").order("priority"),
    supabase.from("workstations").select("*,locations(name)").order("name"),
    supabase.from("locations").select("id,name").eq("active",true).order("name"),
    supabase.from("defect_templates").select("*").eq("active",true).order("name"),
    supabase.from("sanitisation_capabilities").select("*").eq("active",true).order("interface"),
    supabase.from("deployment_profiles").select("*").order("created_at", {ascending:false}),
    supabase.from("deployment_runs").select("id,status,external_run_id,created_at,deployment_profiles(name,provider)").order("created_at", {ascending:false}).limit(20),
    supabase.from("media").select("*",{count:"exact",head:true}).in("data_state",["UNWIPED_RESTRICTED","SANITISATION_IN_PROGRESS","SANITISATION_FAILED"]),
    supabase.from("assets").select("*",{count:"exact",head:true}).eq("status","DIAGNOSTICS"),
    supabase.from("assets").select("*",{count:"exact",head:true}).eq("status","REPAIR"),
  ]);
  return <div className="stack">
    <div><div className="badge">Processing control</div><h1>Processing</h1><p className="muted">Queue overview plus first configurable workflow-rule and workstation profiles.</p></div>
    {params.error?<div className="error">{params.error}</div>:null}
    <div className="grid"><div className="card"><div className="muted">Media requiring attention</div><div className="metric">{wipe??0}</div></div><div className="card"><div className="muted">Diagnostics</div><div className="metric">{diagnostics??0}</div></div><div className="card"><div className="muted">Repair</div><div className="metric">{repair??0}</div></div></div>
    <div className="grid">
      <form action={createWorkflowRule} className="card form"><h2>Add workflow rule</h2><label>Name<input name="name" required/></label><label>Priority<input name="priority" type="number" defaultValue="100" required/></label><label>Conditions JSON<textarea name="conditions" defaultValue={'{"data_bearing":true}'}/></label><label>Action JSON<textarea name="action" defaultValue={'{"route":"SANITISATION"}'}/></label><button className="button">Save rule</button></form>
      <form action={createWorkstation} className="card form"><h2>Add workstation</h2><label>Name<input name="name" required placeholder="Wipe Bench 1"/></label><label>Profile<select name="profile_type"><option>RECEIVING</option><option>WIPE</option><option>DIAGNOSTICS</option><option>REPAIR</option><option>GRADING</option><option>PARTS</option><option>OTHER</option></select></label><label>Location<select name="location_id" defaultValue=""><option value="">Unassigned</option>{(locations??[]).map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button className="button">Save workstation</button></form>
    </div>
    <section className="card"><h2>Sanitisation capability matrix</h2><p className="muted">This is a preflight and evidence catalogue. It does not claim that this browser session can issue drive commands.</p><div className="table-wrap"><table><thead><tr><th>Interface</th><th>Clear</th><th>Purge</th><th>OPAL</th><th>HPA / DCO</th><th>Control</th></tr></thead><tbody>{(capabilities??[]).map((c:any)=><tr key={c.id}><td><strong>{c.interface}</strong><br/><span className="small">{(c.media_families??[]).join(", ")}</span></td><td>{c.clear_supported?"Yes":"No"}</td><td>{c.purge_supported?"Yes":"No"}</td><td>{c.opal_supported?"Yes":"No"}</td><td>{c.hpa_dco_check_supported?"Record check":"Escalate"}</td><td className="small">{c.notes}</td></tr>)}</tbody></table></div></section>
    <div className="grid">
      <form action={recordDiagnosticRun} className="card form"><h2>Record diagnostic run</h2><p className="muted small">Use a local agent, boot medium or external report, then paste the structured result evidence.</p><label>Asset UUID<input name="asset_id" required placeholder="Asset UUID"/></label><label>Profile UUID<input name="profile_id" placeholder="Optional profile UUID"/></label><div className="two"><label>Execution<select name="execution_mode"><option>MANUAL</option><option>LOCAL_AGENT</option><option>BOOT_MEDIA</option><option>EXTERNAL_REPORT</option></select></label><label>Status<select name="status"><option>PASSED</option><option>FAILED</option><option>REVIEW</option><option>RUNNING</option><option>QUEUED</option></select></label></div><label>Results JSON<textarea name="results" required defaultValue={'[{"test_type":"Boot / POST","result":"PASS","notes":""},{"test_type":"Storage health","result":"PASS","notes":""},{"test_type":"Battery","result":"REVIEW","notes":""}]'}/></label><label>Notes<textarea name="notes"/></label><button className="button">Save diagnostic run</button></form>
      <form action={createDeploymentProfile} className="card form"><h2>Register deployment hook</h2><p className="muted small">Stores an approved integration reference. It does not execute MSI, PXE, Intune or ServiceNow jobs.</p><label>Name<input name="name" required placeholder="Blancco Windows PE bench"/></label><label>Provider<select name="provider"><option>BLANCCO</option><option>SERVICE_NOW</option><option>MICROSOFT_ENDPOINT_MANAGER</option><option>PXE_NETBOOT</option><option>OTHER</option></select></label><label>Package / ISO / profile reference<input name="package_reference" placeholder="Vault path or vendor package ID"/></label><label>Command / API reference<input name="command_reference" placeholder="Runbook or endpoint reference"/></label><label>Target environment<input name="target_environment" placeholder="Windows PE / managed fleet / bench"/></label><button className="button secondary">Save controlled hook</button></form>
    </div>
    <section className="card"><h2>Deployment profiles and runs</h2>{!(profiles??[]).length?<p className="muted">No deployment hooks registered.</p>:<div className="table-wrap"><table><thead><tr><th>Profile</th><th>Provider</th><th>Reference</th><th>Plan run</th></tr></thead><tbody>{(profiles??[]).map((p:any)=><tr key={p.id}><td><strong>{p.name}</strong><br/><span className="small">{p.target_environment||"environment unspecified"}</span></td><td>{p.provider}</td><td className="small">{p.package_reference||"—"}</td><td><form action={planDeploymentRun} className="mini-form"><input type="hidden" name="profile_id" value={p.id}/><input name="asset_id" placeholder="Asset UUID (optional)"/><input name="job_id" placeholder="Job UUID (optional)"/><input name="notes" placeholder="Approval / scope note"/><button className="button secondary">Plan only</button></form></td></tr>)}</tbody></table></div>}</section>
    <section className="card"><h2>Recent deployment runs</h2><div className="table-wrap"><table><thead><tr><th>Created</th><th>Profile</th><th>Status</th><th>External run</th></tr></thead><tbody>{(deploymentRuns??[]).map((r:any)=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString("en-AU")}</td><td>{r.deployment_profiles?.name||"—"} <span className="small">{r.deployment_profiles?.provider||""}</span></td><td>{r.status}</td><td>{r.external_run_id||"Awaiting external execution"}</td></tr>)}</tbody></table></div></section>
    <form action={createDefectTemplate} className="card form"><h2>Defect / devaluation template</h2><div className="two"><label>Name<input name="name" required/></label><label>Category<input name="category" placeholder="Blank = any"/></label></div><div className="two"><label>Severity<select name="severity" defaultValue="MINOR"><option>COSMETIC</option><option>MINOR</option><option>MAJOR</option><option>CRITICAL</option></select></label><label>Grade penalty<input name="grade_penalty" type="number" min="0" defaultValue="0"/></label></div><div className="two"><label>Fixed value penalty<input name="value_penalty_fixed" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Percent penalty<input name="value_penalty_percent" type="number" min="0" max="100" step="0.1" defaultValue="0"/></label></div><label>Route override<input name="route_override" placeholder="REFURBISH / PARTS / RECYCLE / HOLD"/></label><button className="button secondary">Save defect template</button></form>
    <section className="card"><h2>Defect templates</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Category</th><th>Severity</th><th>Grade penalty</th><th>Value penalty</th><th>Route</th></tr></thead><tbody>{(defectTemplates??[]).map((d:any)=><tr key={d.id}><td>{d.name}</td><td>{d.category||"Any"}</td><td>{d.severity}</td><td>{d.grade_penalty}</td><td>{"$"+Number(d.value_penalty_fixed||0).toFixed(2)} + {Number(d.value_penalty_percent||0)}%</td><td>{d.route_override||"—"}</td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>Workflow rules</h2><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Name</th><th>Conditions</th><th>Action</th></tr></thead><tbody>{(rules??[]).map((r:any)=><tr key={r.id}><td>{r.priority}</td><td>{r.name}</td><td className="small">{JSON.stringify(r.conditions)}</td><td className="small">{JSON.stringify(r.action)}</td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>Workstations</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Profile</th><th>Location</th></tr></thead><tbody>{(stations??[]).map((s:any)=><tr key={s.id}><td>{s.name}</td><td>{s.profile_type}</td><td>{s.locations?.name||"—"}</td></tr>)}</tbody></table></div></section>
  </div>;
}
