/** Hardware family atlas for the public Storage Explorer.
 * Approximate introduction years and representative interfaces, not compatibility guarantees.
 * Never infer fit solely from drive appearance or "generation".
 */
export type DriveKind = "HDD" | "SSD" | "Hybrid" | "Flash" | "Removable" | "Tape";
export type StorageItem = {
 id:string; title:string; kind:DriveKind; era:string; format:string; interface:string;
 protocol:string; connection:string; use:string; spot:string; caveat:string; host:string;
};
export const eras = [
 {year:"1956–1970s",title:"Room-sized and removable-pack disks",description:"Early magnetic hard disks used large platters and dedicated controllers. Neither capacity nor connectors resembled modern PC drives."},
 {year:"1970s–1980s",title:"Floppies, Winchester and ST-506",description:"Floppy disks became everyday removable media. Winchester sealed hard-disk assemblies led to the ST-506/ST-412 MFM controller era."},
 {year:"1980s",title:"RLL, ESDI, SCSI and ATA emerge",description:"Encoding schemes, controller technologies and host interfaces evolved independently. IDE/ATA integrated the controller with the drive."},
 {year:"1990s",title:"IDE/PATA, SCSI, optical and removable cartridges",description:"40-pin desktop and 44-pin laptop ATA drives dominated PCs. SCSI served workstations/servers; Zip, CD and MO offered removable storage."},
 {year:"2000–2005",title:"Serial ATA arrives",description:"SATA gradually replaced parallel ATA in PCs. The first SATA signalling speed was 1.5 Gb/s, with later 3 and 6 Gb/s revisions."},
 {year:"2005–2010",title:"Consumer flash SSDs take off",description:"PATA and SATA SSDs brought flash memory to familiar laptop/desktop bays. SAS became the enterprise serial successor to parallel SCSI."},
 {year:"2010–2015",title:"SATA SSD, mSATA and M.2",description:"2.5-inch SATA SSDs became practical upgrades. mSATA and then M.2 enabled compact storage; an M.2 card was not necessarily NVMe."},
 {year:"2013–2020",title:"NVMe over PCIe",description:"NVMe, designed for non-volatile memory, removed limitations of the older AHCI command interface. M.2 NVMe and PCIe add-in SSDs became common."},
 {year:"2020s",title:"PCIe Gen4/5/6, U.3 and EDSFF",description:"Faster PCIe links and enterprise form factors expanded performance and serviceability. Gen number alone does not establish a drive's real throughput."},
 {year:"Future / specialist",title:"Storage keeps branching",description:"Zoned media, new NAND types, NVMe-oF, CXL and archival technologies describe different layers or use cases, not interchangeable drive sockets."}
];
export const items:StorageItem[] = [
 {id:"ramac",title:"Early large-format HDD (IBM 350 era)",kind:"HDD",era:"1950s–1970s",format:"Cabinet / removable pack",interface:"Proprietary",protocol:"Controller-specific",connection:"Dedicated cabinet hardware",use:"Mainframes",host:"legacy",spot:"Large multi-platter assembly in a cabinet, not a PC drive.",caveat:"Museum/history only; not an interchangeable connector standard."},
 {id:"st506",title:"ST-506/ST-412 MFM HDD",kind:"HDD",era:"1980s",format:"5.25-inch / 3.5-inch",interface:"ST-506 controller cabling",protocol:"Controller-managed MFM",connection:"34-pin control + 20-pin data plus power",use:"Early PCs",host:"legacy",spot:"Separate control and data ribbon cables; not the later IDE connector.",caveat:"MFM describes encoding; geometry, controller and cabling must all match."},
 {id:"rll",title:"RLL hard disk (ST-506 family)",kind:"HDD",era:"1980s",format:"5.25-inch / 3.5-inch",interface:"Controller cabling",protocol:"Controller-managed RLL",connection:"Typically 34-pin + 20-pin",use:"Early PCs",host:"legacy",spot:"Looks similar to some MFM-era disks; controller determines usage.",caveat:"RLL is an encoding family, not a modern plug-and-play socket."},
 {id:"esdi",title:"ESDI hard disk",kind:"HDD",era:"mid-1980s–1990s",format:"3.5-inch / 5.25-inch",interface:"ESDI",protocol:"ESDI",connection:"34-pin control + 20-pin data",use:"Workstations / early PCs",host:"legacy",spot:"Similar ribbons to ST-506 but with different signalling.",caveat:"Never assume ESDI and ST-506 are interchangeable because plugs resemble one another."},
 {id:"pata35",title:"Desktop IDE / PATA HDD",kind:"HDD",era:"1986–2010s",format:"3.5-inch",interface:"Parallel ATA",protocol:"ATA/ATAPI",connection:"40-pin ribbon + 4-pin Molex power",use:"Desktop",host:"pata40",spot:"Wide 40-pin connector, jumper block and separate Molex power.",caveat:"Master/slave or cable-select, 40/80-conductor cable and BIOS drive-size limits can matter."},
 {id:"pata25",title:"Laptop IDE / PATA HDD",kind:"HDD",era:"1990s–2010s",format:"2.5-inch",interface:"Parallel ATA",protocol:"ATA",connection:"44-pin combined data/power",use:"Laptop",host:"pata44",spot:"Two rows of fine pins; 44-pin laptop PATA is not desktop 40-pin.",caveat:"Some laptops use caddies and interposers that hide the original drive connector."},
 {id:"scsi50",title:"Parallel SCSI HDD (50-pin)",kind:"HDD",era:"1980s–2000s",format:"3.5-inch / 5.25-inch",interface:"Parallel SCSI",protocol:"SCSI",connection:"50-pin internal connector",use:"Workstation / server",host:"scsi",spot:"Wide multi-pin connection and SCSI identification/termination requirements.",caveat:"SCSI variants differ in width, connector, signalling and termination."},
 {id:"scsi68",title:"Wide / Ultra SCSI HDD",kind:"HDD",era:"1990s–2000s",format:"3.5-inch",interface:"Parallel SCSI",protocol:"SCSI",connection:"68-pin or 80-pin SCA variants",use:"Server",host:"scsi",spot:"More contacts than narrow SCSI; SCA models integrate power and signals.",caveat:"A 68-pin cable is not a direct match for an 80-pin hot-swap carrier."},
 {id:"fc",title:"Fibre Channel hard disk",kind:"HDD",era:"1990s–2010s",format:"3.5-inch / 2.5-inch",interface:"Fibre Channel",protocol:"FCP/SCSI",connection:"Enterprise backplane",use:"SAN / enterprise",host:"legacy",spot:"Enterprise carrier/backplane design, not standard desktop SATA.",caveat:"Fibre Channel host hardware and backplane required."},
 {id:"sata35",title:"3.5-inch SATA HDD",kind:"HDD",era:"2003–present",format:"3.5-inch",interface:"SATA 1.5/3/6 Gb/s",protocol:"ATA / AHCI",connection:"7-pin SATA data + 15-pin SATA power",use:"Desktop / NAS",host:"sata35",spot:"Two L-shaped SATA connectors; usually desktop/NAS size.",caveat:"Needs 3.5-inch mounting and usually 12V + 5V power; USB-powered 2.5-inch-only adapters may not power it."},
 {id:"sata25h",title:"2.5-inch SATA HDD",kind:"HDD",era:"2003–present",format:"2.5-inch",interface:"SATA 1.5/3/6 Gb/s",protocol:"ATA / AHCI",connection:"7-pin SATA data + 15-pin SATA power",use:"Laptop / console",host:"sata",spot:"Compact magnetic hard drive, often 7–9.5 mm thick; same SATA connector as 2.5-inch SSD.",caveat:"Thickness and mounting clearance matter; a SATA drive can operate at a lower negotiated link rate."},
 {id:"sas",title:"Enterprise SAS HDD",kind:"HDD",era:"2004–present",format:"2.5-inch / 3.5-inch",interface:"SAS",protocol:"SCSI over SAS",connection:"SAS enterprise backplane",use:"Server / storage array",host:"sas",spot:"SAS connector has a continuous bridge where SATA's two L-shaped pieces are separated.",caveat:"A SAS disk does NOT work on an ordinary SATA-only motherboard port."},
 {id:"usb-hdd",title:"External USB hard drive",kind:"HDD",era:"1990s–present",format:"Portable / desktop enclosure",interface:"USB bridge",protocol:"USB mass-storage / UASP",connection:"USB cable to bridge",use:"Backup",host:"external",spot:"HDD in an enclosure; internally may be SATA or a native USB PCB.",caveat:"Do not assume all external drives contain a shuckable SATA disk."},
 {id:"sshd",title:"Hybrid SSHD",kind:"Hybrid",era:"2010s",format:"2.5-inch / 3.5-inch",interface:"Usually SATA",protocol:"ATA",connection:"SATA data + power",use:"Laptop / desktop",host:"sata",spot:"Mechanical hard drive with a small flash cache marketed as hybrid.",caveat:"Still contains platters; flash cache does not make it equivalent to a full SSD."},
 {id:"microdrive",title:"CompactFlash Microdrive",kind:"HDD",era:"1999–2010s",format:"CompactFlash Type II",interface:"CF/ATA",protocol:"ATA",connection:"50-pin CF interface",use:"Camera / PDA",host:"cf",spot:"Tiny spinning drive in a CompactFlash Type II package.",caveat:"Type I slots are thinner and may not fit Type II Microdrives."},
 {id:"pata-ssd",title:"PATA / IDE SSD",kind:"SSD",era:"1990s–2010s",format:"2.5-inch / DOM",interface:"Parallel ATA",protocol:"ATA",connection:"40/44-pin or Disk-on-Module",use:"Industrial / legacy upgrades",host:"pata44",spot:"Flash upgrade with legacy IDE pins; desktop 40-pin variants also exist.",caveat:"Confirm exact 40-pin vs 44-pin connector, voltage and BIOS support."},
 {id:"sata-ssd",title:"2.5-inch SATA SSD",kind:"SSD",era:"2000s–present",format:"2.5-inch (often 7 mm)",interface:"SATA 1.5/3/6 Gb/s",protocol:"ATA / AHCI",connection:"7-pin data + 15-pin power",use:"Laptop / desktop refurb",host:"sata",spot:"Thin rectangular drive with two L-shaped SATA connectors and no spinning platters.",caveat:"Excellent HDD replacement where the bay and interface match; verify drive caddy and software boot support."},
 {id:"msata",title:"mSATA SSD",kind:"SSD",era:"2009–2010s",format:"Mini-card-like PCB",interface:"mSATA",protocol:"ATA / AHCI",connection:"mSATA connector",use:"Ultrabook / mini PC",host:"msata",spot:"Short exposed circuit board resembling a PCIe Mini Card.",caveat:"mSATA is electrically SATA, but visually similar Mini PCIe slots are not automatically compatible."},
 {id:"m2-sata42",title:"M.2 SATA 2242 SSD",kind:"SSD",era:"2013–present",format:"M.2 2242",interface:"SATA over M.2",protocol:"ATA / AHCI",connection:"M.2 keyed edge",use:"Compact laptop",host:"m2sata",spot:"22 mm wide, 42 mm long; commonly B+M-keyed, but keys alone do not prove protocol.",caveat:"M.2 slot must provide SATA lines; verify the supported length."},
 {id:"m2-sata80",title:"M.2 SATA 2280 SSD",kind:"SSD",era:"2013–present",format:"M.2 2280",interface:"SATA over M.2",protocol:"ATA / AHCI",connection:"M.2 keyed edge",use:"Laptop / desktop",host:"m2sata",spot:"22 mm wide, 80 mm long; no SATA data cable required.",caveat:"An NVMe-only M.2 socket cannot use a SATA-only M.2 card even when it physically fits."},
 {id:"nvme2230",title:"M.2 NVMe 2230 SSD",kind:"SSD",era:"2010s–present",format:"M.2 2230",interface:"PCIe x2/x4",protocol:"NVMe",connection:"M.2 edge connector",use:"Small laptop / handheld",host:"m2nvme",spot:"22 mm wide and only 30 mm long; very short SSD card.",caveat:"Check standoff position, firmware, cooling and whether host supports PCIe/NVMe."},
 {id:"nvme2242",title:"M.2 NVMe 2242 SSD",kind:"SSD",era:"2010s–present",format:"M.2 2242",interface:"PCIe x2/x4",protocol:"NVMe",connection:"M.2 edge connector",use:"Thin laptop",host:"m2nvme",spot:"22 mm wide, 42 mm long; can resemble M.2 SATA of same size.",caveat:"Connector shape does not identify protocol; check label and system spec."},
 {id:"nvme2280",title:"M.2 NVMe 2280 SSD",kind:"SSD",era:"2013–present",format:"M.2 2280",interface:"PCIe Gen3/4/5 x4 commonly",protocol:"NVMe",connection:"M.2 M-key edge commonly",use:"Modern laptop / desktop",host:"m2nvme",spot:"22 × 80 mm board with controller and NAND packages.",caveat:"PCIe link negotiates host generation/lanes. Firmware and boot support must be checked."},
 {id:"nvme22110",title:"M.2 NVMe 22110 SSD",kind:"SSD",era:"2010s–present",format:"M.2 22110",interface:"PCIe x4",protocol:"NVMe",connection:"M.2 edge connector",use:"Workstation / enterprise",host:"m2nvme",spot:"Longer 22 × 110 mm M.2 board, sometimes with power-loss protection.",caveat:"Most ordinary 2280-only bays cannot physically mount a 22110 card."},
 {id:"pcie-aic",title:"PCIe add-in card SSD",kind:"SSD",era:"2000s–present",format:"PCIe expansion card",interface:"PCI Express",protocol:"NVMe or proprietary/legacy",connection:"PCIe slot",use:"Desktop / workstation",host:"pcie",spot:"Expansion-card-sized board with flash or M.2 drives.",caveat:"An adapter may allow data access yet still require separate firmware support to boot."},
 {id:"u2",title:"U.2 NVMe enterprise SSD",kind:"SSD",era:"2015–present",format:"2.5-inch enterprise (often 15 mm)",interface:"PCIe via U.2",protocol:"NVMe",connection:"U.2/SFF-8639",use:"Server / workstation",host:"u2",spot:"2.5-inch housing but a different backplane connector from SATA.",caveat:"Physical 2.5-inch appearance does not mean SATA compatibility."},
 {id:"u3",title:"U.3 tri-mode ecosystem SSD",kind:"SSD",era:"2020s–present",format:"2.5-inch enterprise",interface:"Tri-mode-capable backplane",protocol:"NVMe (for NVMe SSD)",connection:"U.3 connector / platform",use:"Server",host:"u3",spot:"Enterprise hot-swap cartridge resembling U.2.",caveat:"Tri-mode support belongs to the host/backplane ecosystem; do not assume any bay accepts all protocols."},
 {id:"e1s",title:"EDSFF E1.S NVMe SSD",kind:"SSD",era:"2020s–present",format:"EDSFF E1.S",interface:"PCIe",protocol:"NVMe",connection:"EDSFF edge / server bay",use:"Dense server",host:"edsff",spot:"Slim, elongated server SSD with a specialised edge connector.",caveat:"Not interchangeable with M.2, U.2 or E3.S housings."},
 {id:"e1l",title:"EDSFF E1.L NVMe SSD",kind:"SSD",era:"2020s–present",format:"EDSFF E1.L",interface:"PCIe",protocol:"NVMe",connection:"EDSFF edge / server bay",use:"High-capacity server",host:"edsff",spot:"Long ruler-like enterprise drive, with dedicated thermal design.",caveat:"Requires matching server chassis, connectors and cooling."},
 {id:"e3s",title:"EDSFF E3.S NVMe SSD",kind:"SSD",era:"2020s–present",format:"EDSFF E3.S",interface:"PCIe",protocol:"NVMe",connection:"EDSFF E3 backplane",use:"Enterprise",host:"edsff",spot:"Short E3 hot-swap form factor, not a conventional 2.5-inch SATA drive.",caveat:"E3.S and E3.L mechanical lengths differ."},
 {id:"e3l",title:"EDSFF E3.L NVMe SSD",kind:"SSD",era:"2020s–present",format:"EDSFF E3.L",interface:"PCIe",protocol:"NVMe",connection:"EDSFF E3 backplane",use:"Enterprise",host:"edsff",spot:"Long E3 enterprise hot-swap form factor.",caveat:"Confirm enclosure depth, thickness, power and cooling."},
 {id:"apple",title:"Proprietary laptop blade SSD",kind:"SSD",era:"2010s",format:"Vendor-specific blade",interface:"SATA or PCIe (model-dependent)",protocol:"ATA or NVMe/proprietary",connection:"Vendor-specific socket",use:"Some Macs / ultrabooks",host:"proprietary",spot:"Long narrow module resembling M.2, but keyed differently.",caveat:"Model year, drive controller, adapter, firmware and power arrangements must be verified."},
 {id:"bga",title:"Soldered BGA / eMMC storage",kind:"Flash",era:"2000s–present",format:"Board-mounted IC",interface:"eMMC",protocol:"JEDEC eMMC",connection:"BGA soldered package",use:"Budget laptops / embedded",host:"soldered",spot:"Storage chips soldered directly on a PCB rather than socketed.",caveat:"Not a drop-in SSD replacement; board-level work and data recovery are specialised."},
 {id:"ufs",title:"Soldered UFS storage",kind:"Flash",era:"2010s–present",format:"Board-mounted IC",interface:"UFS",protocol:"JEDEC UFS",connection:"BGA soldered package",use:"Phone / mobile",host:"soldered",spot:"Embedded flash in compact mobile computing devices.",caveat:"Not mechanically interchangeable with eMMC or M.2."},
 {id:"usb-stick",title:"USB flash drive",kind:"Flash",era:"2000s–present",format:"Portable stick",interface:"USB 2/3/4 variants",protocol:"USB MSC / UASP depending device",connection:"USB-A / USB-C",use:"Installer / portable media",host:"external",spot:"Small, bus-powered removable flash device.",caveat:"USB connector type and advertised version do not guarantee sustained speed or write endurance."},
 {id:"cf",title:"CompactFlash card",kind:"Flash",era:"1994–present legacy",format:"CF Type I / II",interface:"Parallel ATA family",protocol:"ATA",connection:"50-pin CompactFlash",use:"Camera / industrial",host:"cf",spot:"Thick rectangular card with rows of socket holes.",caveat:"CF, CFast and CFexpress are entirely different interfaces despite similar naming."},
 {id:"sd",title:"SD / SDHC / SDXC / SDUC",kind:"Flash",era:"2000–present",format:"Full-size SD",interface:"SD / UHS etc",protocol:"SD commands",connection:"SD contacts",use:"Camera / embedded",host:"sd",spot:"Small removable card with diagonal clipped corner.",caveat:"Capacity generations, host compatibility, speed classes and file systems are separate questions."},
 {id:"micro-sd",title:"microSD / microSDXC",kind:"Flash",era:"2005–present",format:"microSD",interface:"SD / UHS etc",protocol:"SD commands",connection:"microSD contacts",use:"Phone / camera / SBC",host:"sd",spot:"Thumbnail-sized removable card.",caveat:"Full-size SD adapter changes the shape, not the card's capability."},
 {id:"cfast",title:"CFast card",kind:"Flash",era:"2009–present",format:"CFast card",interface:"SATA",protocol:"ATA",connection:"CFast connector",use:"Professional camera",host:"cfast",spot:"CF-like removable memory card with SATA-derived contacts.",caveat:"CFast is not a CompactFlash or CFexpress card."},
 {id:"cfexpress",title:"CFexpress Type A/B/C",kind:"Flash",era:"2017–present",format:"CFexpress card",interface:"PCIe",protocol:"NVMe",connection:"Type-specific CFexpress socket",use:"Camera / media",host:"cfexpress",spot:"Professional high-speed removable card, available in differently sized types.",caveat:"CFexpress Types A/B/C are physically different; XQD overlap is device-specific."},
 {id:"floppy",title:"3.5-inch / 5.25-inch floppy disk",kind:"Removable",era:"1970s–2000s",format:"Magnetic diskette",interface:"Floppy controller",protocol:"FDC",connection:"Floppy drive cable",use:"Legacy PC",host:"legacy",spot:"Flexible magnetic disk inside removable sleeve or plastic shell.",caveat:"Media densities, drive compatibility and ageing data condition vary."},
 {id:"zip",title:"Iomega Zip removable cartridge",kind:"Removable",era:"1990s–2000s",format:"Proprietary cartridge",interface:"Parallel / SCSI / USB variants",protocol:"Drive-specific",connection:"Matching Zip drive",use:"Legacy backup",host:"legacy",spot:"Thick removable cartridge, distinct from a floppy disk.",caveat:"Requires matching working drive; do not force disks or connectors."},
 {id:"cd-dvd",title:"CD / DVD / Blu-ray optical media",kind:"Removable",era:"1980s–present",format:"12 cm / small optical discs",interface:"Optical drive SATA/ATAPI/USB etc",protocol:"ATAPI / MMC",connection:"Matching optical drive",use:"Install / archives / media",host:"legacy",spot:"Reflective disc read by laser; recordable and rewritable variants.",caveat:"Format, regional/media support and damaged discs can prevent reading."},
 {id:"tape",title:"Magnetic tape (DAT / LTO etc)",kind:"Tape",era:"1950s–present",format:"Tape cartridge / reel",interface:"SCSI / SAS / FC etc",protocol:"Tape SCSI command sets",connection:"Matching tape drive / library",use:"Long-term backup",host:"legacy",spot:"Cartridge or spool of magnetic tape rather than random-access disk.",caveat:"Tape generation read/write backwards compatibility varies; retrieval needs the correct drive and software."},
];
export const storageSources = [
 {title:"SATA-IO: official naming and link compatibility",url:"https://sata-io.org/developers/sata-naming-guidelines"},
 {title:"SATA-IO: release timeline",url:"https://sata-io.org/20th-anniversary"},
 {title:"Kingston: SSD formats including M.2, U.2 and EDSFF",url:"https://www.kingston.com/unitedkingdom/en/blog/pc-performance/ssd-form-factors"},
 {title:"Kingston: NVMe vs SATA and command interfaces",url:"https://www.kingston.com/en/ssd/what-is-nvme-ssd-technology"},
 {title:"Crucial: PCIe generations and backwards compatibility",url:"https://stage.crucial.com/support/articles-faq-ssd/pcie-speeds-limitations"}
];
