const KEY = "dubbo-ewaste-demo-v1";
const guides = {laptop:["Windows 11 CPU/TPM pathway","BIOS password, MDM and Autopilot","Battery, charger and hinge","Storage health and sanitisation"],mac:["Apple generation and macOS support","Activation Lock and Find My","Battery cycle health","Erase evidence"],phone:["IMEI/serial recorded privately","Activation Lock and carrier state","Battery, screen and cameras","Secure reset verification"],android:["Google FRP and MDM","IMEI/serial and carrier state","Battery, display and ports","Secure reset verification"],chromebook:["Google AUE date","Forced re-enrolment / admin lock","Battery, keyboard and screen","Education or parts route"],desktop:["CPU/TPM/Windows 11 pathway","Storage health and sanitisation","RAM, ports, network and PSU","Dust and missing parts"],monitor:["Power, display and dead pixels","Inputs, stand and cable","Panel and backlight","Safe transport route"],tv:["Panel, inputs, remote and power","No CRT or unsafe fault","Transport and storage footprint","Named buyer or receiver"],networking:["Factory reset and ownership","Ports, PoE and power supply","Firmware/controller compatibility","Specialist route"]};
const models = [["Lenovo ThinkPad T14 Gen 2","laptop","Windows 11 eligible in common Intel configurations","BIOS / Autopilot check","Reuse / refurbish"],["Dell Latitude 5420","laptop","Windows 11 eligible in common Intel configurations","BIOS / Autopilot check","Reuse / parts"],["Apple MacBook Air M1","mac","Current macOS support must be checked","Activation Lock / Find My","Reuse / refurbish"],["iPhone 11","phone","Current iOS support must be checked","Activation Lock / carrier","Reuse / social reuse"],["Samsung Galaxy A52","android","Android support varies by region","Google FRP / enterprise","Reuse / parts"],["Lenovo 300e Chromebook","chromebook","ChromeOS AUE is decisive","Forced re-enrolment","Reuse before AUE / parts"],["Dell OptiPlex 7090 Micro","desktop","Windows 11 configuration check","BIOS / management","Reuse / parts"],["Dell P2422H","monitor","OS-independent display","No account lock","Local resale / reuse"],["Ubiquiti UniFi AP AC Lite","networking","Firmware/controller check","Reset / ownership","Specialist resale / parts"]];
function load(){try{return Object.assign({user:null,inventory:[],activity:[]},JSON.parse(localStorage.getItem(KEY)||"{}"));}catch{return {user:null,inventory:[],activity:[]};}}
const state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));} function $(s){return document.querySelector(s);} function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));} function money(v){return new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(Number(v)||0);}
function activity(text){state.activity.unshift({text,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})});state.activity=state.activity.slice(0,8);save();renderOverview();}
function showApp(){$("#login-screen").classList.add("hidden");$("#app-shell").classList.remove("hidden");$("#user-email").textContent=state.user.email;$("#user-initial").textContent=state.user.email[0].toUpperCase();renderAll();}
function showView(view){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===`view-${view}`));document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#page-title").textContent={overview:"Overview",intake:"New intake",inventory:"Inventory",models:"Model lookup",economics:"Economics"}[view];if(view==="inventory")renderInventory();if(view==="models")renderModels();window.scrollTo({top:0,behavior:"smooth"});}
$("#login-form").addEventListener("submit",e=>{e.preventDefault();const email=$("#login-email").value.trim();if(!email||$("#login-password").value!=="demo"){$("#login-message").textContent="Prototype login: use any email and password demo.";return;}state.user={email,role:"Operator"};save();showApp();}); $("#logout-button").addEventListener("click",()=>{state.user=null;save();$("#login-screen").classList.remove("hidden");$("#app-shell").classList.add("hidden");});
document.querySelectorAll("[data-view]").forEach(x=>x.addEventListener("click",()=>showView(x.dataset.view)));document.querySelectorAll("[data-go]").forEach(x=>x.addEventListener("click",()=>showView(x.dataset.go)));
function renderOverview(){const items=state.inventory;$("#metric-inventory").textContent=items.length;$("#metric-holds").textContent=items.filter(x=>x.decision!=="ACCEPT").length;$("#metric-value").textContent=money(items.reduce((a,x)=>a+(Number(x.value)||0),0));const mins=items.reduce((a,x)=>a+(Number(x.minutes)||0),0);$("#metric-time").textContent=`${items.length?Math.round(mins/items.length):0}m`;$("#recent-activity").innerHTML=state.activity.length?state.activity.map(x=>`<div class="activity"><i></i><div>${esc(x.text)}<small>${esc(x.time)}</small></div></div>`).join(""):`<p class="empty-state">No activity yet. Start with a known-source item.</p>`;}
function renderGuide(){const key=$("#device-category").value,list=guides[key]||guides.laptop,names={laptop:"Windows laptop",mac:"Mac",phone:"iPhone / iPad",android:"Android phone / tablet",chromebook:"Chromebook",desktop:"Desktop / mini-PC",monitor:"Monitor",tv:"TV",networking:"Networking gear"};$("#guide-title").textContent=names[key];$("#guide-copy").textContent=`Use the ${names[key]} gates before spending bench time or storage.`;$("#guide-checks").innerHTML=list.map(x=>`<div class="guide-check">${esc(x)}</div>`).join("");}
$("#device-category").addEventListener("change",renderGuide);renderGuide();
function assess(){const f=new FormData($("#intake-form")),r=[],required=[];let d="ACCEPT";if(!f.get("authority")){d="HOLD";r.push("Transfer authority is not recorded.");required.push("ownership or authority record");}if(["swollen","unsafe"].includes(f.get("battery"))||f.get("condition")==="unsafe"){d="REJECT";r.push("Battery or physical condition needs safety escalation.");required.push("quarantine and incident record");}else if(f.get("battery")==="unknown"){if(d!=="REJECT")d="HOLD";r.push("Battery has not been screened.");required.push("battery safety check");}if(f.get("lock")==="locked"){d="REJECT";r.push("A management or account lock is present.");}else if(f.get("lock")==="unknown"){if(d!=="REJECT")d="HOLD";r.push("BIOS, MDM, Activation Lock, FRP or Autopilot is not cleared.");required.push("lock verification");}if(f.get("route")==="unknown"){if(d!=="REJECT")d="HOLD";r.push("No likely final route is recorded.");required.push("buyer, social-reuse or downstream route");}if(["tv","networking"].includes(f.get("category"))&&d==="ACCEPT"){d="HOLD";r.push("This category needs prior approval or specialist route evidence.");required.push("category approval");}return{f,d,r,required};}
$("#assess-button").addEventListener("click",()=>{const x=assess(),p=$("#triage-result"),b=$("#decision-badge");p.className=`triage-result ${x.d.toLowerCase()}`;p.classList.remove("hidden");b.className=`decision-badge ${x.d.toLowerCase()}`;b.textContent=x.d;p.innerHTML=`<strong>${x.d}: ${x.d==="ACCEPT"?"Move to bench testing":x.d==="HOLD"?"Do not add to active stock yet":"Do not accept into normal workflow"}</strong><ul>${[...x.r,...(x.required.length?[`Required next evidence: ${x.required.join(", ")}`]:[])].map(y=>`<li>${esc(y)}</li>`).join("")||"<li>Front-door gates passed. Record the bench test next.</li>"}</ul>`;const f=x.f;if(x.d!=="REJECT"){const item={id:f.get("assetId"),category:f.get("category"),model:f.get("model"),decision:x.d,route:f.get("route"),value:Number(f.get("value"))||0,minutes:Number(f.get("minutes"))||0,updated:new Date().toISOString()};const old=state.inventory.find(y=>y.id===item.id);if(old)Object.assign(old,item);else state.inventory.unshift(item);activity(`${x.d} · ${item.id} · ${item.model}`);renderInventory();}else activity(`REJECT · ${f.get("assetId")||"unidentified item"}`);});
$("#intake-form").addEventListener("reset",()=>setTimeout(()=>{$("#triage-result").classList.add("hidden");$("#decision-badge").className="decision-badge neutral";$("#decision-badge").textContent="Awaiting assessment";renderGuide();},0));
function renderInventory(){const q=($("#inventory-search")?.value||"").toLowerCase(),rows=state.inventory.filter(x=>[x.id,x.model,x.route,x.category].join(" ").toLowerCase().includes(q));$("#inventory-count").textContent=`${rows.length} of ${state.inventory.length} assets`;$("#inventory-body").innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${esc(x.id)}</strong><small>${esc(x.updated?.slice(0,10)||"—")}</small></td><td><strong>${esc(x.model)}</strong><small>${esc(x.category)}</small></td><td><span class="table-decision ${x.decision.toLowerCase()}">${esc(x.decision)}</span></td><td>${esc(x.route)}</td><td>${money(x.value)}</td><td><button class="text-button listing-button" data-id="${esc(x.id)}">Draft listing</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty-state">No matching inventory. Start a new intake.</td></tr>`;document.querySelectorAll(".listing-button").forEach(b=>b.addEventListener("click",()=>{const x=state.inventory.find(y=>y.id===b.dataset.id);if(x){navigator.clipboard?.writeText(`${x.model} — inspected Dubbo E-Waste refurbished item. Route: ${x.route}. Estimated value: ${money(x.value)}.`);b.textContent="Copied draft";activity(`Listing draft copied · ${x.id}`);}}));}
$("#inventory-search").addEventListener("input",renderInventory);
function renderModels(){const q=($("#model-search")?.value||"").toLowerCase(),cat=$("#model-category").value,rows=models.filter(x=>(cat==="all"||x[1]===cat)&&x.join(" ").toLowerCase().includes(q));$("#model-grid").innerHTML=rows.map(x=>`<article class="model-card"><p class="eyebrow">${esc(x[1])}</p><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p><div class="model-meta"><div><span>Lock risk</span><span>${esc(x[3])}</span></div><div><span>Route</span><span>${esc(x[4])}</span></div></div></article>`).join("")||`<div class="panel"><p class="empty-state">No model records match.</p></div>`;}
$("#model-search").addEventListener("input",renderModels);$("#model-category").addEventListener("change",renderModels);
function economics(){const f=new FormData($("#economics-form")),sale=+f.get("sale")||0,acq=+f.get("acquisition")||0,parts=+f.get("parts")||0,costs=+f.get("costs")||0,mins=+f.get("labour")||0,rate=+f.get("rate")||0,contribution=sale-acq-parts-costs,labour=mins/60*rate,after=contribution-labour;$("#contribution").textContent=money(contribution);$("#labour-cost").textContent=money(labour);$("#after-labour").textContent=money(after);$("#per-hour").textContent=`${money(mins?contribution/(mins/60):0)}/hr`;$("#econ-message").innerHTML=`<strong>${after<0?"Hold or reject the work":"Interpretation"}</strong><p>${after<0?"This estimate does not repay target labour before safety, storage or route risk.":"Positive contribution is not enough if safety, storage or route evidence is weak."}</p>`;}
document.querySelectorAll("#economics-form input").forEach(x=>x.addEventListener("input",economics));
function renderModelsAndAll(){renderOverview();renderInventory();renderModels();economics();}
if(state.user)showApp();
