#!/usr/bin/env python3
"""Build the corrected Dubbo eWaste NotebookLM pack.

Exactly 100 PDFs:
  001: master index generated by this script
  002-045: full selected DubboEwaste repository documents converted to PDF
  046-100: genuine original PDF files downloaded from their publishers

External documents are stored byte-for-byte as downloaded. They are NOT replaced
with summaries or rewritten one-page briefs.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
import hashlib
import html
import json
import os
import re
import shutil
import subprocess
import textwrap
import time
import zipfile
from pathlib import Path

import requests
from pypdf import PdfReader
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph, Preformatted, Spacer

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "notebooklm" / "notebooklm_100_original_sources.json"
PACK_ROOT = ROOT / "notebooklm" / "2026-10-06-100-pdf-pack"
PDF_DIR = PACK_ROOT / "pdfs"
DOWNLOAD_DIR = PACK_ROOT / "_downloads"
ZIP_PATH = PACK_ROOT / "DubboEwaste-NotebookLM-100-PDF-Pack.zip"
MANIFEST_PATH = PACK_ROOT / "manifest.json"
README_PATH = PACK_ROOT / "README.md"
GENERATED = "6 October 2026"
SOURCE_COMMIT = os.environ.get("GITHUB_SHA", "local-working-tree")[:12]

FONT = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
FONT_MONO = "Courier"


def register_fonts():
    global FONT, FONT_BOLD, FONT_MONO
    candidates = [
        (
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        ),
        (
            "/usr/share/fonts/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/dejavu/DejaVuSansMono.ttf",
        ),
    ]
    for regular, bold, mono in candidates:
        if all(Path(p).exists() for p in (regular, bold, mono)):
            pdfmetrics.registerFont(TTFont("PackSans", regular))
            pdfmetrics.registerFont(TTFont("PackSansBold", bold))
            pdfmetrics.registerFont(TTFont("PackMono", mono))
            FONT, FONT_BOLD, FONT_MONO = "PackSans", "PackSansBold", "PackMono"
            break


def slug(value: str, limit: int = 105) -> str:
    value = value.replace("&", " and ")
    value = re.sub(r"[^A-Za-z0-9]+", "-", value).strip("-")
    value = re.sub(r"-+", "-", value)
    return (value[:limit].rstrip("-") or "document")


def clean_controls(value: str) -> str:
    value = value.replace("\x00", "")
    return "".join(ch for ch in value if ch in "\n\t" or ord(ch) >= 32)


def inline_text(value: str) -> str:
    value = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", r"Image: \1 (\2)", value)
    value = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1 (\2)", value)
    value = value.replace("**", "").replace("__", "").replace("~~", "").replace(chr(96), "")
    return value.strip()


def esc(value: str) -> str:
    return html.escape(clean_controls(value), quote=False)


class Doc(BaseDocTemplate):
    def __init__(self, filename: str, title: str, footer: str):
        self.footer_text = footer
        super().__init__(
            filename,
            pagesize=A4,
            leftMargin=17 * mm,
            rightMargin=17 * mm,
            topMargin=18 * mm,
            bottomMargin=18 * mm,
            title=title,
            author="Dubbo eWaste / AssetFlow",
            subject="NotebookLM research pack",
            creator="DubboEwaste corrected NotebookLM exporter",
            pageCompression=1,
        )
        frame = Frame(self.leftMargin, self.bottomMargin, self.width, self.height, id="main")
        self.addPageTemplates(PageTemplate(id="main", frames=[frame], onPage=self._footer))

    def _footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont(FONT, 7)
        canvas.setFillColor(colors.HexColor("#666666"))
        canvas.drawString(self.leftMargin, 8 * mm, f"Dubbo eWaste NotebookLM Pack | {self.footer_text[:105]} | page {doc.page}")
        canvas.restoreState()


def styles():
    s = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("TitleX", parent=s["Title"], fontName=FONT_BOLD, fontSize=19, leading=23, spaceAfter=8),
        "h1": ParagraphStyle("H1X", parent=s["Heading1"], fontName=FONT_BOLD, fontSize=14, leading=17, spaceBefore=8, spaceAfter=4, keepWithNext=True),
        "h2": ParagraphStyle("H2X", parent=s["Heading2"], fontName=FONT_BOLD, fontSize=11.5, leading=14, spaceBefore=7, spaceAfter=3, keepWithNext=True),
        "h3": ParagraphStyle("H3X", parent=s["Heading3"], fontName=FONT_BOLD, fontSize=10, leading=12.5, spaceBefore=5, spaceAfter=3, keepWithNext=True),
        "body": ParagraphStyle("BodyX", parent=s["BodyText"], fontName=FONT, fontSize=8.4, leading=11.4, spaceAfter=3, wordWrap="CJK"),
        "bullet": ParagraphStyle("BulletX", parent=s["BodyText"], fontName=FONT, fontSize=8.2, leading=11, leftIndent=10, firstLineIndent=-7, spaceAfter=2, wordWrap="CJK"),
        "meta": ParagraphStyle("MetaX", parent=s["BodyText"], fontName=FONT, fontSize=7.6, leading=9.8, textColor=colors.HexColor("#555555"), spaceAfter=2, wordWrap="CJK"),
        "mono": ParagraphStyle("MonoX", parent=s["Code"], fontName=FONT_MONO, fontSize=6.4, leading=8.1, leftIndent=3, rightIndent=2, backColor=colors.HexColor("#F5F5F5"), borderPadding=3),
        "index": ParagraphStyle("IndexX", parent=s["BodyText"], fontName=FONT, fontSize=7.3, leading=9.6, leftIndent=9, firstLineIndent=-9, spaceAfter=2, wordWrap="CJK"),
    }


def md_story(markdown: str, st: dict) -> list:
    lines = clean_controls(markdown).replace("\r\n", "\n").replace("\r", "\n").split("\n")
    story = []
    code = []
    in_code = False

    def flush_code():
        nonlocal code
        if not code:
            return
        wrapped = []
        for ln in code:
            wrapped.extend(textwrap.wrap(ln, width=100, replace_whitespace=False, drop_whitespace=False, break_long_words=True, break_on_hyphens=False) or [""])
        story.append(Preformatted("\n".join(wrapped), st["mono"], maxLineLength=104))
        code = []

    for raw in lines:
        line = raw.rstrip()
        stripped = line.strip()
        if stripped.startswith(chr(96) * 3):
            if in_code:
                flush_code()
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code.append(line)
            continue
        if not stripped:
            story.append(Spacer(1, 1.8 * mm))
            continue
        if re.fullmatch(r"[-*_]{3,}", stripped):
            story.append(Spacer(1, 2 * mm))
            continue
        h = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if h:
            level = len(h.group(1))
            style = st["h1"] if level == 1 else st["h2"] if level == 2 else st["h3"]
            story.append(Paragraph(esc(inline_text(h.group(2))), style))
            continue
        task = re.match(r"^\s*[-*+]\s+\[([ xX])\]\s+(.*)$", line)
        bullet = re.match(r"^\s*[-*+]\s+(.*)$", line)
        numbered = re.match(r"^\s*(\d+)[.)]\s+(.*)$", line)
        if task:
            mark = "[x]" if task.group(1).lower() == "x" else "[ ]"
            story.append(Paragraph(esc(f"{mark} {inline_text(task.group(2))}"), st["bullet"]))
        elif bullet:
            story.append(Paragraph(esc("- " + inline_text(bullet.group(1))), st["bullet"]))
        elif numbered:
            story.append(Paragraph(esc(f"{numbered.group(1)}. {inline_text(numbered.group(2))}"), st["bullet"]))
        elif stripped.startswith("|") and "|" in stripped[1:]:
            if not re.fullmatch(r"\|?[\s:|-]+\|?", stripped):
                cells = [inline_text(c.strip()) for c in stripped.strip("|").split("|")]
                text = " | ".join(cells)
                wrapped = "\n".join(textwrap.wrap(text, width=102, break_long_words=True, break_on_hyphens=False) or [""])
                story.append(Preformatted(wrapped, st["mono"], maxLineLength=106))
        elif stripped.startswith(">"):
            story.append(Paragraph(esc(inline_text(stripped.lstrip("> ").strip())), st["body"]))
        else:
            story.append(Paragraph(esc(inline_text(stripped)), st["body"]))
    if in_code:
        flush_code()
    return story


def write_repo_pdf(source: Path, output: Path, source_path: str, st: dict):
    title = source.stem.replace("-", " ").replace("_", " ").title()
    doc = Doc(str(output), title, source_path)
    story = [
        Paragraph(esc(title), st["title"]),
        Paragraph("<b>Source type:</b> Full DubboEwaste repository document", st["meta"]),
        Paragraph(f"<b>Repository path:</b> {esc(source_path)}", st["meta"]),
        Paragraph(f"<b>Source commit:</b> {esc(SOURCE_COMMIT)}", st["meta"]),
        Spacer(1, 2 * mm),
    ]
    story.extend(md_story(source.read_text(encoding="utf-8", errors="replace"), st))
    doc.build(story)


def pdf_info(path: Path) -> tuple[int, bool]:
    reader = PdfReader(str(path), strict=False)
    if reader.is_encrypted:
        try:
            reader.decrypt("")
        except Exception:
            pass
    return len(reader.pages), bool(reader.is_encrypted)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def download_pdf(url: str, dest: Path):
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; DubboEwasteResearchPack/1.0; +https://github.com/joshualparris/DubboEwaste)",
        "Accept": "application/pdf,application/octet-stream;q=0.9,*/*;q=0.5",
    }
    last_error = None
    for attempt in range(1, 2):
        try:
            with requests.get(url, headers=headers, timeout=(15, 30), allow_redirects=True, stream=True) as r:
                r.raise_for_status()
                with dest.open("wb") as f:
                    for chunk in r.iter_content(1024 * 256):
                        if chunk:
                            f.write(chunk)
            if dest.stat().st_size < 3000:
                raise RuntimeError(f"download too small ({dest.stat().st_size} bytes)")
            if dest.read_bytes()[:5] != b"%PDF-":
                raise RuntimeError("download is not a PDF signature")
            pdf_info(dest)
            return
        except Exception as exc:
            last_error = exc
            if dest.exists():
                dest.unlink()
            time.sleep(attempt * 2)

    cmd = [
        "curl", "--http1.1", "-L", "--fail", "--retry", "2", "--retry-delay", "2", "--max-time", "60",
        "-A", headers["User-Agent"], "-H", "Accept: application/pdf,*/*;q=0.8",
        "-o", str(dest), url,
    ]
    try:
        subprocess.run(cmd, check=True, timeout=75)
        if dest.stat().st_size < 3000 or dest.read_bytes()[:5] != b"%PDF-":
            raise RuntimeError("curl fallback did not produce a valid PDF")
        pdf_info(dest)
        return
    except Exception as exc:
        if dest.exists():
            dest.unlink()
        raise RuntimeError(f"Failed to download original PDF: {url}\nrequests error: {last_error}\ncurl error: {exc}") from exc


def build_index(entries: list[dict], output: Path, st: dict):
    doc = Doc(str(output), "Dubbo eWaste NotebookLM Research Pack - Corrected Original Sources", "master index")
    story = [
        Paragraph("Dubbo eWaste NotebookLM Research Pack", st["title"]),
        Paragraph("<b>Corrected edition:</b> genuine original online PDFs are included as the actual publisher files, not one-page AI summaries.", st["body"]),
        Paragraph("<b>Composition:</b> exactly 100 PDFs - 1 master index, 44 full DubboEwaste repository documents, 55 original online PDFs.", st["body"]),
        Paragraph("<b>Generated:</b> 6 October 2026", st["meta"]),
        Spacer(1, 3 * mm),
        Paragraph("Contents", st["h1"]),
    ]
    for item in entries:
        source = item.get("source", "")
        pages = item.get("pages")
        page_text = f" | {pages} pages" if pages else ""
        story.append(
            Paragraph(
                f"<b>{item['number']:03d}</b> - {esc(item['title'])}<br/>"
                f"<font color='#555555'>{esc(item['kind'])}{esc(page_text)} | {esc(source)}</font>",
                st["index"],
            )
        )
    doc.build(story)


def main():
    register_fonts()
    st = styles()
    cfg = json.loads(CONFIG.read_text(encoding="utf-8"))
    repo_docs = cfg["repo_documents"]
    external = cfg["external_sources"]
    assert len(repo_docs) == 44, len(repo_docs)
    assert len(external) == 55, len(external)

    if PACK_ROOT.exists():
        shutil.rmtree(PACK_ROOT)
    PDF_DIR.mkdir(parents=True)
    DOWNLOAD_DIR.mkdir(parents=True)

    entries = []
    number = 2

    for source_path in repo_docs:
        source = ROOT / source_path
        if not source.exists():
            raise FileNotFoundError(source_path)
        filename = f"{number:03d}-repo-{slug(source_path)}.pdf"
        out = PDF_DIR / filename
        write_repo_pdf(source, out, source_path, st)
        pages, encrypted = pdf_info(out)
        entries.append({
            "number": number,
            "filename": filename,
            "title": source.stem.replace("-", " ").replace("_", " ").title(),
            "kind": "Full repository document",
            "source": source_path,
            "pages": pages,
            "encrypted": encrypted,
            "sha256": sha256(out),
        })
        number += 1

    failures = []
    tasks = []
    for source in external:
        title, url = source["title"], source["url"]
        filename = f"{number:03d}-original-{slug(title)}.pdf"
        tasks.append((number, title, url, filename))
        number += 1

    def fetch_original(task):
        n, title, url, filename = task
        temp = DOWNLOAD_DIR / filename
        out = PDF_DIR / filename
        print(f"Downloading {n:03d}: {title}", flush=True)
        download_pdf(url, temp)
        shutil.move(str(temp), str(out))
        pages, encrypted = pdf_info(out)
        return {
            "number": n,
            "filename": filename,
            "title": title,
            "kind": "Original publisher PDF",
            "source": url,
            "pages": pages,
            "encrypted": encrypted,
            "sha256": sha256(out),
            "bytes": out.stat().st_size,
        }

    with ThreadPoolExecutor(max_workers=20) as pool:
        future_map = {pool.submit(fetch_original, task): task for task in tasks}
        for future in as_completed(future_map):
            n, title, url, _ = future_map[future]
            try:
                entries.append(future.result())
                print(f"OK {n:03d}: {title}", flush=True)
            except Exception as exc:
                failures.append(f"{n:03d} {title} | {url} | {exc}")
                print(f"FAILED {n:03d}: {exc}", flush=True)

    if failures:
        raise RuntimeError("Original PDF download failures:\n" + "\n\n".join(sorted(failures)))

    entries.sort(key=lambda item: item["number"])

    index = PDF_DIR / "001-MASTER-INDEX-CORRECTED-ORIGINAL-SOURCES.pdf"
    all_entries = [{
        "number": 1,
        "filename": index.name,
        "title": "Dubbo eWaste NotebookLM Research Pack - Master Index",
        "kind": "Pack index",
        "source": "This repository",
    }] + entries
    build_index(all_entries, index, st)
    pages, encrypted = pdf_info(index)
    all_entries[0].update({"pages": pages, "encrypted": encrypted, "sha256": sha256(index)})

    pdfs = sorted(PDF_DIR.glob("*.pdf"))
    if len(pdfs) != 100:
        raise RuntimeError(f"Expected exactly 100 PDFs, got {len(pdfs)}")

    bad = []
    for pdf in pdfs:
        try:
            pages, _ = pdf_info(pdf)
            if pages < 1:
                bad.append(f"{pdf.name}: zero pages")
        except Exception as exc:
            bad.append(f"{pdf.name}: {exc}")
    if bad:
        raise RuntimeError("PDF validation failures:\n" + "\n".join(bad))

    MANIFEST_PATH.write_text(json.dumps({
        "pack_name": cfg["pack_name"],
        "generated": GENERATED,
        "source_commit": SOURCE_COMMIT,
        "pdf_count": len(pdfs),
        "repo_document_count": 44,
        "original_online_pdf_count": 55,
        "entries": all_entries,
    }, indent=2) + "\n", encoding="utf-8")

    README_PATH.write_text(
        "# Dubbo eWaste NotebookLM 100-PDF Research Pack - Corrected Edition\n\n"
        "This corrected pack contains exactly 100 PDFs:\n\n"
        "- 1 master index PDF\n"
        "- 44 full DubboEwaste repository documents converted to PDF\n"
        "- 55 genuine original online PDFs downloaded from their publishers\n\n"
        "**The external PDFs are the original source files. They are not AI-generated one-page summaries.**\n\n"
        "See manifest.json for source URLs, page counts and SHA-256 hashes.\n",
        encoding="utf-8",
    )

    with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for pdf in pdfs:
            zf.write(pdf, arcname=pdf.name)

    with zipfile.ZipFile(ZIP_PATH) as zf:
        members = [n for n in zf.namelist() if n.lower().endswith(".pdf")]
        if len(members) != 100:
            raise RuntimeError(f"ZIP must contain 100 PDFs, got {len(members)}")

    shutil.rmtree(DOWNLOAD_DIR, ignore_errors=True)
    original_pages = sum(int(e.get("pages", 0)) for e in entries if e["kind"] == "Original publisher PDF")
    total_pages = sum(int(e.get("pages", 0)) for e in all_entries)
    print(f"SUCCESS: 100 PDFs verified; {original_pages} pages from 55 original online PDFs; {total_pages} total pages.")
    print(f"ZIP: {ZIP_PATH} ({ZIP_PATH.stat().st_size / 1024 / 1024:.1f} MiB)")


if __name__ == "__main__":
    main()
