import Link from "next/link";
import { requireProgrammeContext } from "@/lib/programme-context";

type CountItem = { site?: string; event_name?: string; total?: number; page_group?: string;
  target_group?: string; country?: string; region?: string; device_class?: string };
type Report = {
  day_sydney: string; events_total: number;
  by_site: CountItem[]; pages: CountItem[]; clicks: CountItem[];
  locations: CountItem[]; devices: CountItem[];
};
function dayInSydney() {
  const entries = new Intl.DateTimeFormat("en-GB", {
    timeZone: "Australia/Sydney", year: "numeric", month: "2-digit", day: "2-digit"
  }).formatToParts(new Date());
  const part = (key: string) => entries.find(p => p.type === key)?.value || "";
  return part("year") + "-" + part("month") + "-" + part("day");
}
const n = (value: number | undefined) => Number(value || 0).toLocaleString("en-AU");
function TableSection({ title, items, name }: { title: string; items: CountItem[]; name: keyof CountItem }) {
  return <section className="card"><h2>{title}</h2>
    {items.length ? <div style={{overflowX:"auto"}}><table style={{width:"100%",textAlign:"left"}}>
      <thead><tr><th>Item</th><th>Site</th><th>Count</th></tr></thead>
      <tbody>{items.slice(0,30).map((v,i) => <tr key={i}>
        <td>{String(v[name] || "unknown")}</td><td>{v.site || "Both"}</td>
        <td>{n(v.total)}</td></tr>)}</tbody>
    </table></div> : <p>No events yet.</p>}</section>;
}
export default async function AnalyticsDashboard() {
  const { supabase, context } = await requireProgrammeContext();
  if (!context.global_admin) return <section className="card"><h1>Administrators only</h1>
    <p>Only global administrators can view cross-programme analytics.</p></section>;

  const anchor = dayInSydney();
  const days = Array.from({ length: 7 }, (_,i) => {
    const d = new Date(anchor + "T12:00:00Z");
    d.setUTCDate(d.getUTCDate() - i);
    return d.toISOString().slice(0,10);
  });
  const results = await Promise.all(days.map(async day => {
    const { data, error } = await supabase.rpc("analytics_daily_report", { p_day: day });
    return { day, data: (data || null) as Report | null, error };
  }));
  const today = results[0]?.data;
  return <div className="stack">
    <div><div className="badge">Administration</div><h1>Site analytics</h1>
      <p className="muted">DubboEwaste, Repair Café, Library of Things and Circular Economy.
      Approximate visits, clicks and sign-ins, in Sydney local dates. No visitor identities are stored.</p></div>
    <div className="grid">
      <section className="card"><h2>Events today</h2><div className="metric">{n(today?.events_total)}</div></section>
      <section className="card"><h2>Page views today</h2><div className="metric">{n(today?.by_site?.filter(r=>r.event_name==="page_view").reduce((a,r)=>a+Number(r.total||0),0))}</div></section>
      <section className="card"><h2>Clicks today</h2><div className="metric">{n(today?.by_site?.filter(r=>r.event_name==="click").reduce((a,r)=>a+Number(r.total||0),0))}</div></section>
      <section className="card"><h2>Successful logins today</h2><div className="metric">{n(today?.by_site?.filter(r=>r.event_name==="login_success").reduce((a,r)=>a+Number(r.total||0),0))}</div></section>
    </div>
    <section className="card"><h2>Last seven days</h2>
      <div style={{overflowX:"auto"}}><table style={{width:"100%",textAlign:"left"}}>
        <thead><tr><th>Sydney date</th><th>Visits</th><th>Clicks</th><th>Sign-ins</th></tr></thead>
        <tbody>{results.map(({day,data}) => <tr key={day}>
          <td>{day}</td>
          {(["page_view","click","login_success"] as const).map(event => <td key={event}>{n(data?.by_site?.filter(row=>row.event_name===event).reduce((sum,row)=>sum+Number(row.total||0),0))}</td>)}
        </tr>)}</tbody>
      </table></div>
      {results.some(r=>r.error) ? <p role="alert">Some data could not be loaded. Check the analytics migration and administrator permissions.</p> : null}
    </section>
    <TableSection title="Today's most visited sections" items={today?.pages || []} name="page_group" />
    <TableSection title="Today's most clicked links and actions" items={today?.clicks || []} name="target_group" />
    <TableSection title="Today's visitor country/state (approximate)" items={today?.locations || []} name="country" />
    <TableSection title="Today's device types" items={today?.devices || []} name="device_class" />
    <section className="card"><h2>How reports work</h2>
      <p>Individual visitors cannot be identified from this dashboard. A visit is a page-view event,
      not necessarily a unique person. Browser privacy settings can prevent tracking.</p>
      <p>Daily GitHub summaries are generated by a scheduled workflow after its GitHub Actions
      secrets are configured. Raw records do not go into GitHub.</p>
      <p><Link href="/privacy-analytics">Analytics privacy information</Link></p>
    </section>
  </div>;
}
