/* Hand-written learning content. Facts come from the DubboEwaste repo and the
   research notes Josh supplied; anything unverified is labelled as such.
   Link shapes: {t, u} external, {t, doc} repo doc id, {t, q} web search. */
const C = {};

C.pipeline = [
  ["Source", "Source equipment", "Prefer fleet refreshes from businesses, schools, MSPs and community organisations. Ten similar ex-business laptops are easier to serialise, wipe, test, repair and sell than ten random household devices."],
  ["Authority", "Prove authority and ownership", "Record who is handing the item over and on what basis (donation, sale, client-owned for service). Refuse suspicious or disputed provenance. If the NSW second-hand dealer regime applies, supplier ID and an ownership statement are required."],
  ["Record", "Assign an asset and serial record", "Every significant item gets an asset ID tied to its serial or IMEI before anything else happens. The 47-field pilot tracker starts here."],
  ["Safety", "Safety triage", "Screen for swollen, punctured, wet, fire-affected or hot batteries before power-on. Refuse loose lithium, CRTs and contaminated gear in Phase 0. Never charge a questionable battery."],
  ["Data", "Secure data sanitisation", "Follow a documented program aligned to NIST SP 800-88 Rev. 2 and the ASD ISM media guidelines. Log method, tool and version, verification and PASS / FAIL / DESTROY. If you can't verify the wipe, don't sell the storage."],
  ["Grade", "Test and grade", "Run bounded tests: memory, storage health, display, ports, battery, wireless, thermals. Record actual output. Deployment-ready means more than 'powers on'."],
  ["Reuse", "Reuse as-is where possible", "Whole-device value is the business. A working business laptop can be worth hundreds of dollars and becomes scrap metal, glass and PCB feedstock once it enters a recycling cage."],
  ["Repair", "Repair or refurbish where it pays", "Stop at a time, parts and safety ceiling. Measure gross margin per labour hour, not headline sale price."],
  ["Route", "Redeploy, resell or donate", "Commercial resale funds the operation. Lower-value but useful devices can go to trusted community partners for social reuse."],
  ["Parts", "Harvest parts if whole-device reuse fails", "RAM, SSDs, chargers and screens feed other repairs. Record what is left."],
  ["Recycle", "Recycle only the genuine remainder", "Send end-of-life material to a verified route (NTCRS scheme, MobileMuster, a named recycler) and keep the weight ticket or certificate."],
];

C.streams = [
  ["Commercial reuse", "Business, school or MSP retires devices → collect and inventory → ownership transfer → sanitise → test and grade → refurbish → resale or redeploy → client outcome report."],
  ["Social reuse", "Useful device with lower commercial value → sanitise, test, configure → trusted local charity or community partner → partner picks the recipient → skills and connectivity support where available."],
  ["Donor parts", "Whole device fails economic repair → harvest useful components → repair other equipment → record the remaining material."],
  ["End of life", "No meaningful whole or parts value → verified recycler or product-stewardship route → keep the weight ticket, certificate or receipt."],
];

C.takeaways = [
  ["Reuse before recycling is the opportunity", "Council, Officeworks, AMR and the regional NTCRS routes already handle disposal. The gap is earlier: identify the useful device, protect the data, refurbish, recover the whole-device value, and recycle last. Sircel, PonyUp, Reconnect, Compnow, WorkVentures and the National Device Bank all point the same way.", "SIRCEL-ITAD-REUSE-MODEL"],
  ["Triage is the highest-value operation", "The most valuable decision is 'is this actually end-of-life?' before anything goes into an e-waste cage. TechCollect says equipment surrendered into its stream is recycled in Australia and not sold second-hand.", "TECHCOLLECT-REUSE-DEEP-DIVE"],
  ["Corporate fleets beat random household e-waste", "Fleet-refresh gear is easier to identify, wipe, test, repair, image and sell. Target businesses, schools, professional offices, MSPs and community organisations. Keep household intake selective.", "GOOD360-COMPNOW-NATIONAL-DEVICE-BANK-DUBBO"],
  ["Data security is a differentiator", "Business clients want chain of custody, serials, sanitisation, verification, failed-erase escalation and a final outcome. Use the wording 'documented secure data erasure' until a certified process supports stronger claims.", "BACKLOG-21-25-COMPLIANCE-DATA-SAFETY"],
  ["Commercial resale and social reuse support each other", "Higher-value stock can be resold to pay for wiping, repairs, chargers and logistics, which then funds lower-value social devices. Run four streams: commercial, social, parts, recycling.", "GOOD360-COMPNOW-NATIONAL-DEVICE-BANK-DUBBO"],
  ["'We take e-waste' isn't a value proposition in Dubbo", "Dubbo already has Council drop-off, Officeworks, AMR, repairers and NetWaste routes. A stronger pitch: before you recycle old IT, we work out what still has value, protect the data, reuse what's viable and document what happened to the rest.", "BACKLOG-17-20-MARKET-COST-TAX"],
  ["Planning classification is the biggest barrier, not EPA tonnage", "A 20–30 device pilot is nowhere near EPA licensing thresholds, but being under a threshold doesn't create planning permission. Is it a home business, home industry, goods repair and reuse premises, or a waste activity? Council has to answer in writing.", "BACKLOG-01-05-PLANNING-LEGAL"],
  ["Launch tiny, selective and reversible", "Tuesday and Saturday by appointment, no public dumping, only items with a known exit, no loose lithium or CRTs, shelf limits, online sales. Copy Bendigo E-Waste's growth sequence, not its current warehouse.", "PHASE-0-OPERATING-BLUEPRINT"],
  ["The downstream chain is still opaque", "No public evidence proves where AMR Dubbo sends e-waste next. Sircel, ACE, Sims and TechCollect are candidates only. It stays 'unknown' until a written answer, transport document or certificate closes it.", "AMR-DUBBO-DOWNSTREAM-FORENSIC"],
  ["Pilot data now matters more than more research", "The real unknowns are empirical: local supply, reuse rate, repair time, sale price, days to sale, liability rate, recycling cost, gross margin per labour hour. The pilot tracker answers them.", "pilot-tracker.csv"],
];

C.gates = [
  ["Council classification", "Get Dubbo Regional Council's written answer on how the exact activity is classified on the proposed site."],
  ["Lease and workspace suitability", "Planning and lease permission are separate gates. The shed must be demonstrably dry and secure before it holds stock or unwiped drives."],
  ["Fair Trading answer", "Does the second-hand dealer regime apply, or the recycling-program exemption? Can you wipe during a 14-day hold? Get it in writing."],
  ["Insurance", "Public and product liability for a home electronics refurb, including lithium conditions. Quote required. Don't guess the premium."],
  ["Verified downstream terms", "A named, written route for the non-reusable remainder, with certificates or weight tickets."],
  ["Small selective pilot", "Pre-approved Tuesday/Saturday intake, shelf limits, online sales."],
  ["Measure 20–30 devices", "Log every item in the pilot tracker: labour, parts, days in stock, sale price, outcome."],
  ["Only then widen intake or spend", "Lease bigger space only when supply is consistent, stock turns, labour pays and storage is the real constraint."],
];

C.unknowns = [
  ["Can the home-site Phase 0 model run lawfully and safely?", "Council classification, site planning confirmation, landlord position, a dry and secure workspace, insurer acceptance. This is the main go/no-go gate."],
  ["Does the NSW second-hand dealer regime apply?", "The recycling-program exemption, donated or free equipment, the 14-day hold, whether wiping or repair counts as alteration."],
  ["Where does the non-reusable material physically go?", "AMR Dubbo, Council's post-June-2025 contractor, embedded lithium, NTCRS, AS 5377, CRTs, certificates, drive destruction."],
  ["Is there enough profitable good equipment in Dubbo?", "Only the pilot can answer: supply quality, reuse rate, repair success, labour, margins, shelf time, returns."],
  ["Which organisations will actually partner?", "Dubbo Support Center, Good Things, WorkVentures, Good360, the Device Banks, ANZRP, councils, local MSPs. Who says yes, in what role, at what volume?"],
];

C.dontClaim = [
  "AMR Dubbo sends e-waste to Sircel, ACE, Sims or Rutherford",
  "AMR Dubbo is a current TechCollect collection partner",
  "Officeworks Dubbo is an industrial recycler",
  "Every Dubbo Council e-waste load follows the old Matthews/Sims route",
  "Sircel sends all reused assets through Good360",
  "Dubbo Support Center is already a Device Bank distribution site",
  "The proposed home site is approved for the business",
  "The second-hand dealer exemption definitely applies",
  "'NIST certified' or 'certified data destruction' without a certified provider",
];

/* ---------- Flow map ---------- */
C.flowCols = ["Who has it", "Handover point", "Next stop", "What it becomes"];
C.flowNodes = [
  {id: "households", col: 0, c: "v", t: "Dubbo households", s: "Old laptops, phones, TVs", d: "Residents can drop household e-waste at Whylandra free, use Officeworks trade-in or Bring it Back, or take it to AMR. Most of it is disposal, not reuse.", docs: ["WHAT-HAPPENS-TO-EWASTE"]},
  {id: "business", col: 0, c: "v", t: "Businesses, MSPs, offices", s: "Fleet refreshes", d: "4,500+ businesses in the Dubbo catchment (local business sources). Fleet gear is the best reuse supply. Today it goes to AMR, national ITAD firms or sits in storerooms.", docs: ["FLIPTECH-DUBBO-BRANCH-FEASIBILITY"]},
  {id: "schools", col: 0, c: "v", t: "NSW public schools", s: "Department laptops", d: "Public schools use a separate Department of Education eWaste process through EDConnect and a contracted vendor, not Council or AMR.", docs: ["NSW-EDUCATION-EWASTE-DUBBO-LAPTOPS"]},
  {id: "councils", col: 0, c: "v", t: "Surrounding councils", s: "NetWaste members", d: "NetWaste says Sims Metal Management collects e-waste from most member councils. Some councils have their own arrangements: Parkes Shire uses Sircel.", docs: ["REGIONAL-EWASTE-PATHWAYS", "BACKLOG-13-16-REGIONAL-SUPPLY"]},
  {id: "whylandra", col: 1, c: "v", t: "Whylandra Waste and Recycling Centre", s: "Council CRC · free for residents", d: "Dubbo Regional Council's facility takes household e-waste (anything with a cord or battery) free. It is a Community Recycling Centre and an NTCRS participant via DHL Drop Zone. The research notes it operates under EPL 6058. A separate commercial fee schedule exists; the business e-waste rate is unknown.", docs: ["BACKLOG-06-12-DOWNSTREAM-STEWARDSHIP"], links: [{t: "Whylandra page", u: "https://www.dubbo.nsw.gov.au/Households-Residents/Rubbish-Recycling-and-Sustainability/whylandra-waste-recycling-centre"}, {t: "Council A–Z recycling guide", u: "https://www.dubbo.nsw.gov.au/Households-Residents/Rubbish-Recycling-and-Sustainability/Domestic-Waste-Services/a-z-recycling"}]},
  {id: "officeworks", col: 1, c: "v", t: "Officeworks Dubbo", s: "Trade-in and Bring it Back", d: "A retail trade-in and technology collection channel at 10 Erskine Street. It is not a local recycler or processor, and not every national category is necessarily accepted locally. Officeworks stopped in-store battery collection in February 2024.", docs: ["BACKLOG-17-20-MARKET-COST-TAX"]},
  {id: "amr", col: 1, c: "v", t: "Australian Metal Recycling", s: "34 Mountbatten Drive · free e-waste", d: "Operated by Scrap Metal Services Pty Ltd (AMR), formerly Matthews Metal Management. Advertises free e-waste recycling for TVs, computers, monitors, phones, tablets and printers, but its materials list says 'excluding lithium ion'. Its published equipment looks like collection, sorting and consolidation, not a specialist dismantling line. It isn't evidenced as a secure data-destruction service.", docs: ["MATTHEWS-INFRABUILD-AMR", "AMR-DUBBO-DOWNSTREAM-FORENSIC"]},
  {id: "dew", col: 1, c: "p", t: "Dubbo eWaste (proposed)", s: "Reuse-first triage", d: "The proposed business sits before the destructive stream: prove ownership, sanitise, test, reuse or refurbish, harvest parts, and only then send the remainder to a verified recycler.", docs: ["PHASE-0-OPERATING-BLUEPRINT", "INTAKE-POLICY"]},
  {id: "edconnect", col: 1, c: "v", t: "Education eWaste vendor", s: "EDConnect / eWaste PowerApp", d: "The vendor schedules regional collection, sanitises all collected hard drives, and issues a sanitisation certificate and a Settlement Report. Who the vendor is and what happens to the laptops next is not public.", docs: ["NSW-EDUCATION-EWASTE-DUBBO-LAPTOPS"]},
  {id: "itad", col: 1, c: "v", t: "National ITAD firms", s: "Fliptech, G1, Greenbox, WV…", d: "Secure collection, erasure, asset reporting, buyback and remarketing, mostly run from capital-city sites. None has an announced Dubbo branch.", docs: ["DUBBO-ITAD-BRANCH-ENTRY-PLAYBOOK"]},
  {id: "matthews", col: 2, c: "h", t: "Matthews Metals contract", s: "Historical · expired 30 June 2025", d: "Council's 2025–2035 Waste Strategy and a 2025 NSW Planning study named Matthews Metals in Dubbo as the e-waste processor. Council's listed Matthews e-waste contract expired on 30 June 2025. Coonamble documented a 2025 route to Matthews Dubbo. Historical Matthews records show NTCRS involvement and a TechCollect-linked scope.", docs: ["WHAT-HAPPENS-TO-EWASTE"]},
  {id: "unknown", col: 2, c: "u", t: "AMR's first downstream recipient", s: "Unknown · no public evidence", d: "No public source names the facility that receives AMR Dubbo's e-waste next. This stays unknown until AMR names its processor in writing, or a transport document, certificate or contract shows it. Questions to ask are in the call scripts.", docs: ["AMR-DUBBO-DOWNSTREAM-FORENSIC", "CALL-SCRIPTS"]},
  {id: "sircel", col: 2, c: "v", t: "Sircel, Parkes", s: "Triage, Blancco, R2v3", d: "Directly evidenced for Parkes Shire. The strongest regional candidate for AMR's route, but unproven. Sircel reported 2,350 reused assets in FY2023-24, and it entered receivership or voluntary administration in late 2025, so don't depend on it without current confirmation.", docs: ["SIRCEL-ITAD-REUSE-MODEL"]},
  {id: "sims", col: 2, c: "v", t: "Sims Metal Management", s: "Most NetWaste councils", d: "NetWaste currently says Sims collects e-waste from the majority of member councils. Historical regional contracts described shredding at St Marys. There's no evidence this is AMR's current route.", docs: ["REGIONAL-EWASTE-PATHWAYS"]},
  {id: "techcollect", col: 2, c: "v", t: "NTCRS recyclers (TechCollect / ANZRP)", s: "ACE Recycling, Sircel in NSW", d: "TechCollect's current NSW recyclers include ACE Recycling Group and Sircel. Equipment surrendered into its stream is recycled in Australia and not resold. Its public collection-partner list doesn't name AMR, Matthews or Dubbo.", docs: ["TECHCOLLECT-REUSE-DEEP-DIVE"]},
  {id: "materials", col: 3, c: "v", t: "Separated materials", s: "Steel, Al/Cu, PCBs, plastic, glass", d: "The usual Australian chain: dismantle or shred, then separate steel, aluminium and copper, glass, plastics, batteries, PCBs and toner, and send each to specialist processors. Some fractions such as PCBs go to approved overseas refiners. Since 1 January 2025 the Basel Convention also controls non-hazardous e-waste like PCBs and CRTs.", docs: ["WHAT-HAPPENS-TO-EWASTE"], links: [{t: "Control of e-waste exports (DCCEEW)", u: "https://www.dcceew.gov.au/environment/protection/hazardous-waste/control-e-waste"}]},
  {id: "batteries", col: 3, c: "v", t: "Battery stream", s: "B-cycle, specialist handlers", d: "Lithium batteries are removed and handled separately. They're the likely leading cause of fires at waste and resource recovery facilities. AMR doesn't accept lithium-ion.", docs: ["BACKLOG-06-12-DOWNSTREAM-STEWARDSHIP"]},
  {id: "reuse", col: 3, c: "p", t: "Reuse outcomes", s: "Resale, redeploy, donate, parts", d: "Whole devices resold, redeployed to the client, donated through community partners, or harvested for parts. This is the outcome the recycling stream destroys.", docs: ["GOOD360-COMPNOW-NATIONAL-DEVICE-BANK-DUBBO"]},
  {id: "landfill", col: 3, c: "v", t: "Residual to landfill", s: "Unavoidable losses", d: "NTCRS annual reports show 'recycled' doesn't mean 100% becomes new product. High recovery rates still include residual landfill and downstream losses.", docs: ["WHAT-HAPPENS-TO-EWASTE"]},
];
C.flowEdges = [
  ["households", "whylandra", "v"], ["households", "officeworks", "v"], ["households", "amr", "v"], ["households", "dew", "p"],
  ["business", "amr", "u"], ["business", "itad", "v"], ["business", "dew", "p"],
  ["schools", "edconnect", "v"],
  ["councils", "sims", "v"], ["councils", "sircel", "v"],
  ["whylandra", "matthews", "h"], ["whylandra", "unknown", "u"],
  ["amr", "unknown", "u"],
  ["edconnect", "reuse", "u"], ["edconnect", "materials", "u"],
  ["itad", "reuse", "v"], ["itad", "materials", "v"],
  ["dew", "reuse", "p"], ["dew", "techcollect", "p"],
  ["matthews", "techcollect", "h"],
  ["unknown", "sircel", "u"], ["unknown", "sims", "u"], ["unknown", "techcollect", "u"],
  ["sircel", "reuse", "v"], ["sircel", "materials", "v"],
  ["sims", "materials", "v"],
  ["techcollect", "materials", "v"], ["techcollect", "batteries", "v"], ["techcollect", "landfill", "v"],
];
C.flowConf = {v: ["ok", "Evidenced"], h: ["warn", "Historical"], u: ["bad", "Unproven or unknown"], p: ["cu", "Proposed"]};

/* ---------- Rules ---------- */
C.layers = [
  {t: "Federal", items: [
    {t: "National Television and Computer Recycling Scheme (NTCRS)", st: ["ok", "Verified"],
      req: "Importers and manufacturers of TVs and computers fund collection and recycling through approved co-regulatory arrangements. Recycling targets rise to 80% in 2026–27.",
      who: "Liable parties and co-regulators such as ANZRP (TechCollect). Collection points like Whylandra take part. A small refurbisher isn't a liable party, but can feed genuine end-of-life gear into the scheme.",
      unsure: "Whether AMR Dubbo's free service is NTCRS-funded and through which arrangement. Whether the reviews will change the scheme.",
      links: [{t: "DCCEEW: NTCRS", u: "https://www.dcceew.gov.au/environment/protection/waste/product-stewardship/products-schemes/television-computer-recycling-scheme"}, {t: "Co-regulatory arrangements", u: "https://www.dcceew.gov.au/environment/protection/waste/product-stewardship/products-schemes/television-computer-recycling-scheme/coreg-arrangements"}, {t: "NTCRS operational review", q: "NTCRS operational review National Television and Computer Recycling Scheme"}]},
    {t: "Recycling and Waste Reduction Act 2020 (and the Product Stewardship Act 2011)", st: ["warn", "Secondary source"],
      req: "The federal framework for product stewardship and waste export controls. Your research found that the 2020 Act replaced the Product Stewardship Act 2011, which the NTCRS was created under.",
      who: "Scheme administrators, liable parties, and anyone exporting regulated waste.",
      unsure: "The replacement claim rests on a secondary source. Confirm it on legislation.gov.au and read the 2020 review of the Product Stewardship Act.",
      links: [{t: "Search the federal register", q: "legislation.gov.au Recycling and Waste Reduction Act 2020"}, {t: "Review of the Product Stewardship Act 2011", q: "Review of the Product Stewardship Act 2011 including NTCRS"}]},
    {t: "Small electricals and solar PV scheme", st: ["info", "In development"],
      req: "The government has committed to a mandatory scheme for small electrical products and solar PV systems. ANZRP says solar is being prioritised first.",
      who: "Future liable parties. It could widen what a small reuse operator can route through a funded scheme.",
      unsure: "Timing and scope.",
      links: [{t: "ANZRP e-stewardship", u: "https://www.anzrp.com.au/about/e-stewardship/"}, {t: "Minister's priority list", q: "DCCEEW Minister's product stewardship priority list"}]},
  ]},
  {t: "NSW environment law", items: [
    {t: "POEO Act and Environment Protection Licences", st: ["ok", "Verified"],
      req: "An EPL is needed for scheduled activities above set thresholds. Section 143 makes it an offence to take waste to a place that can't lawfully receive it. Since the 2025 amendments, licence obligations can't be delegated to contractors.",
      who: "Waste facilities and resource recovery above thresholds. Section 143 applies to anyone moving waste, including your leftovers.",
      unsure: "Whether the scheduled-activity amendments that commenced on 29 May 2026, or the 2025 private member's bill to make receiving over 100 tonnes of e-waste a year a scheduled activity, change anything. The bill's status is unconfirmed.",
      links: [{t: "EPA: licensing thresholds", u: "https://www.epa.nsw.gov.au/Your-environment/Waste/waste-overview/licensing/reduced-licensing-thresholds"}, {t: "EPA Guide to Licensing", q: "NSW EPA guide to licensing environment protection licence"}, {t: "EPA: what's new in law", q: "NSW EPA what's new in law 2026"}, {t: "Planning and legal research", doc: "BACKLOG-01-05-PLANNING-LEGAL"}]},
    {t: "WARR Act 2001", st: ["ok", "Background"],
      req: "Sets NSW's waste-hierarchy objectives: avoid, reuse, recycle, then dispose. It underpins the state's waste strategy and resource recovery framework.",
      who: "Mostly policy and government programs rather than a small operator directly.",
      unsure: "Which instruments made under it matter for a refurbisher.",
      links: [{t: "NSW legislation", u: "https://legislation.nsw.gov.au/"}, {t: "Resource recovery framework", u: "https://www.epa.nsw.gov.au/Your-environment/Recycling-and-reuse/resource-recovery-framework"}]},
    {t: "Waste classification and tracking", st: ["ok", "Verified"],
      req: "Whoever generates waste must classify it into one of six classes. Hazardous waste tracking sits under Part 4 of the POEO (Waste) Regulation 2014.",
      who: "You, for any leftover material you send downstream.",
      unsure: "Whether damaged lithium batteries in your hands count as hazardous waste for storage. Ask the EPA.",
      links: [{t: "Waste Classification Guidelines Part 1", q: "NSW EPA Waste Classification Guidelines Part 1 classifying waste"}, {t: "Waste that must be tracked", u: "https://www.epa.nsw.gov.au/Your-environment/Waste/tracking-transporting-hazardous-waste/waste-must-tracked"}]},
    {t: "Product Lifecycle Responsibility Act 2025 and Regulation 2026", st: ["warn", "Secondary source"],
      req: "A new NSW product stewardship framework. The first regulation targets batteries. Your research found it was promulgated on 20 February 2026 with a start date of 1 October 2026.",
      who: "Mainly suppliers and retailers of batteries and battery products.",
      unsure: "The start date rests on secondary sources. Check whether anything applies to a small refurbisher who resells devices with embedded batteries.",
      links: [{t: "EPA battery reform announcement", u: "https://www.epa.nsw.gov.au/news/epamedia/260407-nsw-leads-the-country-in-battery-reform-to-fight-fires-and-pollution"}, {t: "Product Lifecycle Responsibility Regulation 2026", q: "NSW Product Lifecycle Responsibility Regulation 2026 batteries EPA"}]},
  ]},
  {t: "Standards and certification", items: [
    {t: "AS 5377:2022", st: ["ok", "Verified"],
      req: "Collection, storage, transport and treatment of end-of-life electrical and electronic equipment. It replaced AS/NZS 5377:2013 in Australia; the 2013 edition stays current in New Zealand. WA's e-waste landfill ban regulations reference the 2022 edition.",
      who: "Recyclers working under NTCRS contracts and corporate or government tenders. It's a standard, not a blanket legal mandate. It becomes mandatory in practice through contracts and client requirements.",
      unsure: "Whether a refurb-only operation would ever need it, and what certification costs.",
      links: [{t: "Standards Australia store", q: "Standards Australia AS 5377:2022"}, {t: "Total Green Recycling accreditation example", q: "Total Green Recycling AS/NZS 5377 accreditation"}]},
    {t: "JAS-ANZ, R2v3 and e-Stewards", st: ["ok", "Background"],
      req: "JAS-ANZ accredits the certification bodies that audit against standards like AS 5377. R2 and e-Stewards are international responsible-recycling certifications. Sircel is R2v3 certified.",
      who: "Operators who want certification to win corporate and government work.",
      unsure: "Which certification local clients actually ask for.",
      links: [{t: "Sircel R2v3 announcement", u: "https://sircel.com/2024/09/03/sircel-is-r2v3-certified/"}, {t: "JAS-ANZ register", q: "JAS-ANZ register AS 5377 certification"}]},
  ]},
  {t: "Exports", items: [
    {t: "Basel Convention and export permits", st: ["ok", "Verified"],
      req: "Exporting hazardous e-waste needs a permit. From 1 January 2025, Basel controls also cover non-hazardous e-waste; printed circuit boards and CRTs are the examples given.",
      who: "Anyone exporting, including the recyclers your leftovers go to. A Melbourne recycler was fined almost $20,000 after undeclared e-waste, including circuit boards and lithium batteries, was found in a container bound for Singapore.",
      unsure: "Where AMR's fractions end up, and whether any are exported.",
      links: [{t: "Control of e-waste exports", u: "https://www.dcceew.gov.au/environment/protection/hazardous-waste/control-e-waste"}, {t: "Melbourne recycler fine", q: "Melbourne e-waste recycler fined Singapore shipment circuit boards"}]},
  ]},
  {t: "Data", items: [
    {t: "NIST SP 800-88 Rev. 2", st: ["ok", "Verified"],
      req: "Published September 2025, superseding Rev. 1. It focuses on running a media sanitisation program and points to current technique standards instead of describing techniques itself. Sanitisation levels are Clear, Purge and Destroy.",
      who: "Guidance for your program. It is not a product certification scheme, so be wary of 'NIST certified' claims.",
      unsure: "Which tools and verification steps you'll document for each media type.",
      links: [{t: "NIST SP 800-88 Rev. 2", u: "https://csrc.nist.gov/pubs/sp/800/88/r2/final"}, {t: "Bench toolkit research", doc: "claudegaps-research~03-BENCH-TOOLKIT"}]},
    {t: "ASD Information Security Manual: guidelines for media", st: ["ok", "Verified"],
      req: "The Australian Government's guidance on media sanitisation and destruction. Use it as the Australian reference next to NIST.",
      who: "Government and anyone who chooses to align with it. Useful for government and school clients.",
      unsure: "How strictly local clients expect you to follow it.",
      links: [{t: "ISM: guidelines for media", u: "https://www.cyber.gov.au/business-government/asds-cyber-security-frameworks/ism/cyber-security-guidelines/guidelines-for-media"}, {t: "Dispose of a device securely", u: "https://www.cyber.gov.au/protect-yourself/securing-your-devices/how-secure-your-device/how-dispose-your-device-securely"}]},
    {t: "Privacy Act and notifiable data breaches", st: ["info", "To research"],
      req: "Client devices hold personal information. Learn the Privacy Act basics and the Notifiable Data Breaches scheme.",
      who: "Whether the Australian Privacy Principles apply to a small operator depends on turnover and activities. Check with the OAIC.",
      unsure: "Your obligations if an unwiped drive leaks.",
      links: [{t: "OAIC: small business and privacy", q: "OAIC small business Privacy Act who is covered"}]},
  ]},
  {t: "Batteries and safety", items: [
    {t: "SafeWork NSW lithium-ion guidance and WHS", st: ["ok", "Verified"],
      req: "A PCBU must assess and control lithium battery risks. From 1 July 2026, NSW WHS Codes of Practice carry more weight as the minimum standard expected of a PCBU.",
      who: "You, as soon as you run a business with batteries on site.",
      unsure: "What an insurer and a WHS adviser will require for your exact set-up.",
      links: [{t: "SafeWork NSW: lithium-ion batteries", u: "https://www.safework.nsw.gov.au/hazards-a-z/lithium-ion-batteries"}, {t: "EPA: embedded batteries", u: "https://www.epa.nsw.gov.au/Your-environment/Recycling-and-reuse/household-recycling-overview/embedded-batteries"}]},
    {t: "Fire evidence", st: ["ok", "Verified"],
      req: "Victoria's report on fires at waste and resource recovery facilities found lithium-ion batteries are likely the leading cause. The NSW EPA has inspected e-waste and battery storage sites. A national end-of-life lithium battery guideline from the Heads of EPA has been out for consultation.",
      who: "Everyone storing e-waste.",
      unsure: "What the final national guideline will require. WMRR's 15 May 2026 submission shows industry's critique.",
      links: [{t: "Victorian fires report", q: "Fires at waste and resource recovery facilities report Victoria lithium"}, {t: "WMRR submission on the EOL lithium battery guideline", q: "WMRR submission National Guideline end-of-life lithium batteries 2026"}]},
    {t: "B-cycle", st: ["ok", "Verified"],
      req: "The national battery stewardship scheme. Becoming a drop-off point means registering and taking on much more operational control than putting out a bin.",
      who: "Battery collection sites. Phase 0 shouldn't offer public battery collection.",
      unsure: "Whether B-cycle could take the occasional battery you remove.",
      links: [{t: "B-cycle", u: "https://bcycle.com.au/"}, {t: "Never bin a battery (EPA)", u: "https://www.epa.nsw.gov.au/Your-environment/Recycling-and-reuse/never-bin-a-battery"}]},
  ]},
  {t: "Trading and consumer law", items: [
    {t: "NSW second-hand dealer licence", st: ["ok", "Verified"],
      req: "Needed to buy, sell or exchange prescribed goods, which include electronic goods. Fees for 2026–27: $692 for 1 year, $1,574 for 3 years, $2,456 for 5 years. Renewals from $500. Duties: notify business and storage premises, display signs, check supplier ID, get an ownership statement, keep electronic records reported to police within 3 days, and hold goods 14 days without altering them.",
      who: "The licence belongs to the legal entity, not a brand. No licence is needed to 'engage in recycling and rubbish collection programs'.",
      unsure: "Whether free collection → refurbish → resell → recycle counts as that exemption. Whether wiping or repair counts as altering goods during the hold.",
      links: [{t: "Fair Trading: dealer licences", u: "https://www.nsw.gov.au/business-and-economy/running-a-business/industry-specific-business-requirements/pawnbrokers-and-second-hand-dealers/pawnbroker-and-second-hand-dealer-licences"}, {t: "Fees", u: "https://www.nsw.gov.au/business-and-economy/running-a-business/industry-specific-business-requirements/pawnbrokers-and-second-hand-dealers/pawnbrokers-and-second-hand-dealers-fees"}, {t: "Licensing research", doc: "LEGAL-LICENSING"}]},
    {t: "Australian Consumer Law", st: ["ok", "Verified"],
      req: "Consumer guarantees apply to second-hand goods a business sells. 'As is' or 'no refunds' can't remove statutory rights, but a defect you clearly point out before sale isn't covered by the acceptable-quality guarantee. Repair notices with prescribed wording matter for customer devices.",
      who: "Every business sale.",
      unsure: "Your warranty and returns policy, and how you'll record known faults.",
      links: [{t: "Selling safe second-hand products", u: "https://www.productsafety.gov.au/business/know-how-to-sell-safe-products/how-to-sell-safe-second-hand-products-online"}, {t: "Compliance research", doc: "BACKLOG-21-25-COMPLIANCE-DATA-SAFETY"}]},
    {t: "Business registrations and tax", st: ["ok", "Verified"],
      req: "An ABN is free. A business name costs $47 for 1 year or $108 for 3. GST registration is compulsory at $75,000 turnover. Scrap-metal registration ($260 for 3 years) applies only if you actually deal in scrap metal.",
      who: "You, once you trade.",
      unsure: "Sole trader or company. Second-hand goods GST treatment later on.",
      links: [{t: "ATO: registering for GST", u: "https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/registering-for-gst"}, {t: "Register a business name", u: "https://business.gov.au/registrations/register-your-business-name"}]},
  ]},
  {t: "Local: Dubbo", items: [
    {t: "Council planning", st: ["warn", "Gating question"],
      req: "NSW home-business rules allow low-impact home businesses. Dubbo's LEP caps home-business floor area at 30 m². The proposed site is likely zoned R2 Low Density Residential, which isn't confirmed. A goods repair and reuse premises or a waste facility is a different, possibly prohibited, use.",
      who: "The exact activity on the exact site. Classification depends on what you actually do, not the business name.",
      unsure: "Council's written classification. Whether Tuesday/Saturday intake by appointment changes it.",
      links: [{t: "Do I need a DA?", u: "https://www.dubbo.nsw.gov.au/Builders-Developers/Overview-of-Application-Process/do-i-need-a-da"}, {t: "Dubbo LEP 2022", u: "https://legislation.nsw.gov.au/view/html/inforce/current/epi-2022-0617"}, {t: "Planning research", doc: "BACKLOG-01-05-PLANNING-LEGAL"}]},
    {t: "Council waste services", st: ["ok", "Verified"],
      req: "Free household e-waste at Whylandra. Council also publishes a commercial fee schedule. Free household drop-off means household gate fees are unlikely; your read is that any business has to come from commercial IT, refurb and data destruction (an inference to test).",
      who: "Residents (free), businesses (fees).",
      unsure: "The commercial e-waste rate, and who Council's e-waste contractor has been since June 2025.",
      links: [{t: "Council waste facilities", u: "https://www.dubbo.nsw.gov.au/Households-Residents/Rubbish-Recycling-and-Sustainability/council-waste-facilities"}, {t: "A–Z recycling", u: "https://www.dubbo.nsw.gov.au/Households-Residents/Rubbish-Recycling-and-Sustainability/Domestic-Waste-Services/a-z-recycling"}]},
  ]},
];

C.fixes = [
  ["AS/NZS 5377:2013 is the Australian standard", "AS 5377:2022 replaced it in Australia; 2013 stays current in NZ"],
  ["Use NIST SP 800-88 Rev. 1", "Rev. 2 (September 2025) supersedes it and is program guidance, not certification"],
  ["The NTCRS sits under the Product Stewardship Act 2011", "Research says the Recycling and Waste Reduction Act 2020 replaced it. Verify on legislation.gov.au"],
  ["AS/NZS 5377 is legally mandatory", "It's a standard. It becomes mandatory through contracts, NTCRS arrangements and clients"],
  ["You need an EPL to start", "It depends on scheduled-activity thresholds. A small refurb and data operation may not trigger one. Ask the EPA"],
  ["eBay takes roughly 13%", "Eligible AU sellers under $25,000 trailing sales pay no final value fee. The threshold includes tax and postage, and free-tier sellers must buy labels through eBay"],
  ["Insurance costs $800–$1,500", "Get a quote for the exact activity"],
  ["A $100–$500 metal battery bin handles lithium risk", "No generic bin solves it. Refuse damaged and loose lithium in Phase 0"],
  ["We provide certified data destruction", "Say 'documented secure data erasure' until a certified process backs a stronger claim"],
  ["Windows 10 machines are dead stock", "Normal support ended 14 October 2025, but consumer ESU runs to 12 October 2027. Disclose it clearly"],
  ["Copy Bendigo E-Waste's warehouse model", "Copy its growth sequence: tech skills → own gear → friends and family → small formal pilot → warehouse later"],
  ["8 GB RAM is the Windows 11 minimum", "The official minimum is 4 GB plus TPM 2.0. 8 GB is a sensible refurbisher's choice, not a requirement"],
  ["Batteries ship with a 'road transport only' label", "Check Australia Post's current dangerous goods guide. Lithium rules are stricter than older guides said"],
];

C.doubleCheck = [
  ["'Australia generates over 500,000 tonnes of e-waste a year'", "Unverified figure from the first idea list. Find a primary source before using it."],
  ["Tech Savvy Dubbo as a partner", "Unverified name. Confirm the business exists and what it does."],
  ["NSW battery regulation starting 1 October 2026", "Rests on secondary sources. Check the EPA page and the Act."],
  ["The Ward e-waste bill (over 100 t a year as a scheduled activity)", "Introduced in 2025. Whether it passed is unconfirmed."],
  ["Whylandra operating under EPL 6058", "From the research notes. Confirm on the EPA public register."],
  ["Side venture and your job at Avance", "Check whether using work hours or gear for a side venture is okay. Easier to sort out now than later."],
];

/* ---------- Decision helpers ---------- */
C.wizards = {
  epl: {
    title: "Do I need an EPA licence?",
    intro: "A rough guide to the Environment Protection Licence question. It doesn't replace the EPA's answer.",
    start: "q1",
    nodes: {
      q1: {q: "Will you receive more than about 100 tonnes of e-waste a year?", hint: "A 20–30 device pilot is well under one tonne. A laptop weighs about 2 kg.", o: [["Yes", "rBig"], ["No", "q2"], ["Not sure", "q2"]]},
      q2: {q: "Will you shred, crush, granulate or otherwise mechanically process e-waste on site?", hint: "Phase 0 doesn't. Manual disassembly for parts is different from industrial processing.", o: [["Yes", "rProcess"], ["No", "q3"]]},
      q3: {q: "Will you store loose or damaged lithium batteries, or other hazardous waste?", hint: "Phase 0 refuses loose, swollen, wet or fire-affected batteries.", o: [["Yes", "rHaz"], ["No", "rSmall"]]},
    },
    results: {
      rBig: {tone: "warn", t: "This is licensing territory. Get it in writing.", b: ["A 2025 private member's bill proposed making the receipt and processing of more than 100 tonnes of e-waste a year a scheduled activity. Whether it passed is unconfirmed.", "Scheduled-activity amendments commenced on 29 May 2026. Read the current Schedule 1 and the thresholds for outside the regulated area, then ask the EPA."]},
      rProcess: {tone: "warn", t: "Mechanical processing changes the picture.", b: ["Processing pushes you toward resource recovery and waste-processing scheduled activities, AS 5377 expectations and a resource-recovery planning classification, which probably means a DA.", "It's well outside the Phase 0 design. Outsource processing to a verified recycler."]},
      rHaz: {tone: "warn", t: "Hazardous waste rules apply whatever your volume.", b: ["Classification, storage and tracking (Part 4 of the POEO (Waste) Regulation 2014) apply even below licence thresholds.", "Phase 0 is designed to refuse these items so this question doesn't arise."]},
      rSmall: {tone: "ok", t: "An EPL is unlikely at shed scale, but that isn't the whole answer.", b: ["Being under a threshold doesn't make a waste activity lawful. Planning consent may still be needed, and the EPA has warned that accepting and sorting unwanted material can make a site a waste facility.", "Section 143 still applies: your leftovers must go to a place that can lawfully take them. Licence obligations can't be handed to contractors."]},
    },
    ask: ["Does a small refurbish-and-resell operation that receives a few hundred kilograms a year need an EPL?", "Do damaged lithium batteries count as hazardous waste for storage purposes?", "What changed in the scheduled activities that commenced on 29 May 2026?", "What's the status of the 2025 e-waste bill (over 100 t a year)?"],
    call: "NSW EPA Environment Line: 131 555",
  },
  shd: {
    title: "Do I need a second-hand dealer licence?",
    intro: "Based on NSW Fair Trading guidance in the repo. Fair Trading has the final word.",
    start: "q1",
    nodes: {
      q1: {q: "Will the business buy, sell or exchange second-hand electronic goods?", hint: "Phones, laptops, tablets and similar are prescribed goods.", o: [["Yes", "q2"], ["No, client gear only goes back to the client", "rNone"]]},
      q2: {q: "Will you pay suppliers for any items?", hint: "Buying stock, trade-ins or buybacks.", o: [["Yes", "rNeed"], ["No, everything is donated free", "q3"]]},
      q3: {q: "Could the operation fairly be called a 'recycling and rubbish collection program'?", hint: "This is the exemption wording on the Fair Trading page. Whether refurbish-and-resell fits it is the open question.", o: [["Yes or maybe", "rMaybe"], ["No", "rNeed"]]},
    },
    results: {
      rNone: {tone: "ok", t: "Probably no dealer licence for that activity.", b: ["A service where client-owned devices are wiped or repaired and returned isn't buying or selling second-hand goods.", "Repair notices and consumer law still apply to that work."]},
      rNeed: {tone: "warn", t: "A licence is likely.", b: ["Fees: $692 for 1 year, $1,574 for 3, $2,456 for 5 (2026–27). It belongs to the legal entity and needs a fit-and-proper check.", "Duties include notifying business and storage premises, signs, supplier ID and an ownership statement, electronic records sent to police within 3 days, and a 14-day hold without altering the goods.", "Open question: does wiping or repairing count as altering goods during the hold?"]},
      rMaybe: {tone: "info", t: "The exemption might apply, but nobody has confirmed it.", b: ["Fair Trading's page says no licence is needed to engage in recycling and rubbish collection programs. Whether free collection → refurbish → resell → recycle the rest counts hasn't been confirmed.", "Get the answer in writing, or apply for a formal exemption."]},
    },
    ask: ["Is free collection, wipe, refurbish, resell and recycle a 'recycling and rubbish collection program'?", "If I need a licence, can I wipe or repair during the 14-day hold?", "Does a donated item count as 'acquired'? Are game consoles covered?", "Can an entity that already holds a licence add my shed as a notified premises?"],
    call: "NSW Fair Trading: 13 32 20 · exemptions: licensing.exemptions@customerservice.nsw.gov.au",
  },
  da: {
    title: "Will Council see it as a home business?",
    intro: "Based on the Dubbo LEP research. Council's written answer is the gate.",
    start: "q1",
    nodes: {
      q1: {q: "Where will the work happen?", o: [["At home (the proposed home site)", "q2"], ["Industrial or commercial premises", "rIndustrial"]]},
      q2: {q: "Is the total business floor area 30 m² or less?", hint: "Dubbo's LEP caps home-business floor area at 30 m².", o: [["Yes", "q3"], ["No", "rDA"]]},
      q3: {q: "Will people drop off without an appointment, or browse and buy on site?", hint: "Phase 0 uses pre-approved Tuesday/Saturday intake and online sales.", o: [["No, appointments and online sales only", "q4"], ["Yes", "rDA"]]},
      q4: {q: "Will anything be stored outside, or dismantled at volume?", o: [["No", "rHome"], ["Yes", "rDA"]]},
    },
    results: {
      rHome: {tone: "ok", t: "Home business is the defensible pathway. Still get Council's answer in writing.", b: ["Keep it under 30 m², one resident operator, pre-approved intake, no unattended bin, no outdoor stockpile, low traffic, no shredding, online sales and no walk-in showroom.", "Planning and the lease are separate gates. The lease restricts the garage to parking and doesn't warrant the storage area is watertight. The shed must be dry and secure first."]},
      rDA: {tone: "warn", t: "Expect a DA or a different classification.", b: ["The activity may be classed as a home industry, a goods repair and reuse premises, or a resource recovery facility.", "If the site is R2 Low Density Residential, a goods repair and reuse premises may be prohibited. Ask Council before spending money."]},
      rIndustrial: {tone: "info", t: "Industrial zoning suits the activity better, at a cost.", b: ["Check the land-use definition and whether a change of use needs a DA.", "Benchmark: a 190–200 m² Dubbo industrial unit was listed at $395 a week plus GST."]},
    },
    ask: ["What's the zoning of the property, and is a home business with appointment pickups and online sales permitted without consent?", "What triggers a DA if the public drops off or buys on set days?", "Is storing e-waste in a shed a waste-facility use under the LEP?"],
    call: "Dubbo Regional Council planning · DA fee quotes: online.applications@dubbo.nsw.gov.au",
  },
};

/* ---------- Study plan ---------- */
C.rhythm = [
  ["09:00", "11:00", "Primary-source reading", "Legislation, standards, EPA pages. Keep a parking-lot note open so when the phone rings you jot where you were."],
  ["11:00", "12:30", "Videos and webinars", "These survive interruptions: you can pause and rewind. Quiz yourself after each 5–10 minute chunk."],
  ["13:00", "15:30", "Hands-on work", "Labs, spreadsheets, drafting."],
  ["15:30", "16:30", "Emails to outside people", "Council, EPA, recyclers. Replies come back while you're on calls."],
  ["16:30", "17:00", "Update the learning log", "Glossary, open questions, and what you'd get wrong."],
];

C.tracks = {
  A: {name: "Rules and business", sub: "From your research notes. Eight weeks, weekdays only.", weeks: [
    {t: "Landscape and vocabulary", f: "How e-waste flows in Australia: the NTCRS, product stewardship law, the co-regulators.",
      read: [{t: "DCCEEW: NTCRS", u: "https://www.dcceew.gov.au/environment/protection/waste/product-stewardship/products-schemes/television-computer-recycling-scheme"}, {t: "DCCEEW: e-waste", u: "https://www.dcceew.gov.au/environment/protection/waste/e-waste"}, {t: "Review of the Product Stewardship Act 2011", q: "Review of the Product Stewardship Act 2011 including NTCRS"}, {t: "NTCRS operational review", q: "NTCRS operational review"}, {t: "ANZRP e-stewardship", u: "https://www.anzrp.com.au/about/e-stewardship/"}, {t: "What happens to e-waste", doc: "WHAT-HAPPENS-TO-EWASTE"}, {t: "TechCollect reuse deep dive", doc: "TECHCOLLECT-REUSE-DEEP-DIVE"}],
      tasks: ["Read the NTCRS page and note the 2026–27 target", "Read the two reviews and write a 3-line note on each", "Sketch how a Dubbo laptop reaches a recycler (use the Where it goes page)", "Add 10 terms to your glossary"],
      d: "One-page flow map plus glossary"},
    {t: "NSW rules", f: "POEO Act, scheduled activities and EPL thresholds, waste classification, waste tracking.",
      read: [{t: "EPA: licensing thresholds", u: "https://www.epa.nsw.gov.au/Your-environment/Waste/waste-overview/licensing/reduced-licensing-thresholds"}, {t: "EPA Guide to Licensing", q: "NSW EPA guide to licensing"}, {t: "Waste Classification Guidelines Part 1", q: "NSW EPA Waste Classification Guidelines Part 1"}, {t: "Waste that must be tracked", u: "https://www.epa.nsw.gov.au/Your-environment/Waste/tracking-transporting-hazardous-waste/waste-must-tracked"}, {t: "Environmental Legislation Amendment Act 2025", q: "NSW Environmental Legislation Amendment Act 2025 EPA summary"}, {t: "Planning and NSW waste law", doc: "BACKLOG-01-05-PLANNING-LEGAL"}, {t: "Legal and licensing", doc: "LEGAL-LICENSING"}],
      tasks: ["Read the threshold table for outside the regulated area", "Learn the six waste classes", "Work through the EPA licence decision helper", "Write your questions for the EPA (131 555)"],
      d: "'Do I need an EPL?' decision tree, plus questions for the EPA"},
    {t: "Standards and exports", f: "AS 5377:2022, JAS-ANZ, R2 and e-Stewards for comparison, Basel, export permits.",
      read: [{t: "AS 5377:2022", q: "Standards Australia AS 5377:2022"}, {t: "JAS-ANZ certification", q: "JAS-ANZ how certification works"}, {t: "Sircel R2v3", u: "https://sircel.com/2024/09/03/sircel-is-r2v3-certified/"}, {t: "Control of e-waste exports", u: "https://www.dcceew.gov.au/environment/protection/hazardous-waste/control-e-waste"}, {t: "Melbourne recycler fine (case study)", q: "Melbourne e-waste recycler fined Singapore shipment"}, {t: "Downstream stewardship research", doc: "BACKLOG-06-12-DOWNSTREAM-STEWARDSHIP"}],
      tasks: ["List what AS 5377 covers: collection, storage, transport, treatment", "Note what changed for non-hazardous e-waste on 1 January 2025", "Read the fine case study and write what went wrong", "Draft a compliance checklist"],
      d: "Compliance checklist"},
    {t: "Data destruction", f: "NIST 800-88 Rev. 2, ASD media guidance, Privacy Act basics, and a hands-on lab.",
      read: [{t: "NIST SP 800-88 Rev. 2", u: "https://csrc.nist.gov/pubs/sp/800/88/r2/final"}, {t: "ASD ISM: guidelines for media", u: "https://www.cyber.gov.au/business-government/asds-cyber-security-frameworks/ism/cyber-security-guidelines/guidelines-for-media"}, {t: "nwipe / ShredOS", q: "nwipe ShredOS GitHub"}, {t: "Bench toolkit and NIST verification", doc: "claudegaps-research~03-BENCH-TOOLKIT"}, {t: "Sanitisation certificate template", doc: "templates~data-sanitisation-certificate"}],
      tasks: ["Read Rev. 2 and its FAQ; define Clear, Purge, Destroy in your own words", "Run nwipe or ShredOS in a VM or on your own spare drive (never client or work kit)", "Fill in the sanitisation certificate template for your test drive", "Write what your lab can't prove"],
      d: "Working lab and a sample certificate of sanitisation"},
    {t: "Batteries and safety", f: "B-cycle, dangerous goods, WHS, fire case studies.",
      read: [{t: "SafeWork NSW: lithium-ion", u: "https://www.safework.nsw.gov.au/hazards-a-z/lithium-ion-batteries"}, {t: "EPA: embedded batteries", u: "https://www.epa.nsw.gov.au/Your-environment/Recycling-and-reuse/household-recycling-overview/embedded-batteries"}, {t: "Victorian waste facility fires report", q: "Fires at waste and resource recovery facilities report Victoria"}, {t: "B-cycle", u: "https://bcycle.com.au/"}, {t: "WMRR submission (15 May 2026)", q: "WMRR submission national guideline end-of-life lithium batteries"}, {t: "WHS and lithium research", doc: "BACKLOG-21-25-COMPLIANCE-DATA-SAFETY"}],
      tasks: ["Write your refuse list for batteries", "Watch one lithium battery fire investigation", "Draft a damaged-battery emergency path", "Note what an insurer will ask"],
      d: "Draft battery handling procedure"},
    {t: "Downstream and money", f: "Who buys the fractions, commodity prices, refurb resale values.",
      read: [{t: "eBay AU selling fees", u: "https://www.ebay.com.au/help/selling/fees-credits-invoices/selling-fees-managed-payments-sellers?id=4822"}, {t: "Pricing and valuation", doc: "claudegaps-research~04-PRICING-VALUATION"}, {t: "Market, cost and tax", doc: "BACKLOG-17-20-MARKET-COST-TAX"}, {t: "Costs", doc: "COSTS"}],
      tasks: ["Ring two or three recyclers about who takes their fractions", "Pull 10 eBay sold listings for a common business laptop", "Fill in the Money model with your own numbers", "Add a fire and a contamination scenario"],
      d: "Spreadsheet model with fire and contamination scenarios"},
    {t: "Dubbo market", f: "DA and zoning, Orana customers, competitors, existing recyclers.",
      read: [{t: "Do I need a DA?", u: "https://www.dubbo.nsw.gov.au/Builders-Developers/Overview-of-Application-Process/do-i-need-a-da"}, {t: "Whylandra", u: "https://www.dubbo.nsw.gov.au/Households-Residents/Rubbish-Recycling-and-Sustainability/whylandra-waste-recycling-centre"}, {t: "Good360, Compnow and the Device Bank in Dubbo", doc: "GOOD360-COMPNOW-NATIONAL-DEVICE-BANK-DUBBO"}, {t: "Branch-entry playbook", doc: "DUBBO-ITAD-BRANCH-ENTRY-PLAYBOOK"}, {t: "Call scripts", doc: "CALL-SCRIPTS"}, {t: "Email drafts", doc: "EMAIL-DRAFTS"}],
      tasks: ["Ask Council planning about the DA questions", "Map 10 Orana organisations that refresh IT fleets", "Send three outreach emails", "Track replies on the People page"],
      d: "Market map, plus outreach emails sent"},
    {t: "Synthesis", f: "Pull it together and decide.",
      read: [{t: "Master findings", doc: "MASTER-FINDINGS-ALL-CHATS"}, {t: "Gaps", doc: "GAPS"}, {t: "Launch checklist", doc: "launch-checklist"}],
      tasks: ["Write a one-page business plan", "Build a risk register", "List the unknowns that only calls or a pilot can answer", "Write your go/no-go thoughts"],
      d: "One-page plan, risk register, list of unknowns, go/no-go"},
  ]},
  B: {name: "Bench skills", sub: "From the repo's skills research. Practise on safe devices only.", weeks: [
    {t: "Batteries, WHS, ownership, privacy, locks", f: "What you must refuse, and how to say so.", read: [{t: "Front-door triage", doc: "RESEARCH-01-FRONT-DOOR-TRIAGE"}, {t: "Triage decision system", doc: "claudegaps-research~01-TRIAGE-DECISION-SYSTEM"}, {t: "Intake policy", doc: "INTAKE-POLICY"}], tasks: ["Learn the Tier 0 list", "Practise refusal wording", "Fill in a chain-of-custody record"], d: "Correctly refuse a mixed box and complete a safe record"},
    {t: "Device anatomy, labels, serials, chargers, ESD, storage", f: "Know what you're holding.", read: [{t: "Category knowledge", doc: "claudegaps-research~02-CATEGORY-KNOWLEDGE"}, {t: "Asset transfer template", doc: "templates~asset-transfer-and-chain-of-custody"}], tasks: ["Identify CPU, RAM, storage, ports, battery on ten devices", "Label each with an asset ID"], d: "Identify and label ten safe practice devices"},
    {t: "Inventory, boot, firmware, storage, memory", f: "Windows and Linux diagnostics.", read: [{t: "Microsoft Learn: hardware troubleshooting", u: "https://learn.microsoft.com/en-us/training/modules/explore-physical-hardware-troubleshooting/"}, {t: "Windows 11 requirements", u: "https://support.microsoft.com/en-us/windows/experience/compatibility/windows-11-system-requirements"}, {t: "smartmontools", u: "https://www.smartmontools.org/"}, {t: "Memtest86+", u: "https://memtest.org/"}], tasks: ["Run SMART and NVMe health reads", "Run a memory test", "Write what each tool can't prove"], d: "Five redacted diagnostic reports"},
    {t: "Displays, keyboards, ports, audio, wireless, camera, thermals", f: "Repeatable bench tests.", read: [{t: "Bench toolkit", doc: "claudegaps-research~03-BENCH-TOOLKIT"}, {t: "Triage skills guide (generic, see caveats)", doc: "agyDOCS~Triage-Skills-Guide"}], tasks: ["Write a test sequence with timings", "Run it on five devices"], d: "Five repeatable bench tests with timings"},
    {t: "Sanitisation, account removal, MDM escalation, certificates", f: "Data and locks without ever asking for a password.", read: [{t: "NIST SP 800-88 Rev. 2", u: "https://csrc.nist.gov/pubs/sp/800/88/r2/final"}, {t: "Sanitisation certificate", doc: "templates~data-sanitisation-certificate"}], tasks: ["Simulate an Activation Lock case", "Simulate an Autopilot or MDM case", "Issue a PASS / FAIL / DESTROY record"], d: "Process simulated lock and data cases without passwords"},
    {t: "Disassembly, module replacement, parts labelling", f: "Repair within limits.", read: [{t: "iFixit repair guides", u: "https://www.ifixit.com/Info/Repair_Guide"}, {t: "Hugh Jeffreys", u: "https://www.hughjeffreys.com/"}], tasks: ["Replace RAM, SSD and a battery on donor devices", "Re-run post-repair tests"], d: "Repair two safe donor devices and pass post-repair tests"},
    {t: "Phones, tablets, consoles, network devices", f: "Route decisions by category.", read: [{t: "Category knowledge", doc: "claudegaps-research~02-CATEGORY-KNOWLEDGE"}, {t: "YouTube watch list", doc: "claudegaps-research~06-YOUTUBE-WATCHLIST"}], tasks: ["Write a category sheet for each", "Mark partner-only cases"], d: "Category sheets and partner-only cases identified"},
    {t: "Pricing, listings, consumer law, warranty, pilot review", f: "Sell honestly and decide.", read: [{t: "Pricing and valuation", doc: "claudegaps-research~04-PRICING-VALUATION"}, {t: "Sale and recall record", doc: "templates~sale-and-recall-record"}, {t: "Skills and learning path", doc: "RESEARCH-02-SKILLS-LEARNING-PATH"}], tasks: ["Write one truthful listing with known faults disclosed", "Run the per-item profit test", "Make a go/no-go call"], d: "A truthful listing, a cost model and a go/no-go decision"},
  ]},
};

C.techniques = [
  ["hi", "High utility", "Practice testing; distributed (spaced) practice", "Work across ages, abilities and kinds of test. Swap rereading for delayed recall."],
  ["mid", "Moderate utility", "Elaborative interrogation; self-explanation; interleaved practice", "Ask why a rule exists. Explain how it connects to the business. Mix topics in a session."],
  ["lo", "Low utility", "Summarising; highlighting; keyword mnemonics; imagery for text; rereading", "What most people default to. Fine as a starting point, weak on their own."],
];
C.howTo = [
  ["Quiz yourself instead of rereading", "After each 5–10 minute chunk of a video or document, look away and write what you remember. Then check. Every doc in the library has a recall check for this."],
  ["Space it out", "Spend the first 10 minutes of each day recalling yesterday's material. On Monday, retest last week's content before starting anything new. The flashcards schedule this for you."],
  ["Explain as you go", "For each regulation, write a line or two on why it exists and how it connects to the business idea. The Rules page uses a three-line note: what it requires, who it applies to, what you're unsure of."],
  ["Mix topics", "Don't do all of batteries in one block. Weave a bit of licensing and data destruction in alongside it."],
  ["Make interruptions cheap", "Pick up from a half-written recall note rather than a half-watched video. Use the parking lot in the learning log."],
  ["Use playback speed", "One study found faster playback didn't hurt engagement and improved learning efficiency (abstract only)."],
];

/* ---------- Practice ---------- */
C.glossary = [
  ["NTCRS", "National Television and Computer Recycling Scheme. Federal co-regulatory scheme: TV and computer importers and manufacturers fund collection and recycling through approved arrangements. Target: 80% in 2026–27."],
  ["Co-regulatory arrangement", "An organisation approved to run NTCRS collection and recycling on behalf of liable companies, such as ANZRP (TechCollect)."],
  ["ANZRP / TechCollect", "A not-for-profit NTCRS co-regulator and its collection service. Equipment surrendered to TechCollect is recycled in Australia and not resold. ANZRP supports reuse separately through PonyUp, Reconnect and The Laptop Initiative."],
  ["Recycling and Waste Reduction Act 2020", "Federal law covering product stewardship and waste export regulation. Research says it replaced the Product Stewardship Act 2011 (verify)."],
  ["POEO Act", "Protection of the Environment Operations Act 1997 (NSW). The main pollution law: scheduled activities, Environment Protection Licences, waste offences including section 143."],
  ["WARR Act", "Waste Avoidance and Resource Recovery Act 2001 (NSW). Sets the waste hierarchy: avoid, reuse, recycle, dispose."],
  ["EPL", "Environment Protection Licence. Issued by the NSW EPA for scheduled activities above set thresholds."],
  ["Scheduled activity", "An activity in Schedule 1 of the POEO Act that needs an EPL once its threshold is met."],
  ["Regulated area", "The Sydney-centred part of NSW where lower waste thresholds apply. Thresholds for resource recovery are higher outside it."],
  ["Section 143 (POEO)", "Offence to take waste to a place that can't lawfully be used as a waste facility for it. Applies to your leftovers."],
  ["Waste classification", "NSW EPA process: the generator classifies waste into one of six classes before it's moved or disposed of."],
  ["Waste tracking", "Movement records for hazardous and certain other wastes, under Part 4 of the POEO (Waste) Regulation 2014."],
  ["Product Lifecycle Responsibility Act 2025", "New NSW product stewardship framework. Its first regulation (2026) targets batteries."],
  ["AS 5377:2022", "Australian standard for collecting, storing, transporting and treating end-of-life electrical and electronic equipment. Replaced AS/NZS 5377:2013 in Australia. Mandatory in practice through contracts, not by blanket law."],
  ["JAS-ANZ", "Joint Accreditation System of Australia and New Zealand. Accredits the bodies that certify operators against standards such as AS 5377."],
  ["R2v3 / e-Stewards", "International responsible-recycling certifications. Sircel is R2v3 certified."],
  ["Basel Convention", "International treaty controlling cross-border movement of hazardous waste. Since 1 January 2025 it also controls non-hazardous e-waste such as PCBs and CRTs."],
  ["NIST SP 800-88 Rev. 2", "US media sanitisation guideline, September 2025. Guidance for running a sanitisation program, not a product certification."],
  ["Clear", "NIST level: logical techniques that protect against simple, non-invasive data recovery, such as overwriting user-addressable storage."],
  ["Purge", "NIST level: techniques that make recovery infeasible even with state-of-the-art lab methods, such as block erase or cryptographic erase."],
  ["Destroy", "NIST level: physical destruction that leaves the media unusable and recovery infeasible."],
  ["Cryptographic erase", "Sanitising by destroying the encryption key so encrypted data can't be read. Used on modern Apple hardware and self-encrypting drives."],
  ["ASD ISM", "The Australian Signals Directorate's Information Security Manual. Its guidelines for media cover sanitisation and destruction."],
  ["ITAD", "IT asset disposition. Managed retirement of IT gear: collection, chain of custody, sanitisation, value recovery and reporting."],
  ["Chain of custody", "A record of who held an asset, when, and in what state, from intake to final outcome."],
  ["Documented secure data erasure", "The wording the repo recommends until a certified process supports 'certified destruction'."],
  ["Second-hand dealer licence", "NSW licence to buy, sell or exchange prescribed goods, including electronics. $692 for one year (2026–27)."],
  ["14-day hold", "Licensed dealers must keep regulated goods for 14 days and not alter them. Whether wiping counts as altering is an open question."],
  ["Home business (Dubbo LEP)", "A low-impact business run from a dwelling. Dubbo caps its floor area at 30 m²."],
  ["Goods repair and reuse premises", "A planning land-use term distinct from a home business. May be prohibited in an R2 zone."],
  ["R2 zone", "Low Density Residential planning zone. Not to be confused with the R2 recycling certification."],
  ["CRC", "Community Recycling Centre. Free household drop-off for problem wastes. Whylandra is one."],
  ["Whylandra", "Dubbo Regional Council's Waste and Recycling Centre. Free household e-waste, NTCRS participant via DHL Drop Zone."],
  ["AMR", "Australian Metal Recycling (Scrap Metal Services Pty Ltd), 34 Mountbatten Drive Dubbo, formerly Matthews Metal Management. Free e-waste, excluding lithium-ion."],
  ["NetWaste", "Regional waste group of Central West and Orana councils. Says Sims collects e-waste from most members."],
  ["B-cycle", "National battery stewardship scheme. Drop-off sites must register and meet controls."],
  ["MobileMuster", "The mobile industry's recycling program for phones, chargers and accessories. Not a general tablet or loose-battery route."],
  ["PCBU", "Person conducting a business or undertaking: the main duty holder under WHS law."],
  ["Thermal runaway", "A self-sustaining overheating reaction in a lithium cell that leads to fire. Lithium batteries are the likely leading cause of waste facility fires."],
  ["Activation Lock / FRP", "Apple's Activation Lock and Google's Factory Reset Protection tie a device to an account. A locked device can't be legitimately resold."],
  ["MDM / Autopilot", "Enterprise device management that re-enrols a device to an organisation after reset. Needs the owner's administrator to release."],
  ["ACL", "Australian Consumer Law. Consumer guarantees apply to second-hand goods sold by a business. Defects disclosed before sale aren't covered by acceptable quality."],
  ["Gross margin per labour hour", "The pilot's key metric: sale price minus all direct costs, divided by labour hours."],
  ["Gate fee", "A fee to accept waste. Free household drop-off at Whylandra makes household gate fees unlikely."],
  ["Downstream fractions", "Separated outputs of recycling: steel, aluminium and copper, PCBs, plastics, glass, batteries, residual."],
  ["Triage", "The front-door decision: reuse, repair, parts, recycle or refuse. Probably the highest-value operation in the business."],
  ["National Device Bank", "WorkVentures, Good360 and Good Things Australia (2025). Benchmark device: i5 6th gen or newer, 8 GB RAM, 128 GB SSD, Wi-Fi, webcam, 13.3-inch screen."],
  ["GST threshold", "Registration is compulsory at $75,000 GST turnover."],
];

C.quiz = [
  ["Which edition of AS 5377 now applies in Australia?", ["AS/NZS 5377:2013", "AS 5377:2022", "ISO 5377:2020", "AS 5377:2018"], 1, "Standards Australia issued an Australia-only AS 5377:2022. The 2013 joint edition stays current in New Zealand."],
  ["When was NIST SP 800-88 Rev. 2 published?", ["September 2025", "March 2014", "January 2023", "October 2026"], 0, "Rev. 2 came out in September 2025 and supersedes Rev. 1."],
  ["From 1 January 2025, Basel controls also cover:", ["Only lithium batteries", "Non-hazardous e-waste such as PCBs and CRTs", "Second-hand laptops sold overseas", "Household recycling bins"], 1, "The National EPA page gives printed circuit boards and CRTs as examples."],
  ["Being below an EPA licensing threshold means:", ["You need no other approvals", "Planning consent may still be needed", "You can accept any waste", "Your waste is no longer waste"], 1, "Below threshold doesn't make a waste activity lawful. Planning and section 143 still apply."],
  ["Dubbo's LEP caps home-business floor area at:", ["10 m²", "30 m²", "50 m²", "100 m²"], 1, "30 m². Phase 0 is designed to stay inside it."],
  ["A new one-year NSW second-hand dealer licence (2026–27) costs:", ["$47", "$260", "$692", "$1,574"], 2, "$692 for one year. $1,574 is three years; $47 is a business name; $260 is scrap-metal registration."],
  ["Licensed second-hand dealers must hold regulated goods for:", ["3 days", "7 days", "14 days", "30 days"], 2, "14 days, without altering them. Whether wiping counts as altering is unresolved."],
  ["AMR Dubbo's materials list excludes:", ["Monitors", "Printers", "Lithium-ion", "TVs"], 2, "'Electronic waste excluding lithium ion', which is ambiguous for laptops and phones with embedded batteries."],
  ["What's publicly proven about where AMR Dubbo sends e-waste next?", ["It goes to Sircel Parkes", "It goes to Sims St Marys", "It goes to TechCollect", "Nothing: it's unknown"], 3, "Sircel, ACE, Sims and TechCollect are candidates only."],
  ["TechCollect says equipment surrendered to its stream is:", ["Refurbished and resold", "Recycled in Australia, not resold", "Donated to schools", "Exported for reuse"], 1, "So good gear has to be diverted before it's surrendered."],
  ["The pilot's key economic metric is:", ["Headline sale price", "Number of devices collected", "Gross margin per labour hour", "Tonnes diverted"], 2, "It captures labour, parts, fees, postage and disposal."],
  ["Until a certified process backs it, the repo says to describe wiping as:", ["NIST certified destruction", "Military-grade erasure", "Documented secure data erasure", "Guaranteed unrecoverable"], 2, "Avoid 'certified' language you can't support."],
  ["GST registration is compulsory at a turnover of:", ["$25,000", "$50,000", "$75,000", "$100,000"], 2, "$75,000, confirmed from current ATO guidance."],
  ["The NTCRS recycling target for 2026–27 is:", ["50%", "65%", "80%", "100%"], 2, "Targets rise to 80% in 2026–27."],
  ["Dunlosky et al. (2013) rated which techniques highest?", ["Highlighting and rereading", "Practice testing and spaced practice", "Summarising and imagery", "Keyword mnemonics"], 1, "Both got 'high utility' ratings across ages, abilities and kinds of test."],
  ["Which item is on the Phase 0 priority-accept list?", ["CRT monitors", "Loose lithium batteries", "Business-class laptops", "E-scooter batteries"], 2, "The others are on the refuse list."],
  ["The Phase 0 storage rule is:", ["Store overflow outside", "Shelf full = pause intake", "Rent a warehouse when busy", "Accept everything, sort later"], 1, "Every category gets a physical capacity, and there's no miscellaneous pile."],
  ["In NIST terms, 'Purge' means:", ["Deleting files to the recycle bin", "Recovery infeasible even with state-of-the-art lab techniques", "Physically shredding the drive", "Reinstalling the operating system"], 1, "Destroy is physical destruction. Clear protects against simple recovery."],
  ["The first gate in the launch sequence is:", ["Insurance", "Council classification", "Buying equipment", "Listing stock on eBay"], 1, "Council classification, then lease and workspace, then Fair Trading, insurance, and downstream terms."],
  ["Officeworks Dubbo is best described as:", ["The local e-waste processor", "A retail trade-in and collection channel", "An NTCRS co-regulator", "A battery recycler"], 1, "Not an industrial recycler. It also stopped in-store battery collection in February 2024."],
  ["How does PonyUp support SecondBite?", ["It sends refurbished computers", "It donates 50% of profits", "It runs SecondBite's IT", "It doesn't"], 1, "Profits, not devices."],
  ["Who accredits the bodies that certify operators against AS 5377?", ["NSW EPA", "Standards Australia", "JAS-ANZ", "DCCEEW"], 2, "JAS-ANZ accredits certification bodies."],
  ["NSW waste classification sorts waste into how many classes?", ["Three", "Four", "Six", "Ten"], 2, "Six classes, chosen by whoever generates the waste."],
  ["A Melbourne recycler was fined almost how much for an undeclared e-waste shipment to Singapore?", ["$2,000", "$20,000", "$200,000", "$2 million"], 1, "The container held undeclared circuit boards and lithium batteries."],
  ["Victoria's report found the likely leading cause of waste-facility fires is:", ["Aerosol cans", "Lithium-ion batteries", "Hot ash", "Arson"], 1, "Lithium-ion batteries."],
  ["'R2' on a Dubbo planning map means:", ["Responsible Recycling v2 certification", "Low Density Residential zone", "Resource recovery licence", "A second-hand dealer class"], 1, "Easy to confuse with the R2v3 recycling certification."],
  ["Windows 10 consumer Extended Security Updates in Australia run to:", ["14 October 2025", "12 October 2027", "1 July 2026", "They aren't offered"], 1, "Normal support ended 14 October 2025; consumer ESU runs to 12 October 2027 under current terms."],
  ["Which statement about AS 5377 is accurate?", ["It's a blanket legal mandate for anyone touching e-waste", "It becomes mandatory in practice through contracts and client requirements", "It only applies in New Zealand", "It's a data-wiping standard"], 1, "It's a standard. Contracts, NTCRS arrangements and clients make it bite."],
];

/* ---------- People and market ---------- */
C.contacts = [
  {id: "fairtrading", n: "NSW Fair Trading", r: "Second-hand dealer licence and exemption", ph: "13 32 20", em: "licensing.exemptions@customerservice.nsw.gov.au", ask: C.wizards.shd.ask, doc: "CALL-SCRIPTS"},
  {id: "council", n: "Dubbo Regional Council: planning", r: "Classification, zoning, DA", em: "online.applications@dubbo.nsw.gov.au", note: "Email for DA fee quotes before lodgement.", ask: C.wizards.da.ask, doc: "CALL-SCRIPTS"},
  {id: "epa", n: "NSW EPA Environment Line", r: "Thresholds, hazardous waste, batteries", ph: "131 555", ask: C.wizards.epl.ask, doc: "CALL-SCRIPTS"},
  {id: "amr", n: "Australian Metal Recycling, Dubbo", r: "Downstream for zero-value material", ph: "(02) 6882 1033", ask: ["After I drop e-waste at Dubbo, what is the next physical facility? Legal name and suburb?", "Do batteries need removing from laptops, phones and tablets? What about non-removable ones?", "Is the free service part of the NTCRS, and through which arrangement?", "Which facility in your chain is AS 5377 certified?", "Can a small commercial customer get a weight ticket and recycling certificate?", "Are any fractions exported? Which, and where?"], doc: "AMR-DUBBO-DOWNSTREAM-FORENSIC"},
  {id: "whylandra", n: "Whylandra Waste and Recycling Centre", r: "Council waste", ask: ["What's the commercial e-waste fee?", "What are the NTCRS limits for a business drop-off?", "Who has been Council's e-waste contractor since June 2025?"], doc: "BACKLOG-06-12-DOWNSTREAM-STEWARDSHIP"},
  {id: "joe", n: "Joe, Bendigo E-Waste", r: "Benchmark and mentor", ask: ["What counts as 'good' intake?", "What do you pay for sorted lots, minimum volumes, freight?", "What did the first year actually look like?"], doc: "bendigo-early-days-deep-dive"},
  {id: "insurer", n: "Insurers", r: "Public and product liability", ask: ["Cover for a home-shed electronics refurb with visitors by appointment?", "Lithium battery conditions?", "What evidence of competence do you need?"], doc: "CALL-SCRIPTS"},
  {id: "avance", n: "Avance (employer)", r: "Side-venture check", ask: ["Is a side venture okay, and are there conditions?", "Is any use of work hours or gear off limits?", "Does Avance or a related entity hold a second-hand dealer licence?"], doc: "EMAIL-DRAFTS"},
  {id: "techcollect", n: "TechCollect / ANZRP", r: "Reuse partnership and recycling back end", ask: ["Could a reuse-first operator send failures into your stream?", "What do your reuse partners (PonyUp, Reconnect, The Laptop Initiative) have to meet?"], doc: "TECHCOLLECT-REUSE-DEEP-DIVE"},
  {id: "g1", n: "G1 Asset Management", r: "White-label ITAD", ask: ["White-label pricing for an IT service provider in regional NSW?", "Collection frequency and minimum volumes for Dubbo?"], doc: "DUBBO-ITAD-BRANCH-PATHWAYS-COSTS-PROCESS"},
  {id: "greenbox", n: "Greenbox Partner Program", r: "Formal partner onboarding", ask: ["Partner pricing and rulebook?", "Training requirements and the 14-business-day decision?"], doc: "DUBBO-ITAD-BRANCH-ENTRY-PLAYBOOK"},
  {id: "fliptech", n: "Fliptech Australia", r: "Regional pilot", ask: ["Would you consider a Central West / Orana collection pilot based in Dubbo?", "What would an authorised local operator need to show?"], doc: "FLIPTECH-DUBBO-BRANCH-FEASIBILITY"},
  {id: "dsc", n: "Dubbo Support Center", r: "Social reuse partner", ask: ["Would refurbished laptops help your Digital Sisters and skills work?", "Have you applied to the NSW Device Bank?"], doc: "GOOD360-COMPNOW-NATIONAL-DEVICE-BANK-DUBBO"},
  {id: "tafe", n: "TAFE NSW Dubbo and other RTOs", r: "Training", ask: ["Is UEE20520 available part-time or by RPL?", "What practical assessment is included?", "Are phones, batteries and account locks covered?"], doc: "RESEARCH-02-SKILLS-LEARNING-PATH"},
  {id: "dcceew", n: "DCCEEW e-waste team", r: "Exports and NTCRS", em: "ewaste@dcceew.gov.au", ask: ["Which fractions from a small refurbisher would need an export permit if a downstream buyer exports them?"], doc: "AMR-DUBBO-DOWNSTREAM-FORENSIC"},
];
C.statuses = ["Not started", "Emailed", "Called", "Answered"];

C.local = [
  ["Disposal and collection", [["Whylandra (Council)", "Free household e-waste, CRC, NTCRS via DHL Drop Zone."], ["AMR, 34 Mountbatten Drive", "Free e-waste excluding lithium-ion; downstream unknown."], ["Officeworks, 10 Erskine Street", "Trade-in and Bring it Back; not a processor."]]],
  ["Social reuse", [["Dubbo Support Center", "Good Things partner (Digital Sisters, skills grants), ACNC-registered; appears to meet NSW Device Bank organisation criteria."], ["Digital Nebula, Dubbo", "Good Things skills funding; Device Bank eligibility not obvious."], ["Connecting Community Services", "SecondBite partner with free computer and internet access; no device-supply link found."]]],
  ["Institutional supply", [["NSW public schools", "Separate EDConnect eWaste vendor process; not a casual Phase 0 source."], ["Local businesses and MSPs", "4,500+ businesses in the catchment; the preferred supply."]]],
];
C.models = [
  ["PonyUp for Good", "Corporate fleets about 2–5 years old", "Secure erasure, refurbish, remarket; failures to ANZRP", "About 32% of collected equipment reused; 50% of profits to SecondBite"],
  ["The Reconnect Project", "Phones and tablets of any age; laptops under about 8 years", "Triage, repair, donor parts, erase; sell cheaply or give through social services", "4,800+ devices distributed"],
  ["The Laptop Initiative", "Good working laptops, usually 4 years or newer, already wiped", "Fast corporate-to-charity handover with little warehousing", "Strict intake, no repair program"],
  ["Sircel", "Council and commercial e-waste", "Industrial triage, Blancco, testing, refurbish; shred failures", "2,350 reused assets in FY2023-24; administration in late 2025"],
  ["Bendigo E-Waste", "Now broad intake; started with own and friends' gear", "Keep devices whole, restore first, donor parts, scrap last", "Tech-first founder; warehouse came later"],
];
C.pathways = [
  ["Greenbox Partner Program", "Published onboarding: application, 12-month plan, references, training, 14-business-day decision target. No public joining fee found."],
  ["G1 white-label ITAD", "Cheapest operationally: you own the customer, G1 collects, sanitises and reports. No warehouse at launch."],
  ["Fliptech regional pilot", "Strongest model fit and upside, but no public partner program, so it needs a negotiated pilot."],
  ["WV Technologies partner", "Six hubs in five states; likely a company-backed hub."],
  ["Iron Mountain partner + ALM", "Strongest corporate capability, least independently openable."],
  ["Renew IT depot proposal", "Mature depot model; likely corporate-led."],
  ["Shred-X branch proposal", "Regional NSW coverage; a Dubbo site needs secure-destruction route economics."],
];
C.benchmarks = [
  ["NSW second-hand dealer licence (1 yr)", "$692", "Verified"],
  ["Business name (1 yr / 3 yr)", "$47 / $108", "Verified"],
  ["New company registration", "$636 + $342 a year review", "Verified"],
  ["Scrap-metal registration (3 yr, only if dealing scrap)", "$260", "Verified"],
  ["Secure business storage, 18 m²", "$125 a month incl. GST", "Public listing"],
  ["Dubbo industrial unit, 190–200 m²", "$395 a week + GST", "Public listing"],
  ["Blancco SMB Select 50 bundle", "$982.30", "Public listing"],
  ["National minimum wage", "$26.44 an hour", "Verified"],
  ["Full-time minimum wage + 12% super", "$58,525.38 a year", "Calculated"],
];
C.calcDefaults = {devices: 12, reusePct: 45, partsPct: 20, price: 260, partsCost: 25, feePct: 0, post: 18, laborReuse: 120, laborOther: 20, recycleCost: 2, partsValue: 30, rate: 35, insurance: 80, licence: 1, storage: 0, incidentPct: 3, incidentCost: 15000};
